The Pedigree Project: Machine Class Reference
Machine Class Reference abstract
#include <Machine.h>
Public Member Functions
virtual void initialise ()=0
virtual void initialise2 ()
Called after debugger startup.
virtual void initialise3 ()
Called after processor startup - for thread creation etc.
virtual void deinitialise ()
bool isInitialised ()
virtual void initialiseDeviceTree ()
virtual Serial * getSerial (size_t n)=0
virtual size_t getNumSerial ()=0
virtual Vga * getVga (size_t n)=0
virtual size_t getNumVga ()=0
virtual IrqManager * getIrqManager ()=0
virtual SchedulerTimer * getSchedulerTimer ()=0
virtual Timer * getTimer ()=0
virtual Keyboard * getKeyboard ()=0
virtual void setKeyboard (Keyboard *kb)=0
Static Public Member Functions
static Machine & instance ()
Protected Attributes
bool m_bInitialised
Private Member Functions
Machine (const Machine &)
Machine & operator= (const Machine &)
Friends
void system_reset ()
Detailed Description
This is an abstraction on a machine, or board. It provides functions to retrieve Timers, Serial controllers, VGA controllers, Ethernet controllers etc, without having to know the exact implementation required or memory map. It also provides a "probe" function, which will attempt to detect if a machine is present.
Definition at line 41 of file include/pedigree/kernel/machine/Machine.h.
Member Function Documentation
virtual Keyboard* Machine::getKeyboard () pure virtual
Returns the keyboard device.
Implemented in Pc, HostedMachine, ArmBeagle, Mac, ArmVersatile, Bonito64, and Malta.
Referenced by Debugger::start().
virtual size_t Machine::getNumSerial () pure virtual
Returns the number of Serial device.
Implemented in Pc, HostedMachine, ArmBeagle, Mac, ArmVersatile, Bonito64, Malta, and Db1500.
virtual size_t Machine::getNumVga () pure virtual
Returns the number of VGA devices.
Implemented in Pc, HostedMachine, ArmBeagle, Mac, ArmVersatile, Bonito64, Malta, and Db1500.
Referenced by FramebufferFile::command().
virtual SchedulerTimer* Machine::getSchedulerTimer () pure virtual
Returns the SchedulerTimer device.
Implemented in Pc, HostedMachine, ArmBeagle, Mac, ArmVersatile, Bonito64, Malta, and Db1500.
Referenced by PerProcessorScheduler::initialise().
virtual Serial* Machine::getSerial (size_t n) pure virtual
Returns the n'th Serial device.
Implemented in Pc, HostedMachine, ArmBeagle, Mac, ArmVersatile, Bonito64, Malta, and Db1500.
Referenced by SlamCommand::execute(), BootIO::initialise(), HostedTimer::irq(), and Rtc::irq().
virtual Timer* Machine::getTimer () pure virtual
Returns the n'th Timer device.
Implemented in Pc, HostedMachine, ArmBeagle, Mac, ArmVersatile, Bonito64, Malta, and Db1500.
Referenced by Semaphore::acquireWithResult(), RequestQueue::destroy(), CacheManager::initialise(), RequestQueue::initialise(), IntervalTimer::IntervalTimer(), HidInputManager::keyDown(), Log::LogEntry::operator<<(), WaitCleanup::terminated(), TimeoutGuard::TimeoutGuard(), HidInputManager::timer(), UptimeFile::writeBytewise(), and TimeoutGuard::~TimeoutGuard().
virtual Vga* Machine::getVga (size_t n) pure virtual
Returns the n'th VGA device.
Implemented in Pc, HostedMachine, ArmBeagle, Mac, ArmVersatile, Bonito64, Malta, and Db1500.
Referenced by FramebufferFile::command(), BootIO::initialise(), TextIO::initialise(), VbeDisplay::setScreenMode(), and VmwareGraphics::setScreenMode().
virtual void Machine::initialise () pure virtual
Initialises the machine.
Implemented in Pc, HostedMachine, Mac, ArmBeagle, ArmVersatile, Bonito64, Malta, and Db1500.
virtual void Machine::initialiseDeviceTree () inline virtual
Initialises the machine's base device tree, if one exists, to prefill the tree with those devices that are not otherwise able to be detected via some sort of bus support.
Reimplemented in Pc, ArmBeagle, Mac, ArmVersatile, and HostedMachine.
Definition at line 74 of file include/pedigree/kernel/machine/Machine.h.
virtual void Machine::setKeyboard (Keyboard * kb) pure virtual
Sets the keyboard device.
Implemented in Pc, HostedMachine, ArmBeagle, and ArmVersatile.
The documentation for this class was generated from the following files:
include/pedigree/kernel/machine/Machine.h
Beagle.cc
Versatile.cc
Db1500.cc
hosted/Machine.cc
Mac.cc
Bonito64.cc
Malta.cc