The Pedigree Project: ArmBeagle Class Reference
ArmBeagle Class Reference
#include <Beagle.h>
Public Member Functions
virtual void initialise ()
virtual void initialise2 ()
Called after debugger startup.
virtual Serial * getSerial (size_t n)
virtual size_t getNumSerial ()
virtual Vga * getVga (size_t n)
virtual size_t getNumVga ()
virtual IrqManager * getIrqManager ()
virtual SchedulerTimer * getSchedulerTimer ()
virtual Timer * getTimer ()
virtual Keyboard * getKeyboard ()
virtual void setKeyboard (Keyboard *kb)
virtual void initialiseDeviceTree ()
Public Member Functions inherited from Machine
virtual void initialise3 ()
Called after processor startup - for thread creation etc.
virtual void deinitialise ()
bool isInitialised ()
Static Public Member Functions
static Machine & instance ()
Static Public Member Functions inherited from Machine
static Machine & instance ()
Private Member Functions
ArmBeagle ()
ArmBeagle (const ArmBeagle &)
ArmBeagle & operator= (const ArmBeagle &)
virtual ~ArmBeagle ()
Private Attributes
ArmBeagleSerial m_Serial [3]
GPTimer m_Timers [11]
ArmBeagleVga m_Vga
ArmBeagleKeyboard m_Keyboard
Static Private Attributes
static ArmBeagle m_Instance
Additional Inherited Members
Protected Attributes inherited from Machine
bool m_bInitialised
Detailed Description
Concretion of the abstract Machine class for an ArmBeagle board.
Definition at line 32 of file Beagle.h.
Constructor & Destructor Documentation
ArmBeagle::ArmBeagle () private
Default constructor, does nothing.
Definition at line 228 of file Beagle.cc.
Referenced by setKeyboard().
ArmBeagle::~ArmBeagle () private virtual
Virtual destructor, does nothing.
Definition at line 231 of file Beagle.cc.
Referenced by setKeyboard().
Member Function Documentation
Keyboard * ArmBeagle::getKeyboard () virtual
Returns the keyboard device.
Implements Machine.
Definition at line 223 of file Beagle.cc.
size_t ArmBeagle::getNumSerial () virtual
Returns the number of Serial device.
Implements Machine.
Definition at line 197 of file Beagle.cc.
size_t ArmBeagle::getNumVga () virtual
Returns the number of VGA devices.
Implements Machine.
Definition at line 205 of file Beagle.cc.
SchedulerTimer * ArmBeagle::getSchedulerTimer () virtual
Returns the SchedulerTimer device.
Implements Machine.
Definition at line 214 of file Beagle.cc.
Serial * ArmBeagle::getSerial (size_t n) virtual
Returns the n'th Serial device.
Implements Machine.
Definition at line 193 of file Beagle.cc.
Timer * ArmBeagle::getTimer () virtual
Returns the n'th Timer device.
Implements Machine.
Definition at line 218 of file Beagle.cc.
Vga * ArmBeagle::getVga (size_t n) virtual
Returns the n'th VGA device.
Implements Machine.
Definition at line 201 of file Beagle.cc.
void ArmBeagle::initialise () virtual
Initialises the machine.
Implements Machine.
Definition at line 158 of file Beagle.cc.
void ArmBeagle::initialiseDeviceTree () virtual
Initialises the machine's base device tree, if one exists, to prefill the tree with those devices that are not otherwise able to be detected via some sort of bus support.
Reimplemented from Machine.
Definition at line 38 of file Beagle.cc.
References Device::addChild(), Device::addresses(), Device::addToRoot(), Device::setInterruptNumber(), Device::setParent(), Device::setPciIdentifiers(), and Device::setSpecificType().
Referenced by setKeyboard().
virtual void ArmBeagle::setKeyboard (Keyboard * kb) inline virtual
Sets the keyboard device.
Implements Machine.
Definition at line 50 of file Beagle.h.
References ArmBeagle(), initialiseDeviceTree(), and ~ArmBeagle().
The documentation for this class was generated from the following files:
Beagle.h
Beagle.cc