The Pedigree Project: Arm926EDisassembler Class Reference
Arm926EDisassembler Class Reference
#include <Disassembler.h>
Public Member Functions
void setLocation (uintptr_t nLocation)
uintptr_t getLocation ()
void setMode (size_t nMode)
void disassemble (LargeStaticString &text)
Public Member Functions inherited from DisassemblerBase
virtual ~DisassemblerBase ()
Private Member Functions
void disassembleSpecial (uint32_t nInstruction, LargeStaticString &text)
void disassembleRegImm (uint32_t nInstruction, LargeStaticString &text)
void disassembleOpcode (uint32_t nInstruction, LargeStaticString &text)
Private Attributes
uintptr_t m_nLocation
Detailed Description
A disassembler for ARM926E processors.
Definition at line 28 of file kernel/core/processor/arm_common/Disassembler.h.
Member Function Documentation
void Arm926EDisassembler::disassemble (LargeStaticString & text) virtual
Disassembles one instruction and populates the given StaticString with a textual representation.
Implements DisassemblerBase.
Definition at line 126 of file arm_common/Disassembler.cc.
Referenced by DisassembleCommand::execute(), and TraceCommand::execute().
uintptr_t Arm926EDisassembler::getLocation () virtual
Gets the location of the next instruction to be disassembled.
Implements DisassemblerBase.
Definition at line 117 of file arm_common/Disassembler.cc.
Referenced by DisassembleCommand::execute(), and TraceCommand::execute().
void Arm926EDisassembler::setLocation (uintptr_t nLocation) virtual
Sets the location of the next instruction to be disassembled.
Implements DisassemblerBase.
Definition at line 112 of file arm_common/Disassembler.cc.
Referenced by DisassembleCommand::execute(), and TraceCommand::execute().
void Arm926EDisassembler::setMode (size_t nMode) virtual
Sets the mode of disassembly - 16-bit, 32-bit or 64-bit If a disassembler doesn't support a requested mode, it should return without changing anything.
Parameters
nMode Mode - 16, 32 or 64.
Implements DisassemblerBase.
Definition at line 122 of file arm_common/Disassembler.cc.
Referenced by DisassembleCommand::execute(), and TraceCommand::execute().
Member Data Documentation
uintptr_t Arm926EDisassembler::m_nLocation private
Current disassembling location in memory.
Definition at line 62 of file kernel/core/processor/arm_common/Disassembler.h.
Referenced by MipsDisassembler::disassemble(), MipsDisassembler::getLocation(), and MipsDisassembler::setLocation().
The documentation for this class was generated from the following files:
kernel/core/processor/arm_common/Disassembler.h
arm_common/Disassembler.cc