The Pedigree Project: HostedInterruptManager Class Reference
HostedInterruptManager Class Reference
Kernelprocessorhosted
#include <InterruptManager.h>
Public Member Functions
virtual bool registerInterruptHandler (size_t nInterruptNumber, InterruptHandler *pHandler)
virtual bool registerInterruptHandlerDebugger (size_t nInterruptNumber, InterruptHandler *pHandler)
virtual size_t getBreakpointInterruptNumber () PURE
virtual size_t getDebugInterruptNumber () PURE
void signalShim (int which, void *siginfo, void *meta)
Static Public Member Functions
static HostedInterruptManager & instance ()
static void initialiseProcessor () INITIALISATION_ONLY
Static Public Member Functions inherited from InterruptManager
static InterruptManager & instance ()
Private Member Functions
void setInterruptGate (size_t nInterruptNumber, uintptr_t interruptHandler) INITIALISATION_ONLY
void setIst (size_t nInterruptNumber, size_t ist)
HostedInterruptManager () INITIALISATION_ONLY
HostedInterruptManager (const HostedInterruptManager &)
HostedInterruptManager & operator= (const HostedInterruptManager &)
virtual ~HostedInterruptManager ()
Static Private Member Functions
static void interrupt (InterruptState &interruptState)
Private Attributes
Spinlock m_Lock
InterruptHandler * m_pHandler [MAX_SIGNAL]
InterruptHandler * m_pDbgHandler [MAX_SIGNAL]
Static Private Attributes
static HostedInterruptManager m_Instance
Additional Inherited Members
Protected Member Functions inherited from InterruptManager
InterruptManager ()
virtual ~InterruptManager ()
Detailed Description
The interrupt manager on hosted systems
Definition at line 34 of file kernel/core/processor/hosted/InterruptManager.h.
Constructor & Destructor Documentation
HostedInterruptManager::HostedInterruptManager () private
The constructor
Definition at line 240 of file hosted/InterruptManager.cc.
References m_pDbgHandler, and m_pHandler.
Referenced by instance().
HostedInterruptManager::HostedInterruptManager (const HostedInterruptManager &) private
Copy constructor
Note
NOT implemented
HostedInterruptManager::~HostedInterruptManager () private virtual
The destructor
Definition at line 252 of file hosted/InterruptManager.cc.
Referenced by instance().
Member Function Documentation
size_t HostedInterruptManager::getBreakpointInterruptNumber () virtual
Get the interrupt number of the breakpoint exception
Returns
the interrupt number of the breakpoint exception
Implements InterruptManager.
Definition at line 95 of file hosted/InterruptManager.cc.
Referenced by instance().
size_t HostedInterruptManager::getDebugInterruptNumber () virtual
Get the interrupt number of the debug exception
Returns
the interrupt number of the debug exception
Implements InterruptManager.
Definition at line 99 of file hosted/InterruptManager.cc.
Referenced by instance().
void HostedInterruptManager::initialiseProcessor () static
Initialises this processors IDTR
Note
This should only be called from Processor::initialise1() and Multiprocessor::applicationProcessorStartup()
Definition at line 225 of file hosted/InterruptManager.cc.
Referenced by Processor::initialisationDone(), and instance().
static HostedInterruptManager& HostedInterruptManager::instance () inline static
Get the HostedInterruptManager class instance
Returns
instance of the HostedInterruptManager class
Definition at line 39 of file kernel/core/processor/hosted/InterruptManager.h.
References getBreakpointInterruptNumber(), getDebugInterruptNumber(), HostedInterruptManager(), INITIALISATION_ONLY, initialiseProcessor(), interrupt(), m_Instance, operator=(), PURE, registerInterruptHandler(), registerInterruptHandlerDebugger(), setInterruptGate(), setIst(), signalShim(), and ~HostedInterruptManager().
Referenced by interrupt().
void HostedInterruptManager::interrupt (InterruptState & interruptState) static private
Called when an interrupt was triggered
Parameters
[in] interruptState reference to the usermode/kernel state before the interrupt
Todo:
Provide a better entry point for system shutdown.
Definition at line 106 of file hosted/InterruptManager.cc.
References Thread::getParent(), Processor::information(), instance(), Debugger::instance(), InterruptHandler::interrupt(), LIKELY, panic(), Processor::reset(), signalShim(), Debugger::start(), Subsystem::threadException(), and UNLIKELY.
Referenced by instance().
HostedInterruptManager& HostedInterruptManager::operator= (const HostedInterruptManager &) private
Assignment operator
Note
NOT implemented
Referenced by instance().
bool HostedInterruptManager::registerInterruptHandler (size_t nInterruptNumber, InterruptHandler * pHandler) virtual
Register an interrupt handler
Parameters
[in] nInterruptNumber the interrupt's number
[in] pHandler the interrupt handler
Returns
true, if successfully registered, false otherwise
Implements InterruptManager.
Definition at line 54 of file hosted/InterruptManager.cc.
References UNLIKELY.
Referenced by instance().
bool HostedInterruptManager::registerInterruptHandlerDebugger (size_t nInterruptNumber, InterruptHandler * pHandler) virtual
Register an interrupt handler (for the kernel debugger)
Parameters
[in] nInterruptNumber the interrupt's number
[in] pHandler the interrupt handler
Returns
true, if successfully registered, false otherwise
Implements InterruptManager.
Definition at line 76 of file hosted/InterruptManager.cc.
References UNLIKELY.
Referenced by instance().
void HostedInterruptManager::setInterruptGate (size_t nInterruptNumber, uintptr_t interruptHandler) private
Sets up an interrupt gate
Parameters
[in] interruptNumber the interrupt number
[in] interruptHandler address of the assembler interrupt handler stub
Note
This function is defined in kernel/processor/ARCH/interrupt.cc
Referenced by instance().
void HostedInterruptManager::setIst (size_t nInterruptNumber, size_t ist) private
Sets the IST field for a given interrupt gate
Parameters
[in] interruptNumber the interrupt number
[in] ist IST index to use
Referenced by instance().
void HostedInterruptManager::signalShim (int which, void * siginfo, void * meta)
Signal handling shim for InterruptState protected access.
Definition at line 201 of file hosted/InterruptManager.cc.
References Processor::getInterrupts().
Referenced by instance(), and interrupt().
Member Data Documentation
HostedInterruptManager HostedInterruptManager::m_Instance static private
The instance of the interrupt manager
Definition at line 101 of file kernel/core/processor/hosted/InterruptManager.h.
Referenced by instance().
Spinlock HostedInterruptManager::m_Lock private
Spinlock protecting the member variables
Definition at line 91 of file kernel/core/processor/hosted/InterruptManager.h.
InterruptHandler* HostedInterruptManager::m_pDbgHandler[MAX_SIGNAL] private
The debugger interrupt handlers
Definition at line 97 of file kernel/core/processor/hosted/InterruptManager.h.
Referenced by HostedInterruptManager().
InterruptHandler* HostedInterruptManager::m_pHandler[MAX_SIGNAL] private
The normal interrupt handlers
Definition at line 94 of file kernel/core/processor/hosted/InterruptManager.h.
Referenced by HostedInterruptManager().
The documentation for this class was generated from the following files:
kernel/core/processor/hosted/InterruptManager.h
hosted/InterruptManager.cc