The Pedigree Project: LogViewer Class Reference
LogViewer Class Reference
kernel » debugger » commands
#include <LogViewer.h>
Public Member Functions
LogViewer ()
~LogViewer ()
void autocomplete (const HugeStaticString &input, HugeStaticString &output)
bool execute (const HugeStaticString &input, HugeStaticString &output, InterruptState &state, DebuggerIO *screen)
const NormalStaticString getString ()
virtual const char * getLine1 (size_t index, DebuggerIO::Colour &colour, DebuggerIO::Colour &bgColour)
virtual const char * getLine2 (size_t index, size_t &colOffset, DebuggerIO::Colour &colour, DebuggerIO::Colour &bgColour)
virtual size_t getLineCount ()
Public Member Functions inherited from Scrollable
void move (size_t x, size_t y)
void resize (size_t width, size_t height)
void scroll (ssize_t lines)
void scrollTo (size_t absolute)
void refresh (DebuggerIO *pScreen)
void setScrollKeys (char up, char down)
ssize_t getLine ()
void centreOn (size_t line)
size_t height () const
size_t width () const
Additional Inherited Members
Protected Attributes inherited from Scrollable
size_t m_x
size_t m_y
size_t m_width
size_t m_height
ssize_t m_line
char m_ScrollUp
char m_ScrollDown
Detailed Description
Debugger command that allows viewing of the kernel log.
Definition at line 36 of file LogViewer.h.
Constructor & Destructor Documentation
LogViewer::LogViewer ()
Default constructor - zero's stuff.
Definition at line 24 of file LogViewer.cc.
LogViewer::~LogViewer ()
Default destructor - does nothing.
Definition at line 28 of file LogViewer.cc.
Member Function Documentation
void LogViewer::autocomplete (const HugeStaticString & input, HugeStaticString & output) virtual
Return an autocomplete string, given an input string.
Implements DebuggerCommand.
Definition at line 32 of file LogViewer.cc.
bool LogViewer::execute (const HugeStaticString & input, HugeStaticString & output, InterruptState & state, DebuggerIO * screen) virtual
Execute the command with the given screen.
Implements DebuggerCommand.
Definition at line 37 of file LogViewer.cc.
References DebuggerIO::drawHorizontalLine(), DebuggerIO::drawString(), DebuggerIO::enableCli(), DebuggerIO::getChar(), Log::getDynamicEntry(), Log::getDynamicEntryCount(), Log::getStaticEntry(), Log::getStaticEntryCount(), DebuggerIO::getWidth(), Log::instance(), Log::LogEntry::severity, Log::LogEntry::str, and Log::LogEntry::timestamp.
const NormalStaticString LogViewer::getString () inline virtual
Returns the string representation of this command.
Implements DebuggerCommand.
Definition at line 64 of file LogViewer.h.
The documentation for this class was generated from the following files:
LogViewer.h
LogViewer.cc