The Pedigree Project: IsaAtaController Class Reference
IsaAtaController Class Reference
#include <IsaAtaController.h>
Public Member Functions
IsaAtaController (Controller *pDev, int nController=0)
virtual void getName (String &str)
virtual bool sendCommand (size_t nUnit, uintptr_t pCommand, uint8_t nCommandSize, uintptr_t pRespBuffer, uint16_t nRespBytes, bool bWrite)
virtual uint64_t executeRequest (uint64_t p1, uint64_t p2, uint64_t p3, uint64_t p4, uint64_t p5, uint64_t p6, uint64_t p7, uint64_t p8)
virtual bool irq (irq_id_t number, InterruptState &state)
Public Member Functions inherited from AtaController
AtaController (Controller *pDev, int nController=0)
virtual bool compareRequests (const RequestQueue::Request &a, const RequestQueue::Request &b)
Public Member Functions inherited from ScsiController
ScsiController (Controller *pDev)
Public Member Functions inherited from Controller
Controller (Device *pDev)
virtual Type getType ()
virtual void dump (String &str)
Public Member Functions inherited from Device
Device (Device *p)
Device * getParent () const
void setParent (Device *p)
virtual String getSpecificType ()
virtual void setSpecificType (String str)
void setPciPosition (uint32_t bus, uint32_t device, uint32_t func)
void setPciIdentifiers (uint8_t classCode, uint8_t subclassCode, uint16_t vendorId, uint16_t deviceId, uint8_t progIf)
void setPciConfigHeader (const PciBus::ConfigSpace &space)
PciBus::ConfigSpace getPciConfigHeader () const
uint8_t getPciClassCode ()
uint8_t getPciSubclassCode ()
uint16_t getPciVendorId ()
uint16_t getPciDeviceId ()
uint8_t getPciProgInterface ()
uint32_t getPciBusPosition ()
uint32_t getPciDevicePosition ()
uint32_t getPciFunctionNumber ()
virtual Vector< Address * > & addresses ()
virtual uintptr_t getInterruptNumber ()
virtual void setInterruptNumber (uintptr_t n)
void addChild (Device *pDevice)
Device * getChild (size_t n)
size_t getNumChildren ()
void removeChild (size_t n)
void removeChild (Device *d)
void replaceChild (Device *src, Device *dest)
Public Member Functions inherited from RequestQueue
RequestQueue (const String &name)
virtual void initialise ()
virtual void destroy ()
MUST_USE_RESULT uint64_t addRequest (size_t priority, uint64_t p1=0, uint64_t p2=0, uint64_t p3=0, uint64_t p4=0, uint64_t p5=0, uint64_t p6=0, uint64_t p7=0, uint64_t p8=0)
MUST_USE_RESULT uint64_t addRequest (size_t priority, ActionOnDuplicate action, uint64_t p1=0, uint64_t p2=0, uint64_t p3=0, uint64_t p4=0, uint64_t p5=0, uint64_t p6=0, uint64_t p7=0, uint64_t p8=0)
uint64_t addAsyncRequest (size_t priority, uint64_t p1=0, uint64_t p2=0, uint64_t p3=0, uint64_t p4=0, uint64_t p5=0, uint64_t p6=0, uint64_t p7=0, uint64_t p8=0)
void halt ()
void resume ()
Private Member Functions
IsaAtaController (const IsaAtaController &)
void operator= (const IsaAtaController &)
Additional Inherited Members
Public Types inherited from Device
enum Type {
Generic, Root, Disk, Bus,
Display, Network, Sound, Console,
Mouse, Controller, UsbController, UsbGeneric,
UsbContainer
}
typedef Device *(* Callback) (Device *)
Public Types inherited from RequestQueue
enum ActionOnDuplicate { Block, NewRequest, ReturnImmediately }
Static Public Member Functions inherited from Device
static void foreach (Callback callback, Device *root=0)
template<class F , class... Args>
static void foreach (pedigree_std::Callable< F > &callback, Device *root, Args...args)
static void addToRoot (Device *device)
static void searchByVendorId (uint16_t vendorId, void(*callback)(Device *), Device *root=0)
static void searchByVendorIdAndDeviceId (uint16_t vendorId, uint16_t deviceId, void(*callback)(Device *), Device *root=0)
static void searchByClass (uint16_t classCode, void(*callback)(Device *), Device *root=0)
static void searchByClassAndSubclass (uint16_t classCode, uint16_t subclassCode, void(*callback)(Device *), Device *root=0)
static void searchByClassSubclassAndProgInterface (uint16_t classCode, uint16_t subclassCode, uint8_t progInterface, void(*callback)(Device *), Device *root=0)
Public Attributes inherited from AtaController
IoBase * m_pCommandRegs
IoBase * m_pControlRegs
Protected Member Functions inherited from AtaController
virtual size_t getNumUnits ()
Protected Member Functions inherited from ScsiController
void searchDisks ()
Protected Member Functions inherited from Device
NOT_COPYABLE_OR_ASSIGNABLE (Device)
Protected Member Functions inherited from RequestQueue
RequestQueue (const RequestQueue &)
void operator= (const RequestQueue &)
bool isRequestValid (const Request *r)
int work ()
Request * getNextRequest ()
Protected Member Functions inherited from IrqHandler
virtual ~IrqHandler ()
Static Protected Member Functions inherited from Device
static Device & root ()
Static Protected Member Functions inherited from RequestQueue
static int trampoline (void *p)
static int doAsync (void *p)
Protected Attributes inherited from AtaController
int m_nController
Protected Attributes inherited from Device
Vector< Address * > m_Addresses
Vector< Device * > m_Children
Device * m_pParent
uintptr_t m_InterruptNumber
String m_SpecificType
PciBus::ConfigSpace m_ConfigHeader
uint8_t m_ClassCode
uint8_t m_SubclassCode
uint16_t m_VendorId
uint16_t m_DeviceId
uint8_t m_ProgInterface
uint32_t m_PciBusPos
uint32_t m_PciDevicePos
uint32_t m_PciFunctionNum
Protected Attributes inherited from RequestQueue
Request * m_pRequestQueue [REQUEST_QUEUE_NUM_PRIORITIES]
volatile bool m_Stop
Mutex m_RequestQueueMutex
ConditionVariable m_RequestQueueCondition
ConditionVariable m_AsyncRequestQueueCondition
Thread * m_pThread
bool m_Halted
Mutex m_HaltAcknowledged
RequestQueueOverrunChecker m_OverrunChecker
size_t m_nMaxAsyncRequests
size_t m_nAsyncRequests
size_t m_nTotalRequests
String m_Name
Static Protected Attributes inherited from Device
static Device m_Root
static Mutex m_TreeLock
Detailed Description
The controller for up to two AtaDisks. This uses a background thread and a request queue.
Definition at line 34 of file IsaAtaController.h.
Member Function Documentation
uint64_t IsaAtaController::executeRequest (uint64_t p1, uint64_t p2, uint64_t p3, uint64_t p4, uint64_t p5, uint64_t p6, uint64_t p7, uint64_t p8) virtual
Callback - classes are expected to inherit and override this function. It's called when a request needs to be executed (by the worker thread).
Reimplemented from ScsiController.
Definition at line 152 of file IsaAtaController.cc.
References AtaDisk::doRead(), and AtaDisk::doWrite().
Referenced by getName().
virtual void IsaAtaController::getName (String & str) inline virtual
Stores the device's name in str.
Implements AtaController.
Definition at line 42 of file IsaAtaController.h.
References executeRequest(), and irq().
bool IsaAtaController::irq (irq_id_t number, InterruptState & state) virtual
Called when the handler is registered with the irq manager and the irq occurred
Note
If this function returns false you have to call IrqManager::acknowledgeIrq() when you removed the interrupt reason.
Parameters
[in] number the irq number
Returns
should return true, if the interrupt reason was removed, or false otherwise
Reimplemented from AtaController.
Definition at line 165 of file IsaAtaController.cc.
References AtaDisk::irqReceived().
Referenced by getName().
The documentation for this class was generated from the following files:
IsaAtaController.h
IsaAtaController.cc