The Pedigree Project: Ext2Symlink Class Reference
Ext2Symlink Class Reference
#include <Ext2Symlink.h>
Public Member Functions
Ext2Symlink (const String &name, uintptr_t inode_num, Inode *inode, class Ext2Filesystem *pFs, File *pParent=0)
virtual ~Ext2Symlink ()
virtual uint64_t readBytewise (uint64_t location, uint64_t size, uintptr_t buffer, bool canBlock)
virtual uint64_t writeBytewise (uint64_t location, uint64_t size, uintptr_t buffer, bool canBlock)
void truncate ()
void fileAttributeChanged ()
Public Member Functions inherited from Symlink
Symlink ()
Symlink (const Symlink &file)
Symlink (const String &name, Time::Timestamp accessedTime, Time::Timestamp modifiedTime, Time::Timestamp creationTime, uintptr_t inode, class Filesystem *pFs, size_t size, File *pParent)
virtual ~Symlink ()
virtual bool isSymlink ()
int followLink (char *pBuffer, size_t bufLen)
File * followLink ()
Public Member Functions inherited from File
File ()
File (const String &name, Time::Timestamp accessedTime, Time::Timestamp modifiedTime, Time::Timestamp creationTime, uintptr_t inode, class Filesystem *pFs, size_t size, File *pParent)
virtual ~File ()
virtual uint64_t read (uint64_t location, uint64_t size, uintptr_t buffer, bool bCanBlock=true) final
virtual uint64_t write (uint64_t location, uint64_t size, uintptr_t buffer, bool bCanBlock=true) final
virtual physical_uintptr_t getPhysicalPage (size_t offset)
virtual void returnPhysicalPage (size_t offset)
virtual void sync ()
virtual void sync (size_t offset, bool async)
Time::Timestamp getCreationTime ()
void setCreationTime (Time::Timestamp t)
Time::Timestamp getAccessedTime ()
void setAccessedTime (Time::Timestamp t)
Time::Timestamp getModifiedTime ()
void setModifiedTime (Time::Timestamp t)
String getName () const
void getName (String &s) const
virtual String getFullPath (bool bWithLabel=true)
size_t getSize ()
void setSize (size_t sz)
virtual bool isDirectory ()
virtual bool isPipe () const
virtual bool isFifo () const
virtual bool isSocket () const
uintptr_t getInode () const
virtual void setInode (uintptr_t inode)
Filesystem * getFilesystem () const
void setFilesystem (Filesystem *pFs)
virtual void increaseRefCount (bool bIsWriter)
virtual void decreaseRefCount (bool bIsWriter)
void setPermissions (uint32_t perms)
uint32_t getPermissions () const
void setUid (size_t uid)
size_t getUid () const
void setGid (size_t gid)
size_t getGid () const
File * getParent () const
virtual int select (bool bWriting=false, int timeout=0)
void monitor (Thread *pThread, Event *pEvent)
void cullMonitorTargets (Thread *pThread)
virtual bool supports (const size_t command) const
virtual int command (const size_t command, void *buffer)
virtual size_t getBlockSize () const
void enableDirect ()
void disableDirect ()
virtual void preallocate (size_t expectedSize, bool zero=true)
virtual File * open ()
Public Member Functions inherited from Ext2Node
Ext2Node (uintptr_t inode_num, Inode *pInode, class Ext2Filesystem *pFs)
virtual ~Ext2Node ()
Inode * getInode ()
uint32_t getInodeNumber ()
void fileAttributeChanged (size_t size, size_t atime, size_t mtime, size_t ctime)
void updateMetadata (uint16_t uid, uint16_t gid, uint32_t perms)
void wipe ()
void extend (size_t newSize)
void extend (size_t newSize, uint64_t location, uint64_t size)
uintptr_t readBlock (uint64_t location)
void writeBlock (uint64_t location)
void trackBlock (uint32_t block)
void pinBlock (uint64_t location)
void unpinBlock (uint64_t location)
void sync (size_t offset, bool async)
Private Member Functions
Ext2Symlink (const Ext2Symlink &file)
Ext2Symlink & operator= (const Ext2Symlink &)
Additional Inherited Members
Static Public Member Functions inherited from Symlink
static Symlink * fromFile (File *pF)
Protected Member Functions inherited from Symlink
void initialise (bool bForce=false)
virtual bool isBytewise () const
Protected Member Functions inherited from File
virtual uintptr_t readBlock (uint64_t location)
virtual void writeBlock (uint64_t location, uintptr_t addr)
virtual void extend (size_t newSize)
virtual void extend (size_t newSize, uint64_t location, uint64_t size)
void dataChanged ()
void getFilesystemLabel (HugeStaticString &s)
virtual void pinBlock (uint64_t location)
virtual void unpinBlock (uint64_t location)
void evict (uint64_t location)
void setPermissionsOnly (uint32_t perms)
void setUidOnly (size_t uid)
void setGidOnly (size_t gid)
Protected Member Functions inherited from Ext2Node
bool ensureLargeEnough (size_t size, uint64_t location, uint64_t opsize, bool onlyBlocks=false, bool nozeroblocks=false)
bool addBlock (uint32_t blockValue)
bool ensureBlockLoaded (size_t nBlock)
bool getBlockNumber (size_t nBlock)
bool getBlockNumberIndirect (uint32_t inode_block, size_t nBlocks, size_t nBlock)
bool getBlockNumberBiindirect (uint32_t inode_block, size_t nBlocks, size_t nBlock)
bool getBlockNumberTriindirect (uint32_t inode_block, size_t nBlocks, size_t nBlock)
bool setBlockNumber (size_t blockNum, uint32_t blockValue)
uint32_t modeToPermissions (uint32_t mode) const
uint32_t permissionsToMode (uint32_t permissions) const
Static Protected Member Functions inherited from File
static void writeCallback (CacheConstants::CallbackCause cause, uintptr_t loc, uintptr_t page, void *meta)
Protected Attributes inherited from Symlink
File * m_pCachedSymlink
String m_sTarget
Protected Attributes inherited from File
String m_Name
Time::Timestamp m_AccessedTime
Time::Timestamp m_ModifiedTime
Time::Timestamp m_CreationTime
uintptr_t m_Inode
class Filesystem * m_pFilesystem
size_t m_Size
File * m_pParent
size_t m_nWriters
size_t m_nReaders
size_t m_Uid
size_t m_Gid
uint32_t m_Permissions
HashTable< DataCacheKey, uintptr_t > m_DataCache
bool m_bDirect
Cache m_FillCache
Mutex m_Lock
List< MonitorTarget * > m_MonitorTargets
Protected Attributes inherited from Ext2Node
Inode * m_pInode
uint32_t m_InodeNumber
class Ext2Filesystem * m_pExt2Fs
Vector< uint32_t > m_Blocks
uint32_t m_nMetadataBlocks
size_t m_nSize
Detailed Description
A File is a file, a directory or a symlink.
Definition at line 32 of file Ext2Symlink.h.
Constructor & Destructor Documentation
Ext2Symlink::Ext2Symlink (const Ext2Symlink & file) private
Copy constructors are hidden - unused!
Ext2Symlink::Ext2Symlink (const String & name, uintptr_t inode_num, Inode * inode, class Ext2Filesystem * pFs, File * pParent = 0)
Constructor, should be called only by a Filesystem.
Definition at line 30 of file Ext2Symlink.cc.
References File::setGidOnly(), File::setPermissionsOnly(), and File::setUidOnly().
Ext2Symlink::~Ext2Symlink () virtual
Destructor
Definition at line 47 of file Ext2Symlink.cc.
Member Function Documentation
void Ext2Symlink::fileAttributeChanged () virtual
Updates inode attributes.
Reimplemented from File.
Definition at line 111 of file Ext2Symlink.cc.
References Ext2Node::updateMetadata().
uint64_t Ext2Symlink::readBytewise (uint64_t location, uint64_t size, uintptr_t buffer, bool bCanBlock) virtual
Reads bytes from the file, if isBytewise() == true.
Reimplemented from File.
Definition at line 51 of file Ext2Symlink.cc.
References Ext2Filesystem::m_BlockSize, and WARNING.
void Ext2Symlink::truncate () virtual
Delete all data from the file.
Reimplemented from File.
Definition at line 105 of file Ext2Symlink.cc.
References Ext2Node::wipe().
uint64_t Ext2Symlink::writeBytewise (uint64_t location, uint64_t size, uintptr_t buffer, bool bCanBlock) virtual
Writes bytes to the file, if isBytewise() == true.
Reimplemented from File.
Definition at line 84 of file Ext2Symlink.cc.
References Ext2Filesystem::m_BlockSize, and WARNING.
The documentation for this class was generated from the following files:
Ext2Symlink.h
Ext2Symlink.cc