The Pedigree Project: ServiceFeatures Class Reference
ServiceFeatures Class Reference
#include <ServiceFeatures.h>
Public Types
enum Type { write = 0, read = 1, touch = 2, probe = 4 }
Public Member Functions
virtual bool provides (Type service)
virtual void add (Type s)
virtual void remove (Type s)
Private Attributes
uint32_t m_OpEnum
Detailed Description
Service Operation Enumeration
This class provides a central interface for finding out the features a Service exposes to the system.
Definition at line 31 of file ServiceFeatures.h.
Member Enumeration Documentation
enum ServiceFeatures::Type
Enumerator
write
Write: send data to the Service. Open to interpretation (OTI)
read
Read: obtain data form the service. OTI
touch
Touch: inform of new state, pass relevant object data
probe
Probe: what's happening? OTI
Definition at line 34 of file ServiceFeatures.h.
Member Function Documentation
void ServiceFeatures::add (Type s) virtual
Used by the Service itself when installing
Definition at line 34 of file ServiceFeatures.cc.
Referenced by PartitionService::serve().
bool ServiceFeatures::provides (Type service) virtual
Does the operation provide a specific service?
Definition at line 29 of file ServiceFeatures.cc.
Referenced by StreamingScreenLogger::callback(), RtcFile::command(), CdiDisk::initialise(), ScsiDisk::initialise(), panic(), PartitionService::serve(), and Debugger::start().
void ServiceFeatures::remove (Type s) virtual
Used by the Service itself to dynamically change offered features
Definition at line 40 of file ServiceFeatures.cc.
The documentation for this class was generated from the following files:
ServiceFeatures.h
ServiceFeatures.cc