The Pedigree Project: ARMV7StackFrame Class Reference
ARMV7StackFrame Class Reference
KernelprocessorARMV7
#include <StackFrame.h>
Public Member Functions
ARMV7StackFrame (const ProcessorState &State, uintptr_t basePointer, LargeStaticString mangledSymbol)
~ARMV7StackFrame ()
Public Member Functions inherited from StackFrameBase
void prettyPrint (HugeStaticString &buf)
StackFrameBase (const ProcessorState &State, uintptr_t basePointer, LargeStaticString mangledSymbol)
virtual ~StackFrameBase ()
Static Public Member Functions
static void construct (ProcessorState &state, uintptr_t returnAddress, unsigned int nParams,...)
Static Public Member Functions inherited from StackFrameBase
static void construct (ProcessorState &state, uintptr_t returnAddress, unsigned int nParams,...)
Private Member Functions
virtual uintptr_t getParameter (size_t n)
Additional Inherited Members
Protected Attributes inherited from StackFrameBase
symbol_t m_Symbol
const ProcessorState & m_State
uintptr_t m_BasePointer
Detailed Description
mips32 StackFrame
Definition at line 31 of file armv7/StackFrame.h.
Constructor & Destructor Documentation
ARMV7StackFrame::ARMV7StackFrame (const ProcessorState & State, uintptr_t basePointer, LargeStaticString mangledSymbol) inline
Creates a stack frame based on the given processor state and also the given symbol name (mangled).
Definition at line 36 of file armv7/StackFrame.h.
ARMV7StackFrame::~ARMV7StackFrame () inline
The destructor does nothing
Definition at line 43 of file armv7/StackFrame.h.
References construct(), and getParameter().
Member Function Documentation
void ARMV7StackFrame::construct (ProcessorState & state, uintptr_t returnAddress, unsigned int nParams, ...) static
Construct a stack frame, given a ProcessorState. The stack frame should be constructed to comply with the default ABI for the current architecture - that implies the stack may be changed, so the getStackPointer() member of ProcessorState must be valid.
Parameters
[out] state The state to modify (construct a stack frame in).
returnAddress The return address of the stack frame.
nParams The number of parameters to the stack frame.
... The parameters, each sizeof(uintptr_t).
Definition at line 30 of file armv7/StackFrame.cc.
Referenced by ~ARMV7StackFrame().
uintptr_t ARMV7StackFrame::getParameter (size_t n) private virtual
Returns the n'th 64-bit parameter in the stack frame.
Todo:
Write.
Implements StackFrameBase.
Definition at line 24 of file armv7/StackFrame.cc.
Referenced by ~ARMV7StackFrame().
The documentation for this class was generated from the following files:
armv7/StackFrame.h
armv7/StackFrame.cc