The Pedigree Project: LookupCommand Class Reference
LookupCommand Class Reference
kernel » debugger » commands
#include <LookupCommand.h>
Public Member Functions
LookupCommand ()
~LookupCommand ()
void autocomplete (const HugeStaticString &input, HugeStaticString &output)
bool execute (const HugeStaticString &input, HugeStaticString &output, InterruptState &state, DebuggerIO *screen)
const NormalStaticString getString ()
Detailed Description
Debugger command that allows viewing of the Cpu dump.
Definition at line 34 of file LookupCommand.h.
Constructor & Destructor Documentation
LookupCommand::LookupCommand ()
Default constructor - does nothing.
Definition at line 26 of file LookupCommand.cc.
LookupCommand::~LookupCommand ()
Default destructor - does nothing.
Definition at line 30 of file LookupCommand.cc.
Member Function Documentation
void LookupCommand::autocomplete (const HugeStaticString & input, HugeStaticString & output) virtual
Return an autocomplete string, given an input string.
Implements DebuggerCommand.
Definition at line 34 of file LookupCommand.cc.
bool LookupCommand::execute (const HugeStaticString & input, HugeStaticString & output, InterruptState & state, DebuggerIO * screen) virtual
Execute the command with the given screen.
Implements DebuggerCommand.
Definition at line 39 of file LookupCommand.cc.
References KernelElf::globalLookupSymbol(), KernelElf::instance(), and Elf::lookupSymbol().
const NormalStaticString LookupCommand::getString () inline virtual
Returns the string representation of this command.
Implements DebuggerCommand.
Definition at line 62 of file LookupCommand.h.
The documentation for this class was generated from the following files:
LookupCommand.h
LookupCommand.cc