The Pedigree Project: HostedMachine Class Reference
HostedMachine Class Reference
#include <Machine.h>
Public Member Functions
virtual void initialise () INITIALISATION_ONLY
virtual void initialiseDeviceTree ()
virtual Serial * getSerial (size_t n)
virtual size_t getNumSerial ()
virtual Vga * getVga (size_t n)
virtual size_t getNumVga ()
virtual IrqManager * getIrqManager ()
virtual SchedulerTimer * getSchedulerTimer ()
virtual Timer * getTimer ()
virtual Keyboard * getKeyboard ()
virtual void setKeyboard (Keyboard *kb)
virtual void stopAllOtherProcessors ()
Public Member Functions inherited from Machine
virtual void initialise2 ()
Called after debugger startup.
virtual void initialise3 ()
Called after processor startup - for thread creation etc.
virtual void deinitialise ()
bool isInitialised ()
Static Public Member Functions
static HostedMachine & instance ()
Static Public Member Functions inherited from Machine
static Machine & instance ()
Private Member Functions
HostedMachine () INITIALISATION_ONLY
HostedMachine (const HostedMachine &)
HostedMachine & operator= (const HostedMachine &)
virtual ~HostedMachine ()
Private Attributes
HostedSerial m_Serial [2]
HostedVga m_Vga
Keyboard * m_Keyboard
Static Private Attributes
static HostedMachine m_Instance
Additional Inherited Members
Protected Attributes inherited from Machine
bool m_bInitialised
Detailed Description
Concretion of the abstract Machine class for hosted systems
Definition at line 34 of file kernel/machine/hosted/Machine.h.
Constructor & Destructor Documentation
HostedMachine::HostedMachine () private
Default constructor, does nothing.
Definition at line 104 of file hosted/Machine.cc.
HostedMachine::~HostedMachine () private virtual
Virtual destructor, does nothing.
Definition at line 108 of file hosted/Machine.cc.
Member Function Documentation
Keyboard * HostedMachine::getKeyboard () virtual
Returns the keyboard device.
Implements Machine.
Definition at line 89 of file hosted/Machine.cc.
size_t HostedMachine::getNumSerial () virtual
Returns the number of Serial device.
Implements Machine.
Definition at line 59 of file hosted/Machine.cc.
size_t HostedMachine::getNumVga () virtual
Returns the number of VGA devices.
Implements Machine.
Definition at line 69 of file hosted/Machine.cc.
References HostedIrqManager::instance().
SchedulerTimer * HostedMachine::getSchedulerTimer () virtual
Returns the SchedulerTimer device.
Implements Machine.
Definition at line 79 of file hosted/Machine.cc.
References HostedSchedulerTimer::instance().
Serial * HostedMachine::getSerial (size_t n) virtual
Returns the n'th Serial device.
Implements Machine.
Definition at line 54 of file hosted/Machine.cc.
Timer * HostedMachine::getTimer () virtual
Returns the n'th Timer device.
Implements Machine.
Definition at line 84 of file hosted/Machine.cc.
Vga * HostedMachine::getVga (size_t n) virtual
Returns the n'th VGA device.
Implements Machine.
Definition at line 64 of file hosted/Machine.cc.
void HostedMachine::initialise () virtual
Initialises the machine.
Implements Machine.
Definition at line 37 of file hosted/Machine.cc.
References HostedSchedulerTimer::initialise(), HostedIrqManager::initialise(), HostedTimer::initialise(), HostedIrqManager::instance(), and HostedSchedulerTimer::instance().
void HostedMachine::initialiseDeviceTree () virtual
Initialises the machine's base device tree, if one exists, to prefill the tree with those devices that are not otherwise able to be detected via some sort of bus support.
Reimplemented from Machine.
Definition at line 50 of file hosted/Machine.cc.
void HostedMachine::setKeyboard (Keyboard * kb) virtual
Sets the keyboard device.
Implements Machine.
Definition at line 94 of file hosted/Machine.cc.
The documentation for this class was generated from the following files:
kernel/machine/hosted/Machine.h
hosted/Machine.cc