The Pedigree Project: RawFsDir Class Reference
RawFsDir Class Reference
Public Member Functions
RawFsDir (String name, class RawFs *pFs, File *pParent)
virtual void cacheDirectoryContents ()
virtual void fileAttributeChanged ()
void addEntry (File *pEntry)
void removeRecursive ()
Public Member Functions inherited from Directory
Directory ()
Directory (const String &name, Time::Timestamp accessedTime, Time::Timestamp modifiedTime, Time::Timestamp creationTime, uintptr_t inode, class Filesystem *pFs, size_t size, File *pParent)
virtual ~Directory ()
virtual bool isDirectory ()
File * getChild (size_t n)
size_t getNumChildren ()
virtual bool isCachePopulated () const
File * lookup (const HashedStringView &s) const
void remove (const HashedStringView &s)
Directory * getReparsePoint () const
Get the reparse point attached to this directory. Reparse points allow locations on the filesystem to redirect lookups to a separate directory. While the reparse point is active, the target directory is used for lookups instead of this one.
void setReparsePoint (Directory *pTarget)
bool addEphemeralFile (File *pFile)
Add an ephemeral file to the directory.
bool empty ()
Public Member Functions inherited from File
File ()
File (const String &name, Time::Timestamp accessedTime, Time::Timestamp modifiedTime, Time::Timestamp creationTime, uintptr_t inode, class Filesystem *pFs, size_t size, File *pParent)
virtual ~File ()
virtual uint64_t read (uint64_t location, uint64_t size, uintptr_t buffer, bool bCanBlock=true) final
virtual uint64_t write (uint64_t location, uint64_t size, uintptr_t buffer, bool bCanBlock=true) final
virtual physical_uintptr_t getPhysicalPage (size_t offset)
virtual void returnPhysicalPage (size_t offset)
virtual void sync ()
virtual void sync (size_t offset, bool async)
Time::Timestamp getCreationTime ()
void setCreationTime (Time::Timestamp t)
Time::Timestamp getAccessedTime ()
void setAccessedTime (Time::Timestamp t)
Time::Timestamp getModifiedTime ()
void setModifiedTime (Time::Timestamp t)
String getName () const
void getName (String &s) const
virtual String getFullPath (bool bWithLabel=true)
virtual void truncate ()
size_t getSize ()
void setSize (size_t sz)
virtual bool isSymlink ()
virtual bool isPipe () const
virtual bool isFifo () const
virtual bool isSocket () const
uintptr_t getInode () const
virtual void setInode (uintptr_t inode)
Filesystem * getFilesystem () const
void setFilesystem (Filesystem *pFs)
virtual void increaseRefCount (bool bIsWriter)
virtual void decreaseRefCount (bool bIsWriter)
void setPermissions (uint32_t perms)
uint32_t getPermissions () const
void setUid (size_t uid)
size_t getUid () const
void setGid (size_t gid)
size_t getGid () const
File * getParent () const
virtual int select (bool bWriting=false, int timeout=0)
void monitor (Thread *pThread, Event *pEvent)
void cullMonitorTargets (Thread *pThread)
virtual bool supports (const size_t command) const
virtual int command (const size_t command, void *buffer)
virtual size_t getBlockSize () const
void enableDirect ()
void disableDirect ()
virtual void preallocate (size_t expectedSize, bool zero=true)
virtual File * open ()
Private Member Functions
RawFsDir (const RawFsDir &file)
RawFsDir & operator= (const RawFsDir &)
Additional Inherited Members
Static Public Member Functions inherited from Directory
static Directory * fromFile (File *pF)
Protected Types inherited from Directory
typedef LazyEvaluate< File, DirectoryEntryMetadata, evaluateEntry, destroyEntry > DirectoryEntry
Protected Member Functions inherited from Directory
virtual const DirectoryEntryCache & getCache ()
void markCachePopulated ()
void addDirectoryEntry (const String &name, File *pTarget)
void addDirectoryEntry (const String &name, DirectoryEntryMetadata &&meta)
void preallocateDirectoryEntries (size_t count)
virtual File * convertToFile (const DirectoryEntryMetadata &meta)
Protected Member Functions inherited from File
virtual uint64_t readBytewise (uint64_t location, uint64_t size, uintptr_t buffer, bool bCanBlock=true)
virtual uint64_t writeBytewise (uint64_t location, uint64_t size, uintptr_t buffer, bool bCanBlock=true)
virtual uintptr_t readBlock (uint64_t location)
virtual void writeBlock (uint64_t location, uintptr_t addr)
virtual void extend (size_t newSize)
virtual void extend (size_t newSize, uint64_t location, uint64_t size)
void dataChanged ()
void getFilesystemLabel (HugeStaticString &s)
virtual void pinBlock (uint64_t location)
virtual void unpinBlock (uint64_t location)
void evict (uint64_t location)
void setPermissionsOnly (uint32_t perms)
void setUidOnly (size_t uid)
void setGidOnly (size_t gid)
Static Protected Member Functions inherited from File
static void writeCallback (CacheConstants::CallbackCause cause, uintptr_t loc, uintptr_t page, void *meta)
Protected Attributes inherited from File
String m_Name
Time::Timestamp m_AccessedTime
Time::Timestamp m_ModifiedTime
Time::Timestamp m_CreationTime
uintptr_t m_Inode
class Filesystem * m_pFilesystem
size_t m_Size
File * m_pParent
size_t m_nWriters
size_t m_nReaders
size_t m_Uid
size_t m_Gid
uint32_t m_Permissions
HashTable< DataCacheKey, uintptr_t > m_DataCache
bool m_bDirect
Cache m_FillCache
Mutex m_Lock
List< MonitorTarget * > m_MonitorTargets
Detailed Description
Definition at line 28 of file RawFsDir.h.
Constructor & Destructor Documentation
RawFsDir::RawFsDir (const RawFsDir & file) private
Copy constructors are hidden - unused!
RawFsDir::RawFsDir (String name, class RawFs * pFs, File * pParent)
Constructor, should only be called by RawFs.
Definition at line 28 of file RawFsDir.cc.
Member Function Documentation
void RawFsDir::addEntry (File * pEntry)
Adds an entry to this directory.
Note
To be called by RawFS only.
Definition at line 40 of file RawFsDir.cc.
References Directory::addDirectoryEntry(), and File::getName().
Referenced by cacheDirectoryContents(), and RawFs::getRoot().
virtual void RawFsDir::cacheDirectoryContents () inline virtual
Reads directory contents into File* cache.
Reimplemented from Directory.
Definition at line 40 of file RawFsDir.h.
References addEntry(), and removeRecursive().
void RawFsDir::removeRecursive ()
Todo:
Leaky.
Todo:
do this
Definition at line 45 of file RawFsDir.cc.
References File::getName(), and NOTICE.
Referenced by cacheDirectoryContents(), and RawFs::getRoot().
The documentation for this class was generated from the following files:
RawFsDir.h
RawFs.cc
RawFsDir.cc