The Pedigree Project: SyscallTracerCommand Class Reference
SyscallTracerCommand Class Reference
Public Member Functions
SyscallTracerCommand ()
void autocomplete (const HugeStaticString &input, HugeStaticString &output)
bool execute (const HugeStaticString &input, HugeStaticString &output, InterruptState &state, DebuggerIO *pScreen)
const NormalStaticString getString ()
virtual const char * getLine1 (size_t index, DebuggerIO::Colour &colour, DebuggerIO::Colour &bgColour)
virtual const char * getLine2 (size_t index, size_t &colOffset, DebuggerIO::Colour &colour, DebuggerIO::Colour &bgColour)
virtual size_t getLineCount ()
Public Member Functions inherited from Scrollable
void move (size_t x, size_t y)
void resize (size_t width, size_t height)
void scroll (ssize_t lines)
void scrollTo (size_t absolute)
void refresh (DebuggerIO *pScreen)
void setScrollKeys (char up, char down)
ssize_t getLine ()
void centreOn (size_t line)
size_t height () const
size_t width () const
Additional Inherited Members
Protected Attributes inherited from Scrollable
size_t m_x
size_t m_y
size_t m_width
size_t m_height
ssize_t m_line
char m_ScrollUp
char m_ScrollDown
Detailed Description
Definition at line 27 of file SyscallTracerCommand.h.
Constructor & Destructor Documentation
SyscallTracerCommand::SyscallTracerCommand ()
Creates a new SyscallTracer object.
Definition at line 22 of file SyscallTracerCommand.cc.
Member Function Documentation
void SyscallTracerCommand::autocomplete (const HugeStaticString & input, HugeStaticString & output) virtual
Return an autocomplete string, given an input string. The string put into *output must not exceed len in length.
Implements DebuggerCommand.
Definition at line 30 of file SyscallTracerCommand.cc.
bool SyscallTracerCommand::execute (const HugeStaticString & input, HugeStaticString & output, InterruptState & state, DebuggerIO * pScreen) virtual
Execute the command with the given screen. The command can take over the screen while executing, but must return it to CLI mode (via enableCLI) before returning.
Returns
True if the debugger should continue accepting commands, false if it should return control to the kernel.
Implements DebuggerCommand.
Definition at line 35 of file SyscallTracerCommand.cc.
References DebuggerIO::drawHorizontalLine(), DebuggerIO::drawString(), DebuggerIO::getChar(), and DebuggerIO::getWidth().
const NormalStaticString SyscallTracerCommand::getString () inline virtual
Returns the string representation of this command.
Implements DebuggerCommand.
Definition at line 55 of file SyscallTracerCommand.h.
The documentation for this class was generated from the following files:
SyscallTracerCommand.h
SyscallTracerCommand.cc