The Pedigree Project: ThreadsCommand Class Reference
ThreadsCommand Class Reference
kernel » debugger » commands
#include <ThreadsCommand.h>
Public Member Functions
ThreadsCommand ()
~ThreadsCommand ()
void autocomplete (const HugeStaticString &input, HugeStaticString &output)
bool execute (const HugeStaticString &input, HugeStaticString &output, InterruptState &state, DebuggerIO *screen)
const NormalStaticString getString ()
void setPointers (Thread **ppThread, InterruptState *pState)
virtual const char * getLine1 (size_t index, DebuggerIO::Colour &colour, DebuggerIO::Colour &bgColour)
virtual const char * getLine2 (size_t index, size_t &colOffset, DebuggerIO::Colour &colour, DebuggerIO::Colour &bgColour)
virtual size_t getLineCount ()
Public Member Functions inherited from Scrollable
void move (size_t x, size_t y)
void resize (size_t width, size_t height)
void scroll (ssize_t lines)
void scrollTo (size_t absolute)
void refresh (DebuggerIO *pScreen)
void setScrollKeys (char up, char down)
ssize_t getLine ()
void centreOn (size_t line)
size_t height () const
size_t width () const
Private Member Functions
bool swapThread (InterruptState &state, DebuggerIO *pScreen)
Private Attributes
size_t m_SelectedLine
size_t m_nLines
Additional Inherited Members
Protected Attributes inherited from Scrollable
size_t m_x
size_t m_y
size_t m_width
size_t m_height
ssize_t m_line
char m_ScrollUp
char m_ScrollDown
Detailed Description
Allows step execution.
Definition at line 40 of file ThreadsCommand.h.
Constructor & Destructor Documentation
ThreadsCommand::ThreadsCommand ()
Default constructor - zero's stuff.
Definition at line 32 of file ThreadsCommand.cc.
ThreadsCommand::~ThreadsCommand ()
Default destructor - does nothing.
Definition at line 37 of file ThreadsCommand.cc.
Member Function Documentation
void ThreadsCommand::autocomplete (const HugeStaticString & input, HugeStaticString & output) virtual
Return an autocomplete string, given an input string.
Implements DebuggerCommand.
Definition at line 41 of file ThreadsCommand.cc.
bool ThreadsCommand::execute (const HugeStaticString & input, HugeStaticString & output, InterruptState & state, DebuggerIO * screen) virtual
Execute the command with the given screen.
Implements DebuggerCommand.
Definition at line 46 of file ThreadsCommand.cc.
References Process::description(), DebuggerIO::drawHorizontalLine(), DebuggerIO::drawString(), DebuggerIO::enableCli(), DebuggerIO::getChar(), Thread::getCpuId(), Thread::getDebugState(), Process::getId(), Thread::getId(), Scheduler::getNumProcesses(), Process::getNumThreads(), Scheduler::getProcess(), Thread::getStatus(), Process::getThread(), DebuggerIO::getWidth(), KernelElf::globalLookupSymbol(), Processor::information(), Scheduler::instance(), and KernelElf::instance().
const NormalStaticString ThreadsCommand::getString () inline virtual
Returns the string representation of this command.
Implements DebuggerCommand.
Definition at line 68 of file ThreadsCommand.h.
void ThreadsCommand::setPointers (Thread ** ppThread, InterruptState * pState) inline
Sets the pointers to use to change the thread the debugger debugs.
Definition at line 74 of file ThreadsCommand.h.
Referenced by Debugger::start().
The documentation for this class was generated from the following files:
ThreadsCommand.h
ThreadsCommand.cc