The Pedigree Project: PedigreeTerminalEmulator Class Reference
PedigreeTerminalEmulator Class Reference
Public Member Functions
virtual bool render (PedigreeGraphics::Rect &rt, PedigreeGraphics::Rect &dirty)
void handleReposition (const PedigreeGraphics::Rect &rt)
size_t getWidth () const
size_t getHeight () const
Public Member Functions inherited from Widget
uint64_t getHandle () const
bool construct (const char *endpoint, const char *title, widgetCallback_t cb, PedigreeGraphics::Rect &dimensions)
bool setTitle (const std::string &newTitle)
bool redraw (PedigreeGraphics::Rect &rt)
bool visibility (bool vis)
void destroy ()
void * getRawFramebuffer ()
int getSocket () const
Private Attributes
size_t m_nWidth
size_t m_nHeight
Additional Inherited Members
Static Public Member Functions inherited from Widget
static void checkForEvents (bool bAsync=false)
Detailed Description
Definition at line 41 of file user/applications/TUI/main.cc.
Member Function Documentation
virtual bool PedigreeTerminalEmulator::render (PedigreeGraphics::Rect & rt, PedigreeGraphics::Rect & dirty) inline virtual
Called to actually render the widget. Would normally be called by the RepaintNeeded handler by application code.
Parameters
rt Area that needs to be rendered.
dirty Object containing a dirty rectangle for redrawing.
Returns
True if the render succeeded, False otherwise.
Implements Widget.
Definition at line 49 of file user/applications/TUI/main.cc.
References Widget::checkForEvents(), Widget::construct(), Widget::getRawFramebuffer(), Tui::initialise(), Tui::keyInput(), Tui::recreateSurfaces(), Tui::resize(), Tui::run(), Tui::setCursorStyle(), and Tui::stop().
The documentation for this class was generated from the following file:
user/applications/TUI/main.cc