The Pedigree Project: HostedProcessorState Class Reference
HostedProcessorState Class Reference
Kernelprocessorhosted
#include <state.h>
Public Member Functions
HostedProcessorState ()
HostedProcessorState (const HostedProcessorState &)
HostedProcessorState (const HostedInterruptState &)
HostedProcessorState (const HostedSyscallState &)
HostedProcessorState & operator= (const HostedProcessorState &)
HostedProcessorState & operator= (const HostedInterruptState &)
HostedProcessorState & operator= (const HostedSyscallState &)
~HostedProcessorState ()
uintptr_t getStackPointer () const
void setStackPointer (uintptr_t stackPointer)
uintptr_t getInstructionPointer () const
void setInstructionPointer (uintptr_t instructionPointer)
uintptr_t getBasePointer () const
void setBasePointer (uintptr_t basePointer)
Public Attributes
uint64_t state
Detailed Description
x64 ProcessorState
Definition at line 209 of file hosted/state.h.
Constructor & Destructor Documentation
HostedProcessorState::HostedProcessorState () inline
Default constructor initializes everything with 0
Definition at line 375 of file hosted/state.h.
HostedProcessorState::HostedProcessorState (const HostedProcessorState & x) inline
Copy-constructor
Definition at line 378 of file hosted/state.h.
HostedProcessorState::HostedProcessorState (const HostedInterruptState & x) inline
Construct a ProcessorState object from an InterruptState object
Parameters
[in] x reference to the InterruptState object
Definition at line 382 of file hosted/state.h.
HostedProcessorState::HostedProcessorState (const HostedSyscallState & x) inline
Construct a ProcessorState object from an SyscallState object
Parameters
[in] x reference to the SyscallState object
Definition at line 386 of file hosted/state.h.
References operator=().
HostedProcessorState::~HostedProcessorState () inline
Destructor does nothing
Definition at line 406 of file hosted/state.h.
Member Function Documentation
uintptr_t HostedProcessorState::getBasePointer () const inline
Get the base-pointer
Returns
the base-pointer
Definition at line 424 of file hosted/state.h.
uintptr_t HostedProcessorState::getInstructionPointer () const inline
Get the instruction-pointer of the next instruction that is executed after the interrupt is processed
Returns
the instruction-pointer
Definition at line 417 of file hosted/state.h.
uintptr_t HostedProcessorState::getStackPointer () const inline
Get the stack-pointer before the interrupt occured
Returns
the stack-pointer before the interrupt
Definition at line 410 of file hosted/state.h.
HostedProcessorState & HostedProcessorState::operator= (const HostedProcessorState & x) inline
Assignment operator
Definition at line 390 of file hosted/state.h.
Referenced by HostedProcessorState(), and operator=().
HostedProcessorState & HostedProcessorState::operator= (const HostedInterruptState & x) inline
Assignment from InterruptState
Parameters
[in] reference to the InterruptState
Definition at line 396 of file hosted/state.h.
References operator=(), and HostedInterruptState::state.
HostedProcessorState & HostedProcessorState::operator= (const HostedSyscallState & x) inline
Assignment from SyscallState
Parameters
[in] reference to the SyscallState
Definition at line 402 of file hosted/state.h.
void HostedProcessorState::setBasePointer (uintptr_t basePointer) inline
Set the base-pointer
Parameters
[in] basePointer the new base-pointer
Definition at line 428 of file hosted/state.h.
void HostedProcessorState::setInstructionPointer (uintptr_t instructionPointer) inline
Set the instruction-pointer
Parameters
[in] instructionPointer the new instruction-pointer
Definition at line 421 of file hosted/state.h.
void HostedProcessorState::setStackPointer (uintptr_t stackPointer) inline
Set the userspace stack-pointer
Parameters
[in] stackPointer the new stack-pointer
Definition at line 414 of file hosted/state.h.
The documentation for this class was generated from the following file:
hosted/state.h