The Pedigree Project: TraceCommand Class Reference
TraceCommand Class Reference
kernel » debugger » commands
#include <TraceCommand.h>
Classes
class Disassembly
class Registers
class Stacktrace
Public Member Functions
TraceCommand ()
~TraceCommand ()
void autocomplete (const HugeStaticString &input, HugeStaticString &output)
void setInterface (int nInterface)
bool execute (const HugeStaticString &input, HugeStaticString &output, InterruptState &state, DebuggerIO *screen)
const NormalStaticString getString ()
int execTrace ()
Private Member Functions
void drawBackground (size_t nCols, size_t nLines, DebuggerIO *pScreen)
Private Attributes
int m_nExec
int m_nInterface
Detailed Description
Allows the tracing of an execution path, single stepping and continuing to breakpoints, while displaying a disassembly, the target CPU state and a stack backtrace.
Definition at line 39 of file TraceCommand.h.
Constructor & Destructor Documentation
TraceCommand::TraceCommand ()
Default constructor - zero's stuff.
Definition at line 28 of file TraceCommand.cc.
TraceCommand::~TraceCommand ()
Default destructor - does nothing.
Definition at line 32 of file TraceCommand.cc.
Member Function Documentation
void TraceCommand::autocomplete (const HugeStaticString & input, HugeStaticString & output) virtual
Return an autocomplete string, given an input string.
Implements DebuggerCommand.
Definition at line 36 of file TraceCommand.cc.
int TraceCommand::execTrace () inline
Returns >=0 if the debugger should immediately call us. Returns the interface index to use.
Definition at line 78 of file TraceCommand.h.
References m_nExec.
Referenced by Debugger::start().
bool TraceCommand::execute (const HugeStaticString & input, HugeStaticString & output, InterruptState & state, DebuggerIO * screen) virtual
Execute the command with the given screen.
Implements DebuggerCommand.
Definition at line 46 of file TraceCommand.cc.
References Arm926EDisassembler::disassemble(), DebuggerIO::drawHorizontalLine(), DebuggerIO::drawString(), DebuggerIO::enableCli(), DebuggerIO::enableRefreshes(), DebuggerIO::getChar(), Arm926EDisassembler::getLocation(), DebuggerIO::getWidth(), KernelElf::globalLookupSymbol(), KernelElf::instance(), m_nExec, Arm926EDisassembler::setLocation(), Arm926EDisassembler::setMode(), and Processor::setSingleStep().
Referenced by Debugger::start().
const NormalStaticString TraceCommand::getString () inline virtual
Returns the string representation of this command.
Implements DebuggerCommand.
Definition at line 69 of file TraceCommand.h.
Member Data Documentation
int TraceCommand::m_nExec private
Should the debugger immediately call our execute function? and what interface should it use?
Definition at line 158 of file TraceCommand.h.
Referenced by execTrace(), and execute().
The documentation for this class was generated from the following files:
TraceCommand.h
TraceCommand.cc