The Pedigree Project: PPC32InterruptManager Class Reference
PPC32InterruptManager Class Reference
KernelprocessorPPC32
#include <InterruptManager.h>
Public Member Functions
virtual bool registerInterruptHandler (size_t interruptNumber, InterruptHandler *handler)
virtual bool registerInterruptHandlerDebugger (size_t interruptNumber, InterruptHandler *handler)
virtual size_t getBreakpointInterruptNumber () PURE
virtual size_t getDebugInterruptNumber () PURE
virtual bool registerSyscallHandler (Service_t Service, SyscallHandler *handler)
virtual uintptr_t syscall (Service_t service, uintptr_t function, uintptr_t p1=0, uintptr_t p2=0, uintptr_t p3=0, uintptr_t p4=0, uintptr_t p5=0)
Static Public Member Functions
static PPC32InterruptManager & instance ()
static void initialiseProcessor ()
Static Public Member Functions inherited from InterruptManager
static InterruptManager & instance ()
Static Public Member Functions inherited from SyscallManager
static EXPORTED_PUBLIC SyscallManager & instance ()
Private Member Functions
PPC32InterruptManager ()
PPC32InterruptManager (const PPC32InterruptManager &)
PPC32InterruptManager & operator= (const PPC32InterruptManager &)
virtual ~PPC32InterruptManager ()
Static Private Member Functions
static void interrupt (InterruptState &interruptState)
Private Attributes
InterruptHandler * m_pHandler [64]
InterruptHandler * m_pDbgHandler [64]
SyscallHandler * m_pSyscallHandler [serviceEnd]
Spinlock m_Lock
Static Private Attributes
static PPC32InterruptManager m_Instance
Additional Inherited Members
Protected Member Functions inherited from InterruptManager
InterruptManager ()
virtual ~InterruptManager ()
Protected Member Functions inherited from SyscallManager
SyscallManager ()
virtual ~SyscallManager ()
Detailed Description
The interrupt handler on mips32 processors
Definition at line 34 of file kernel/core/processor/ppc32/InterruptManager.h.
Constructor & Destructor Documentation
PPC32InterruptManager::PPC32InterruptManager () private
The constructor
Definition at line 256 of file ppc32/InterruptManager.cc.
Referenced by instance().
PPC32InterruptManager::PPC32InterruptManager (const PPC32InterruptManager &) private
Copy constructor
Note
NOT implemented
PPC32InterruptManager::~PPC32InterruptManager () private virtual
The destructor
Definition at line 259 of file ppc32/InterruptManager.cc.
Referenced by instance().
Member Function Documentation
size_t PPC32InterruptManager::getBreakpointInterruptNumber () virtual
Get the interrupt number of the breakpoint exception
Returns
the interrupt number of the breakpoint exception
Implements InterruptManager.
Definition at line 111 of file ppc32/InterruptManager.cc.
Referenced by instance().
size_t PPC32InterruptManager::getDebugInterruptNumber () virtual
Get the interrupt number of the debug exception
Returns
the interrupt number of the debug exception
Implements InterruptManager.
Definition at line 115 of file ppc32/InterruptManager.cc.
Referenced by instance().
void PPC32InterruptManager::initialiseProcessor () static
Initialises this processors IDTR
Note
This should only be called from initialiseProcessor()
Todo:
and some smp/acpi function
Definition at line 155 of file ppc32/InterruptManager.cc.
References OpenFirmware::instance().
Referenced by HashedPageTable::initialise(), and instance().
static PPC32InterruptManager& PPC32InterruptManager::instance () inline static
Get the PPC32InterruptManager class instance
Returns
instance of the PPC32InterruptManager class
Definition at line 39 of file kernel/core/processor/ppc32/InterruptManager.h.
References getBreakpointInterruptNumber(), getDebugInterruptNumber(), initialiseProcessor(), interrupt(), m_Instance, operator=(), PPC32InterruptManager(), PURE, registerInterruptHandler(), registerInterruptHandlerDebugger(), registerSyscallHandler(), syscall(), and ~PPC32InterruptManager().
void PPC32InterruptManager::interrupt (InterruptState & interruptState) static private
Called when an interrupt was triggered
Parameters
[in] interruptState reference to the usermode/kernel state before the interrupt
Definition at line 198 of file ppc32/InterruptManager.cc.
References FATAL, Hex, Debugger::instance(), LIKELY, panic(), and Debugger::start().
Referenced by instance().
PPC32InterruptManager& PPC32InterruptManager::operator= (const PPC32InterruptManager &) private
Assignment operator
Note
NOT implemented
Referenced by instance().
bool PPC32InterruptManager::registerInterruptHandler (size_t nInterruptNumber, InterruptHandler * pHandler) virtual
Register an interrupt handler
Parameters
[in] nInterruptNumber the interrupt's number
[in] pHandler the interrupt handler
Returns
true, if successfully registered, false otherwise
Implements InterruptManager.
Definition at line 75 of file ppc32/InterruptManager.cc.
References UNLIKELY.
Referenced by instance().
bool PPC32InterruptManager::registerInterruptHandlerDebugger (size_t nInterruptNumber, InterruptHandler * pHandler) virtual
Register an interrupt handler (for the kernel debugger)
Parameters
[in] nInterruptNumber the interrupt's number
[in] pHandler the interrupt handler
Returns
true, if successfully registered, false otherwise
Implements InterruptManager.
Definition at line 94 of file ppc32/InterruptManager.cc.
References UNLIKELY.
Referenced by instance().
bool PPC32InterruptManager::registerSyscallHandler (Service_t Service, SyscallHandler * pHandler) virtual
Register a syscall handler
Parameters
[in] Service the service number you want to register
[in] pHandler the interrupt handler
Returns
true, if successfully registered, false otherwise
Implements SyscallManager.
Definition at line 121 of file ppc32/InterruptManager.cc.
References UNLIKELY.
Referenced by instance().
uintptr_t PPC32InterruptManager::syscall (Service_t service, uintptr_t function, uintptr_t p1 = 0, uintptr_t p2 = 0, uintptr_t p3 = 0, uintptr_t p4 = 0, uintptr_t p5 = 0) virtual
Calls a syscall.
Implements SyscallManager.
Definition at line 137 of file ppc32/InterruptManager.cc.
Referenced by instance().
Member Data Documentation
PPC32InterruptManager PPC32InterruptManager::m_Instance static private
The instance of the interrupt manager
Definition at line 95 of file kernel/core/processor/ppc32/InterruptManager.h.
Referenced by instance().
Spinlock PPC32InterruptManager::m_Lock private
Lock
Definition at line 92 of file kernel/core/processor/ppc32/InterruptManager.h.
InterruptHandler* PPC32InterruptManager::m_pDbgHandler[64] private
The debugger interrupt handlers
Definition at line 86 of file kernel/core/processor/ppc32/InterruptManager.h.
SyscallHandler* PPC32InterruptManager::m_pSyscallHandler[serviceEnd] private
The syscall handlers
Definition at line 89 of file kernel/core/processor/ppc32/InterruptManager.h.
The documentation for this class was generated from the following files:
kernel/core/processor/ppc32/InterruptManager.h
ppc32/InterruptManager.cc