The Pedigree Project: MIPSCommonProcessorInformation Class Reference
MIPSCommonProcessorInformation Class Reference
kernel » processor-specifc kernel » mips-common
#include <ProcessorInformation.h>
Public Member Functions
VirtualAddressSpace & getVirtualAddressSpace () const
void setVirtualAddressSpace (VirtualAddressSpace &virtualAddressSpace)
Protected Member Functions
MIPSCommonProcessorInformation (ProcessorId processorId)
virtual ~MIPSCommonProcessorInformation ()
Private Member Functions
MIPSCommonProcessorInformation ()
MIPSCommonProcessorInformation (const MIPSCommonProcessorInformation &)
MIPSCommonProcessorInformation & operator= (const MIPSCommonProcessorInformation &)
Private Attributes
ProcessorId m_ProcessorId
VirtualAddressSpace * m_VirtualAddressSpace
Friends
class Processor
Detailed Description
Common mips processor information structure
Definition at line 30 of file mips_common/ProcessorInformation.h.
Constructor & Destructor Documentation
MIPSCommonProcessorInformation::MIPSCommonProcessorInformation (ProcessorId processorId) inline protected
Construct a MIPSCommonProcessorInformation object
Parameters
[in] processorId Identifier of the processor
Definition at line 51 of file mips_common/ProcessorInformation.h.
virtual MIPSCommonProcessorInformation::~MIPSCommonProcessorInformation () inline protected virtual
The destructor does nothing
Definition at line 57 of file mips_common/ProcessorInformation.h.
References MIPSCommonProcessorInformation(), and operator=().
MIPSCommonProcessorInformation::MIPSCommonProcessorInformation () private
Default constructor
Note
NOT implemented
Referenced by ~MIPSCommonProcessorInformation().
MIPSCommonProcessorInformation::MIPSCommonProcessorInformation (const MIPSCommonProcessorInformation &) private
Copy-constructor
Note
NOT implemented
Member Function Documentation
VirtualAddressSpace& MIPSCommonProcessorInformation::getVirtualAddressSpace () const inline
Get the current processor's VirtualAddressSpace
Returns
reference to the current processor's VirtualAddressSpace
Definition at line 37 of file mips_common/ProcessorInformation.h.
References m_VirtualAddressSpace.
MIPSCommonProcessorInformation& MIPSCommonProcessorInformation::operator= (const MIPSCommonProcessorInformation &) private
Assignment operator
Note
NOT implemented
Referenced by ~MIPSCommonProcessorInformation().
void MIPSCommonProcessorInformation::setVirtualAddressSpace (VirtualAddressSpace & virtualAddressSpace) inline
Set the current processor's VirtualAddressSpace
Parameters
[in] virtualAddressSpace reference to the new VirtualAddressSpace
Definition at line 43 of file mips_common/ProcessorInformation.h.
References m_VirtualAddressSpace.
Member Data Documentation
ProcessorId MIPSCommonProcessorInformation::m_ProcessorId private
Identifier of that processor
Definition at line 74 of file mips_common/ProcessorInformation.h.
VirtualAddressSpace* MIPSCommonProcessorInformation::m_VirtualAddressSpace private
The current VirtualAddressSpace
Definition at line 76 of file mips_common/ProcessorInformation.h.
Referenced by getVirtualAddressSpace(), and setVirtualAddressSpace().
The documentation for this class was generated from the following file:
mips_common/ProcessorInformation.h