The Pedigree Project: CdiNet Class Reference
CdiNet Class Reference
#include <CdiNet.h>
Public Member Functions
CdiNet (struct cdi_net_device *device)
CdiNet (Network *pDev, struct cdi_net_device *device)
virtual void getName (String &str)
virtual bool send (size_t nBytes, uintptr_t buffer)
virtual bool setStationInfo (const StationInfo &info)
virtual const StationInfo & getStationInfo ()
const struct cdi_net_device * getCdiDevice () const
Public Member Functions inherited from Network
Network (Network *pDev)
virtual Type getType ()
virtual void dump (String &str)
virtual bool isConnected ()
virtual void gotPacket ()
virtual void droppedPacket ()
Called when a packet is dropped by the system.
virtual void badPacket ()
Public Member Functions inherited from Device
Device (Device *p)
Device * getParent () const
void setParent (Device *p)
virtual String getSpecificType ()
virtual void setSpecificType (String str)
void setPciPosition (uint32_t bus, uint32_t device, uint32_t func)
void setPciIdentifiers (uint8_t classCode, uint8_t subclassCode, uint16_t vendorId, uint16_t deviceId, uint8_t progIf)
void setPciConfigHeader (const PciBus::ConfigSpace &space)
PciBus::ConfigSpace getPciConfigHeader () const
uint8_t getPciClassCode ()
uint8_t getPciSubclassCode ()
uint16_t getPciVendorId ()
uint16_t getPciDeviceId ()
uint8_t getPciProgInterface ()
uint32_t getPciBusPosition ()
uint32_t getPciDevicePosition ()
uint32_t getPciFunctionNumber ()
virtual Vector< Address * > & addresses ()
virtual uintptr_t getInterruptNumber ()
virtual void setInterruptNumber (uintptr_t n)
void addChild (Device *pDevice)
Device * getChild (size_t n)
size_t getNumChildren ()
void removeChild (size_t n)
void removeChild (Device *d)
void replaceChild (Device *src, Device *dest)
Private Member Functions
CdiNet (const CdiNet &)
const CdiNet & operator= (const CdiNet &)
Private Attributes
struct cdi_net_device * m_Device
Additional Inherited Members
Public Types inherited from Device
enum Type {
Generic, Root, Disk, Bus,
Display, Network, Sound, Console,
Mouse, Controller, UsbController, UsbGeneric,
UsbContainer
}
typedef Device *(* Callback) (Device *)
Static Public Member Functions inherited from Network
static EXPORTED_PUBLIC uint32_t convertToIpv4 (uint8_t a, uint8_t b, uint8_t c, uint8_t d)
static EXPORTED_PUBLIC IpAddress convertToIpv6 (uint8_t a, uint8_t b=0, uint8_t c=0, uint8_t d=0, uint8_t e=0, uint8_t f=0, uint8_t g=0, uint8_t h=0, uint8_t i=0, uint8_t j=0, uint8_t k=0, uint8_t l=0, uint8_t m=0, uint8_t n=0, uint8_t o=0, uint8_t p=0)
static EXPORTED_PUBLIC uint16_t calculateChecksum (uintptr_t buffer, size_t nBytes)
Static Public Member Functions inherited from Device
static void foreach (Callback callback, Device *root=0)
template<class F , class... Args>
static void foreach (pedigree_std::Callable< F > &callback, Device *root, Args...args)
static void addToRoot (Device *device)
static void searchByVendorId (uint16_t vendorId, void(*callback)(Device *), Device *root=0)
static void searchByVendorIdAndDeviceId (uint16_t vendorId, uint16_t deviceId, void(*callback)(Device *), Device *root=0)
static void searchByClass (uint16_t classCode, void(*callback)(Device *), Device *root=0)
static void searchByClassAndSubclass (uint16_t classCode, uint16_t subclassCode, void(*callback)(Device *), Device *root=0)
static void searchByClassSubclassAndProgInterface (uint16_t classCode, uint16_t subclassCode, uint8_t progInterface, void(*callback)(Device *), Device *root=0)
Protected Member Functions inherited from Device
NOT_COPYABLE_OR_ASSIGNABLE (Device)
Static Protected Member Functions inherited from Device
static Device & root ()
Protected Attributes inherited from Network
StationInfo m_StationInfo
Protected Attributes inherited from Device
Vector< Address * > m_Addresses
Vector< Device * > m_Children
Device * m_pParent
uintptr_t m_InterruptNumber
String m_SpecificType
PciBus::ConfigSpace m_ConfigHeader
uint8_t m_ClassCode
uint8_t m_SubclassCode
uint16_t m_VendorId
uint16_t m_DeviceId
uint8_t m_ProgInterface
uint32_t m_PciBusPos
uint32_t m_PciDevicePos
uint32_t m_PciFunctionNum
Static Protected Attributes inherited from Device
static Device m_Root
static Mutex m_TreeLock
Detailed Description
CDI NIC Device
Definition at line 31 of file CdiNet.h.
Constructor & Destructor Documentation
CdiNet::CdiNet (struct cdi_net_device * device)
Todo:
Check endianness - should be fine, but we'll see...
Definition at line 49 of file CdiNet.cc.
References NetworkStack::instance(), NetworkStack::registerDevice(), and Device::setSpecificType().
Referenced by getName(), and setStationInfo().
CdiNet::CdiNet (Network * pDev, struct cdi_net_device * device)
Todo:
Check endianness - should be fine, but we'll see...
Definition at line 37 of file CdiNet.cc.
References NetworkStack::instance(), NetworkStack::registerDevice(), and Device::setSpecificType().
Member Function Documentation
virtual void CdiNet::getName (String & str) inline virtual
Stores the device's name in str.
Reimplemented from Network.
Definition at line 38 of file CdiNet.h.
References CdiNet(), getStationInfo(), send(), and setStationInfo().
const StationInfo & CdiNet::getStationInfo () virtual
Gets station information (such as IP addresses)
Reimplemented from Network.
Definition at line 76 of file CdiNet.cc.
Referenced by getName().
bool CdiNet::send (size_t nBytes, uintptr_t buffer) virtual
Sends a given packet through the device.
Parameters
nBytes The number of bytes to send.
buffer A buffer with the packet to send
Implements Network.
Definition at line 65 of file CdiNet.cc.
Referenced by getName().
bool CdiNet::setStationInfo (const StationInfo & info) virtual
Sets station information (such as IP addresses)
Parameters
info The information to set as the station info
Reimplemented from Network.
Definition at line 81 of file CdiNet.cc.
References Device::addToRoot(), CdiNet(), Dec, EXPORTED_PUBLIC, Device::foreach(), StationInfo::gateway, Hex, NetworkStack::instance(), StationInfo::nDnsServers, Device::Network, NOTICE, and NetworkStack::receive().
Referenced by getName().
The documentation for this class was generated from the following files:
CdiNet.h
CdiNet.cc