The Pedigree Project: NMFaultHandler Class Reference
NMFaultHandler Class Reference
kernel » processor-specifc kernel
#include <NMFaultHandler.h>
Public Member Functions
bool initialise ()
bool initialiseProcessor ()
virtual void interrupt (size_t interruptNumber, InterruptState &state)
void threadTerminated (class Thread *)
Static Public Member Functions
static NMFaultHandler & instance ()
Private Member Functions
NMFaultHandler () INITIALISATION_ONLY
NMFaultHandler (const NMFaultHandler &)
virtual ~InterruptHandler ()
Static Private Attributes
static NMFaultHandler m_Instance
Detailed Description
The x86 Device Not Present(NM) Exception handler.
Definition at line 32 of file NMFaultHandler.h.
Constructor & Destructor Documentation
NMFaultHandler::NMFaultHandler () private
The default constructor.
Definition at line 313 of file x64/NMFaultHandler.cc.
References Thread::state(), and netif::state.
Referenced by instance().
NMFaultHandler::NMFaultHandler (const NMFaultHandler &) private
The copy constructor. Note not implemented.
Member Function Documentation
bool NMFaultHandler::initialise ()
Register the NMFaultHandler with the InterruptManager.
Returns
true if sucessful, false otherwise.
Definition at line 66 of file x64/NMFaultHandler.cc.
References initialiseProcessor(), InterruptManager::instance(), and InterruptManager::registerInterruptHandler().
Referenced by instance().
bool NMFaultHandler::initialiseProcessor ()
Initialise the current processor's floating point state.
Definition at line 78 of file x64/NMFaultHandler.cc.
References Processor::cpuid().
Referenced by initialise(), and instance().
static NMFaultHandler& NMFaultHandler::instance () inline static
Get the NMFaultHandler instance
Returns
the NMFaultHandler instance.
Definition at line 37 of file NMFaultHandler.h.
References INITIALISATION_ONLY, initialise(), initialiseProcessor(), interrupt(), m_Instance, and NMFaultHandler().
Referenced by Thread::~Thread().
void NMFaultHandler::interrupt (size_t nInterruptNumber, InterruptState & state) virtual
Called when the handler is registered with the interrupt manager and the interrupt occurred
Parameters
[in] nInterruptNumber the interrupt number
[in] state reference to the state before the interrupt
Implements InterruptHandler.
Definition at line 144 of file x64/NMFaultHandler.cc.
References ERROR, Processor::information(), and Thread::state().
Referenced by instance().
Member Data Documentation
NMFaultHandler NMFaultHandler::m_Instance static private
The NMFaultHandler instance
Definition at line 66 of file NMFaultHandler.h.
Referenced by instance().
The documentation for this class was generated from the following files:
NMFaultHandler.h
x64/NMFaultHandler.cc