The Pedigree Project: CdiIrqHandler Class Reference
CdiIrqHandler Class Reference
Private Member Functions
virtual bool irq (irq_id_t number, InterruptState &state)
Additional Inherited Members
Protected Member Functions inherited from IrqHandler
virtual ~IrqHandler ()
Detailed Description
Definition at line 38 of file misc.cc.
Member Function Documentation
bool CdiIrqHandler::irq (irq_id_t irq, InterruptState & state) private virtual
Interner IRQ-Handler, der den IRQ-Handler des Treibers aufruft
Implements IrqHandler.
Definition at line 62 of file misc.cc.
References Spinlock::acquire(), Semaphore::acquire(), PhysicalMemoryManager::continuous, EXPORTED_PUBLIC, PhysicalMemoryManager::getPageSize(), Processor::information(), PhysicalMemoryManager::instance(), NOTICE, MemoryRegion::physicalAddress(), IrqManager::registerIsaIrqHandler(), Spinlock::release(), Semaphore::release(), MemoryRegion::size(), MemoryRegion::virtualAddress(), WARNING, and VirtualAddressSpace::Write.
The documentation for this class was generated from the following file:
misc.cc