The Pedigree Project: DebuggerCommand Class Reference
DebuggerCommand Class Reference abstract
kernel » debugger
#include <DebuggerCommand.h>
Public Member Functions
virtual void autocomplete (const HugeStaticString &input, HugeStaticString &output)=0
virtual bool execute (const HugeStaticString &input, HugeStaticString &output, InterruptState &state, DebuggerIO *screen)=0
virtual const NormalStaticString getString ()=0
Detailed Description
Abstract class defining the interface for a DebuggerCommand. Class Debugger has a set of these DebuggerCommands, and calls the getString and autocomplete functions to augment the command line interface with visual prompts.
Definition at line 36 of file DebuggerCommand.h.
Member Function Documentation
virtual void DebuggerCommand::autocomplete (const HugeStaticString & input, HugeStaticString & output) pure virtual
Return an autocomplete string, given an input string. The string put into *output must not exceed len in length.
Implemented in LocksCommand, DevicesCommand, AllocationCommand, SlamCommand, ThreadsCommand, TraceCommand, LogViewer, MemoryInspector, PanicCommand, BreakpointCommand, DumpCommand, HelpCommand, IoCommand, QuitCommand, StepCommand, LookupCommand, MappingCommand, Backtracer, CpuInfoCommand, DisassembleCommand, and SyscallTracerCommand.
Referenced by Debugger::start().
virtual bool DebuggerCommand::execute (const HugeStaticString & input, HugeStaticString & output, InterruptState & state, DebuggerIO * screen) pure virtual
Execute the command with the given screen. The command can take over the screen while executing, but must return it to CLI mode (via enableCLI) before returning.
Returns
True if the debugger should continue accepting commands, false if it should return control to the kernel.
Implemented in LocksCommand, DevicesCommand, TraceCommand, AllocationCommand, SlamCommand, ThreadsCommand, LogViewer, MemoryInspector, PanicCommand, BreakpointCommand, DumpCommand, HelpCommand, IoCommand, QuitCommand, StepCommand, LookupCommand, MappingCommand, SyscallTracerCommand, Backtracer, CpuInfoCommand, and DisassembleCommand.
Referenced by Debugger::start().
virtual const NormalStaticString DebuggerCommand::getString () pure virtual
Returns the string representation of this command.
Implemented in LocksCommand, DevicesCommand, TraceCommand, AllocationCommand, SlamCommand, ThreadsCommand, LogViewer, MemoryInspector, PanicCommand, BreakpointCommand, DumpCommand, HelpCommand, IoCommand, QuitCommand, StepCommand, LookupCommand, MappingCommand, SyscallTracerCommand, Backtracer, CpuInfoCommand, and DisassembleCommand.
Referenced by DebuggerIO::readCli(), and Debugger::start().
The documentation for this class was generated from the following files:
DebuggerCommand.h
DebuggerCommand.cc