The Pedigree Project: IoCommand Class Reference
IoCommand Class Reference
kernel » debugger » commands
#include <IoCommand.h>
Public Member Functions
IoCommand ()
~IoCommand ()
void autocomplete (const HugeStaticString &input, HugeStaticString &output)
bool execute (const HugeStaticString &input, HugeStaticString &output, InterruptState &state, DebuggerIO *screen)
const NormalStaticString getString ()
Detailed Description
Debugger command that list allocated I/O ports and memory-regions
Definition at line 35 of file IoCommand.h.
Constructor & Destructor Documentation
IoCommand::IoCommand ()
Default constructor - zero's stuff.
Definition at line 29 of file IoCommand.cc.
IoCommand::~IoCommand ()
Default destructor - does nothing.
Definition at line 33 of file IoCommand.cc.
Member Function Documentation
void IoCommand::autocomplete (const HugeStaticString & input, HugeStaticString & output) virtual
Return an autocomplete string, given an input string.
Implements DebuggerCommand.
Definition at line 37 of file IoCommand.cc.
bool IoCommand::execute (const HugeStaticString & input, HugeStaticString & output, InterruptState & state, DebuggerIO * screen) virtual
Execute the command with the given screen.
Implements DebuggerCommand.
Definition at line 42 of file IoCommand.cc.
References IoPortManager::allocateIoPortList(), PhysicalMemoryManager::allocateMemoryRegionList(), Vector< T >::begin(), Vector< T >::end(), IoPortManager::freeIoPortList(), IoPortManager::instance(), and PhysicalMemoryManager::instance().
const NormalStaticString IoCommand::getString () inline virtual
Returns the string representation of this command.
Implements DebuggerCommand.
Definition at line 63 of file IoCommand.h.
The documentation for this class was generated from the following files:
IoCommand.h
IoCommand.cc