The Pedigree Project: UsbUlpi Class Reference
UsbUlpi Class Reference
Public Member Functions
void initialise ()
Static Public Member Functions
static UsbUlpi & instance ()
Private Types
enum UlpiRegisters {
VendorIdLo = 0, VendorIdHi = 1, ProductIdLo = 2, ProductIdHi = 3,
FunctionControl = 4, InterfaceControl = 7, OtgControl = 0xA, UsbIntEnableRise = 0xD,
UsbIntEnableFall = 0x10, UsbIntStatus = 0x13, UsbIntLatch = 0x14, Debug = 0x15,
Scratch = 0x16, ExtendedSetAccess = 0x2F, UtmiVControlEnable = 0x30, UtmiVControlStatus = 0x33,
UtmiVControlLatch = 0x34, UtmiVStatus = 0x35, UtmiIntLatchNoClr = 0x38, VendorIntEnable = 0x3B,
VendorIntStatus = 0x3E, VendorIntLatch = 0x3F
}
enum PowerManagement {
VUSB1V5_DEV_GRP = 0xCC, VUSB1V5_TYPE = 0xCD, VUSB1V5_REMAP = 0xCE, VUSB1V8_DEV_GRP = 0xCF,
VUSB1V8_TYPE = 0xD0, VUSB1V8_REMAP = 0xD1, VUSB3V1_DEV_GRP = 0xD2, VUSB3V1_TYPE = 0xD3,
VUSB3V1_REMAP = 0xD4, VUSBCP_DEV_GRP = 0xD5, VUSBCP_TYPE = 0xD6, VUSBCP_REMAP = 0xD7,
VUSB_DEDICATED1 = 0xD8, VUSB_DEDICATED2 = 0xD9
}
Private Attributes
MemoryRegion m_MemRegionUHH
MemoryRegion m_MemRegionTLL
MemoryRegion m_MemRegionPCtl
Static Private Attributes
static UsbUlpi m_Instance
Detailed Description
Definition at line 26 of file UsbUlpi.h.
Member Function Documentation
void UsbUlpi::initialise ()
Todo:
OtgControl is invalid on Linaro's beaglexm qemu emulation.
Definition at line 79 of file UsbUlpi.cc.
References PhysicalMemoryManager::continuous, Dec, ERROR, PhysicalMemoryManager::force, Hex, PhysicalMemoryManager::instance(), VirtualAddressSpace::KernelMode, NOTICE, Prcm::SelectClockCORE(), Prcm::SelectClockPLL(), Prcm::SetClockPLL(), Prcm::SetFuncClockCORE(), Prcm::SetIfaceClockCORE(), MemoryRegion::virtualAddress(), Prcm::WaitCoreIdleStatus(), Prcm::WaitPllIdleStatus(), and VirtualAddressSpace::Write.
Member Data Documentation
UsbUlpi UsbUlpi::m_Instance static private
Todo:
super specific to a machine
Definition at line 46 of file UsbUlpi.h.
The documentation for this class was generated from the following files:
UsbUlpi.h
UsbUlpi.cc