The Pedigree Project: SyscallHandler Class Reference
SyscallHandler Class Reference abstract
kernel » processor-specifc kernel
#include <SyscallHandler.h>
Public Member Functions
virtual uintptr_t syscall (SyscallState &State)=0
Protected Member Functions
virtual ~SyscallHandler ()
Detailed Description
Abstract base class for all syscall-handlers. All syscall-handlers mustbe derived from this class
Definition at line 32 of file SyscallHandler.h.
Constructor & Destructor Documentation
SyscallHandler::~SyscallHandler () protected virtual default
Virtual destructor
Member Function Documentation
virtual uintptr_t SyscallHandler::syscall (SyscallState & State) pure virtual
Called when the handler is registered with the syscall manager and a syscall occurred
Parameters
[in] State reference to the state before the syscall
Implemented in KernelCoreSyscallManager, NativeSyscallManager, PosixSyscallManager, and PedigreeCSyscallManager.
Referenced by X86InterruptManager::interrupt(), HostedSyscallManager::syscall(), and X64SyscallManager::syscall().
The documentation for this class was generated from the following files:
SyscallHandler.h
SyscallHandler.cc