The Pedigree Project: FramebufferFile Class Reference
FramebufferFile Class Reference
Public Member Functions
FramebufferFile (String str, size_t inode, Filesystem *pParentFS, File *pParentNode)
bool initialise ()
virtual uintptr_t readBlock (uint64_t location)
virtual bool supports (const size_t command) const
virtual int command (const size_t command, void *buffer)
Public Member Functions inherited from File
File ()
File (const String &name, Time::Timestamp accessedTime, Time::Timestamp modifiedTime, Time::Timestamp creationTime, uintptr_t inode, class Filesystem *pFs, size_t size, File *pParent)
virtual ~File ()
virtual uint64_t read (uint64_t location, uint64_t size, uintptr_t buffer, bool bCanBlock=true) final
virtual uint64_t write (uint64_t location, uint64_t size, uintptr_t buffer, bool bCanBlock=true) final
virtual physical_uintptr_t getPhysicalPage (size_t offset)
virtual void returnPhysicalPage (size_t offset)
virtual void sync ()
virtual void sync (size_t offset, bool async)
Time::Timestamp getCreationTime ()
void setCreationTime (Time::Timestamp t)
Time::Timestamp getAccessedTime ()
void setAccessedTime (Time::Timestamp t)
Time::Timestamp getModifiedTime ()
void setModifiedTime (Time::Timestamp t)
String getName () const
void getName (String &s) const
virtual String getFullPath (bool bWithLabel=true)
virtual void truncate ()
size_t getSize ()
void setSize (size_t sz)
virtual bool isSymlink ()
virtual bool isDirectory ()
virtual bool isPipe () const
virtual bool isFifo () const
virtual bool isSocket () const
uintptr_t getInode () const
virtual void setInode (uintptr_t inode)
Filesystem * getFilesystem () const
void setFilesystem (Filesystem *pFs)
virtual void fileAttributeChanged ()
virtual void increaseRefCount (bool bIsWriter)
virtual void decreaseRefCount (bool bIsWriter)
void setPermissions (uint32_t perms)
uint32_t getPermissions () const
void setUid (size_t uid)
size_t getUid () const
void setGid (size_t gid)
size_t getGid () const
File * getParent () const
virtual int select (bool bWriting=false, int timeout=0)
void monitor (Thread *pThread, Event *pEvent)
void cullMonitorTargets (Thread *pThread)
virtual size_t getBlockSize () const
void enableDirect ()
void disableDirect ()
virtual void preallocate (size_t expectedSize, bool zero=true)
virtual File * open ()
Private Attributes
GraphicsService::GraphicsParameters * m_pGraphicsParameters
bool m_bTextMode
size_t m_nDepth
Additional Inherited Members
Protected Member Functions inherited from File
virtual bool isBytewise () const
virtual uint64_t readBytewise (uint64_t location, uint64_t size, uintptr_t buffer, bool bCanBlock=true)
virtual uint64_t writeBytewise (uint64_t location, uint64_t size, uintptr_t buffer, bool bCanBlock=true)
virtual void writeBlock (uint64_t location, uintptr_t addr)
virtual void extend (size_t newSize)
virtual void extend (size_t newSize, uint64_t location, uint64_t size)
void dataChanged ()
void getFilesystemLabel (HugeStaticString &s)
virtual void pinBlock (uint64_t location)
virtual void unpinBlock (uint64_t location)
void evict (uint64_t location)
void setPermissionsOnly (uint32_t perms)
void setUidOnly (size_t uid)
void setGidOnly (size_t gid)
Static Protected Member Functions inherited from File
static void writeCallback (CacheConstants::CallbackCause cause, uintptr_t loc, uintptr_t page, void *meta)
Protected Attributes inherited from File
String m_Name
Time::Timestamp m_AccessedTime
Time::Timestamp m_ModifiedTime
Time::Timestamp m_CreationTime
uintptr_t m_Inode
class Filesystem * m_pFilesystem
size_t m_Size
File * m_pParent
size_t m_nWriters
size_t m_nReaders
size_t m_Uid
size_t m_Gid
uint32_t m_Permissions
HashTable< DataCacheKey, uintptr_t > m_DataCache
bool m_bDirect
Cache m_FillCache
Mutex m_Lock
List< MonitorTarget * > m_MonitorTargets
Detailed Description
Definition at line 193 of file DevFs.h.
Member Function Documentation
int FramebufferFile::command (const size_t command, void * buffer) virtual
Handle a command.
Todo:
What if there is no text mode!?
Todo:
Magic number.
Todo:
What if there is no text mode!?
Reimplemented from File.
Definition at line 289 of file DevFs.cc.
References Dec, ERROR, File::File(), Machine::getNumVga(), Machine::getVga(), Hex, NOTICE, Framebuffer::redraw(), Vga::rememberMode(), Vga::restoreMode(), File::setGidOnly(), Vga::setLargestTextMode(), Vga::setMode(), File::setPermissionsOnly(), Display::setScreenMode(), and File::setUidOnly().
uintptr_t FramebufferFile::readBlock (uint64_t location) virtual
Internal function to retrieve an aligned 512byte section of the file.
Todo:
If this is NOT virtual, we need to do something about that.
Reimplemented from File.
Definition at line 267 of file DevFs.cc.
References ERROR.
bool FramebufferFile::supports (const size_t command) const virtual
Does this File object support the given integer-based command?
Reimplemented from File.
Definition at line 284 of file DevFs.cc.
Member Data Documentation
GraphicsService::GraphicsParameters* FramebufferFile::m_pGraphicsParameters private
Todo:
pinBlock/unpinBlock should pin/unpin physical pages!
Definition at line 210 of file DevFs.h.
The documentation for this class was generated from the following files:
DevFs.h
DevFs.cc