The Pedigree Project: TimerHandler Class Reference
TimerHandler Class Reference abstract
kernel » machine-specifc kernel
#include <TimerHandler.h>
Public Member Functions
virtual void timer (uint64_t delta, InterruptState &state)=0
Detailed Description
Abstract base class for all timer handlers. All those handlers must be derived from this class
Definition at line 32 of file TimerHandler.h.
Member Function Documentation
virtual void TimerHandler::timer (uint64_t delta, InterruptState & state) pure virtual
Called when the handler is registered with the Timer/SchedulerTimer class and a timer event occured
Parameters
[in] delta time elapsed since the last event, in nanoseconds
[in,out] state the state of the processor when the event occurred.
Implemented in Uhci, IntervalTimer, PerProcessorScheduler, CacheManager, Ib700Watchdog, HidInputManager, and RequestQueue::RequestQueueOverrunChecker.
Referenced by HidInputManager::instance(), Decrementer::interrupt(), CountCompareTimer::interrupt(), Pit::irq(), HostedSchedulerTimer::irq(), HostedTimer::irq(), and Rtc::irq().
The documentation for this class was generated from the following files:
TimerHandler.h
TimerHandler.cc