The Pedigree Project: SyscallManager Class Reference
SyscallManager Class Reference abstract
kernel » processor-specifc kernel
#include <SyscallManager.h>
Public Member Functions
virtual bool registerSyscallHandler (Service_t Service, SyscallHandler *pHandler)=0
virtual uintptr_t syscall (Service_t service, uintptr_t function, uintptr_t p1=0, uintptr_t p2=0, uintptr_t p3=0, uintptr_t p4=0, uintptr_t p5=0)=0
Static Public Member Functions
static EXPORTED_PUBLIC SyscallManager & instance ()
Protected Member Functions
SyscallManager ()
virtual ~SyscallManager ()
Private Member Functions
SyscallManager (const SyscallManager &)
SyscallManager & operator= (const SyscallManager &)
Detailed Description
The syscall manager allows syscall handler registrations and handles syscalls
Definition at line 34 of file include/pedigree/kernel/processor/SyscallManager.h.
Constructor & Destructor Documentation
SyscallManager::SyscallManager () protected default
The constructor
SyscallManager::~SyscallManager () protected virtual default
The destructor
SyscallManager::SyscallManager (const SyscallManager &) private
The copy-constructor
Note
Not implemented (singleton)
Member Function Documentation
SyscallManager & SyscallManager::instance () static
Get the syscall manager instance
Returns
instance of the syscall manager
Definition at line 70 of file arm_926e/InterruptManager.cc.
References ARM926EInterruptManager::instance().
Referenced by PedigreeCSyscallManager::call(), PosixSyscallManager::call(), NativeSyscallManager::call(), KernelCoreSyscallManager::call(), KernelCoreSyscallManager::~KernelCoreSyscallManager(), NativeSyscallManager::~NativeSyscallManager(), PedigreeCSyscallManager::~PedigreeCSyscallManager(), and PosixSyscallManager::~PosixSyscallManager().
SyscallManager& SyscallManager::operator= (const SyscallManager &) private
The copy-constructor
Note
Not implemented (singleton)
virtual bool SyscallManager::registerSyscallHandler (Service_t Service, SyscallHandler * pHandler) pure virtual
Register a syscall handler
Parameters
[in] Service the service number you want to register
[in] pHandler the interrupt handler
Returns
true, if successfully registered, false otherwise
Implemented in MIPS32InterruptManager, X86InterruptManager, PPC32InterruptManager, ARM926EInterruptManager, ARMV7InterruptManager, X64SyscallManager, and HostedSyscallManager.
Referenced by KernelCoreSyscallManager::~KernelCoreSyscallManager(), NativeSyscallManager::~NativeSyscallManager(), PedigreeCSyscallManager::~PedigreeCSyscallManager(), and PosixSyscallManager::~PosixSyscallManager().
virtual uintptr_t SyscallManager::syscall (Service_t service, uintptr_t function, uintptr_t p1 = 0, uintptr_t p2 = 0, uintptr_t p3 = 0, uintptr_t p4 = 0, uintptr_t p5 = 0) pure virtual
Calls a syscall.
Implemented in X86InterruptManager, ARM926EInterruptManager, ARMV7InterruptManager, PPC32InterruptManager, X64SyscallManager, and HostedSyscallManager.
Referenced by PedigreeCSyscallManager::call(), PosixSyscallManager::call(), NativeSyscallManager::call(), and KernelCoreSyscallManager::call().
The documentation for this class was generated from the following files:
include/pedigree/kernel/processor/SyscallManager.h
arm_926e/InterruptManager.cc
hosted/SyscallManager.cc