The Pedigree Project: ArmV7PhysicalMemoryManager::PageStack Class Reference
ArmV7PhysicalMemoryManager::PageStack Class Reference
The Stack of pages (below4GB, below64GB, no constraint).
Public Member Functions
PageStack () INITIALISATION_ONLY
physical_uintptr_t allocate (size_t constraints)
void free (physical_uintptr_t physicalAddress)
~PageStack ()
Private Member Functions
PageStack (const PageStack &)
PageStack & operator= (const PageStack &)
Private Attributes
physical_uintptr_t m_Stack [1]
void * m_Stack
size_t m_StackMax
size_t m_StackSize
Detailed Description
The Stack of pages (below4GB, below64GB, no constraint).
The actual page stack contains is a Stack of the pages with the constraints below4GB and below64GB and those pages without address size constraints.
Definition at line 81 of file kernel/core/processor/armv7/PhysicalMemoryManager.h.
Constructor & Destructor Documentation
ArmV7PhysicalMemoryManager::PageStack::PageStack ()
Default constructor does nothing
Definition at line 293 of file armv7/PhysicalMemoryManager.cc.
Referenced by ~PageStack().
ArmV7PhysicalMemoryManager::PageStack::~PageStack () inline
The destructor does nothing
Definition at line 94 of file kernel/core/processor/armv7/PhysicalMemoryManager.h.
References operator=(), and PageStack().
ArmV7PhysicalMemoryManager::PageStack::PageStack (const PageStack &) private
The copy-constructor
Note
Not implemented
Member Function Documentation
physical_uintptr_t ArmV7PhysicalMemoryManager::PageStack::allocate (size_t constraints)
Allocate a page with certain constraints
Parameters
[in] constraints either below4GB or below64GB or 0
Returns
The physical address of the allocated page or 0
Definition at line 245 of file armv7/PhysicalMemoryManager.cc.
void ArmV7PhysicalMemoryManager::PageStack::free (physical_uintptr_t physicalAddress)
Free a physical page
Parameters
[in] physicalAddress physical address of the page
Definition at line 259 of file armv7/PhysicalMemoryManager.cc.
References VirtualAddressSpace::getKernelAddressSpace(), PhysicalMemoryManager::getPageSize(), VirtualAddressSpace::KernelMode, ArmV7VirtualAddressSpace::map(), physicalAddress(), and VirtualAddressSpace::Write.
PageStack& ArmV7PhysicalMemoryManager::PageStack::operator= (const PageStack &) private
The copy-constructor
Note
Not implemented
Referenced by ~PageStack().
Member Data Documentation
physical_uintptr_t ArmV7PhysicalMemoryManager::PageStack::m_Stack[1] private
Pointer to the base address of the stack. The stack grows upwards.
Definition at line 111 of file kernel/core/processor/armv7/PhysicalMemoryManager.h.
size_t ArmV7PhysicalMemoryManager::PageStack::m_StackMax private
Size of the currently mapped stack
Definition at line 115 of file kernel/core/processor/armv7/PhysicalMemoryManager.h.
size_t ArmV7PhysicalMemoryManager::PageStack::m_StackSize private
Currently used size of the stack
Definition at line 117 of file kernel/core/processor/armv7/PhysicalMemoryManager.h.
The documentation for this class was generated from the following files:
kernel/core/processor/armv7/PhysicalMemoryManager.h
armv7/PhysicalMemoryManager.cc