The Pedigree Project: X64InterruptManager Class Reference
X64InterruptManager Class Reference
kernel » processor-specifc kernel » x64
#include <InterruptManager.h>
Classes
struct GateDescriptor
Public Member Functions
virtual bool registerInterruptHandler (size_t nInterruptNumber, InterruptHandler *pHandler)
virtual bool registerInterruptHandlerDebugger (size_t nInterruptNumber, InterruptHandler *pHandler)
virtual size_t getBreakpointInterruptNumber () PURE
virtual size_t getDebugInterruptNumber () PURE
Static Public Member Functions
static X64InterruptManager & instance ()
static void initialiseProcessor () INITIALISATION_ONLY
Static Public Member Functions inherited from InterruptManager
static InterruptManager & instance ()
Private Member Functions
void setInterruptGate (size_t nInterruptNumber, uintptr_t interruptHandler) INITIALISATION_ONLY
void setIst (size_t nInterruptNumber, size_t ist)
X64InterruptManager () INITIALISATION_ONLY
X64InterruptManager (const X64InterruptManager &)
X64InterruptManager & operator= (const X64InterruptManager &)
virtual ~X64InterruptManager ()
Static Private Member Functions
static void interrupt (InterruptState &interruptState) USED
Private Attributes
struct X64InterruptManager::GateDescriptor PACKED
Spinlock m_Lock
GateDescriptor m_IDT [256]
InterruptHandler * m_pHandler [256]
InterruptHandler * m_pDbgHandler [256]
Static Private Attributes
static X64InterruptManager m_Instance
Friends
class Processor
Additional Inherited Members
Protected Member Functions inherited from InterruptManager
InterruptManager ()
virtual ~InterruptManager ()
Detailed Description
The interrupt manager on x64 processors
Definition at line 35 of file kernel/core/processor/x64/InterruptManager.h.
Constructor & Destructor Documentation
X64InterruptManager::X64InterruptManager () private
The constructor
Definition at line 328 of file x64/InterruptManager.cc.
References m_pDbgHandler, m_pHandler, setInterruptGate(), and setIst().
Referenced by instance().
X64InterruptManager::X64InterruptManager (const X64InterruptManager &) private
Copy constructor
Note
NOT implemented
X64InterruptManager::~X64InterruptManager () private virtual
The destructor
Definition at line 347 of file x64/InterruptManager.cc.
Referenced by instance().
Member Function Documentation
size_t X64InterruptManager::getBreakpointInterruptNumber () virtual
Get the interrupt number of the breakpoint exception
Returns
the interrupt number of the breakpoint exception
Implements InterruptManager.
Definition at line 123 of file x64/InterruptManager.cc.
Referenced by instance().
size_t X64InterruptManager::getDebugInterruptNumber () virtual
Get the interrupt number of the debug exception
Returns
the interrupt number of the debug exception
Implements InterruptManager.
Definition at line 127 of file x64/InterruptManager.cc.
Referenced by instance().
void X64InterruptManager::initialiseProcessor () static
Initialises this processors IDTR
Note
This should only be called from Processor::initialise1() and Multiprocessor::applicationProcessorStartup()
Definition at line 297 of file x64/InterruptManager.cc.
References PACKED.
Referenced by instance().
static X64InterruptManager& X64InterruptManager::instance () inline static
Get the X64InterruptManager class instance
Returns
instance of the X64InterruptManager class
Definition at line 42 of file kernel/core/processor/x64/InterruptManager.h.
References getBreakpointInterruptNumber(), getDebugInterruptNumber(), INITIALISATION_ONLY, initialiseProcessor(), interrupt(), m_Instance, operator=(), PURE, registerInterruptHandler(), registerInterruptHandlerDebugger(), setInterruptGate(), setIst(), USED, X64InterruptManager(), and ~X64InterruptManager().
void X64InterruptManager::interrupt (InterruptState & interruptState) static private
Called when an interrupt was triggered
Parameters
[in] interruptState reference to the usermode/kernel state before the interrupt
Definition at line 134 of file x64/InterruptManager.cc.
References ERROR, Process::getId(), Thread::getId(), Thread::getParent(), Hex, Processor::id(), Processor::information(), Debugger::instance(), InterruptHandler::interrupt(), LIKELY, panic(), Debugger::start(), Subsystem::threadException(), and UNLIKELY.
Referenced by instance().
X64InterruptManager& X64InterruptManager::operator= (const X64InterruptManager &) private
Assignment operator
Note
NOT implemented
Referenced by instance().
bool X64InterruptManager::registerInterruptHandler (size_t nInterruptNumber, InterruptHandler * pHandler) virtual
Register an interrupt handler
Parameters
[in] nInterruptNumber the interrupt's number
[in] pHandler the interrupt handler
Returns
true, if successfully registered, false otherwise
Implements InterruptManager.
Definition at line 82 of file x64/InterruptManager.cc.
References UNLIKELY.
Referenced by instance().
bool X64InterruptManager::registerInterruptHandlerDebugger (size_t nInterruptNumber, InterruptHandler * pHandler) virtual
Register an interrupt handler (for the kernel debugger)
Parameters
[in] nInterruptNumber the interrupt's number
[in] pHandler the interrupt handler
Returns
true, if successfully registered, false otherwise
Implements InterruptManager.
Definition at line 104 of file x64/InterruptManager.cc.
References UNLIKELY.
Referenced by instance().
void X64InterruptManager::setInterruptGate (size_t nInterruptNumber, uintptr_t interruptHandler) private
Sets up an interrupt gate
Parameters
[in] interruptNumber the interrupt number
[in] interruptHandler address of the assembler interrupt handler stub
Note
This function is defined in kernel/processor/ARCH/interrupt.cc
Definition at line 309 of file x64/InterruptManager.cc.
Referenced by instance(), and X64InterruptManager().
void X64InterruptManager::setIst (size_t nInterruptNumber, size_t ist) private
Sets the IST field for a given interrupt gate
Parameters
[in] interruptNumber the interrupt number
[in] ist IST index to use
Definition at line 321 of file x64/InterruptManager.cc.
Referenced by instance(), and X64InterruptManager().
Member Data Documentation
GateDescriptor X64InterruptManager::m_IDT[256] private
The interrupt descriptor table (IDT)
Definition at line 113 of file kernel/core/processor/x64/InterruptManager.h.
X64InterruptManager X64InterruptManager::m_Instance static private
The instance of the interrupt manager
Definition at line 122 of file kernel/core/processor/x64/InterruptManager.h.
Referenced by instance().
Spinlock X64InterruptManager::m_Lock private
Spinlock protecting the member variables
Definition at line 110 of file kernel/core/processor/x64/InterruptManager.h.
InterruptHandler* X64InterruptManager::m_pDbgHandler[256] private
The debugger interrupt handlers
Definition at line 118 of file kernel/core/processor/x64/InterruptManager.h.
Referenced by X64InterruptManager().
InterruptHandler* X64InterruptManager::m_pHandler[256] private
The normal interrupt handlers
Definition at line 115 of file kernel/core/processor/x64/InterruptManager.h.
Referenced by X64InterruptManager().
The documentation for this class was generated from the following files:
kernel/core/processor/x64/InterruptManager.h
x64/InterruptManager.cc