The Pedigree Project: DevicesCommand Class Reference
DevicesCommand Class Reference
kernel » debugger » commands
#include <DevicesCommand.h>
Classes
class DeviceInfo
class DeviceTree
Public Member Functions
DevicesCommand ()
~DevicesCommand ()
void autocomplete (const HugeStaticString &input, HugeStaticString &output)
bool execute (const HugeStaticString &input, HugeStaticString &output, InterruptState &state, DebuggerIO *screen)
const NormalStaticString getString ()
Private Member Functions
void drawBackground (size_t nLines, DebuggerIO *pScreen)
Detailed Description
Allows the tracing of an execution path, single stepping and continuing to breakpoints, while displaying a disassembly, the target CPU state and a stack backtrace.
Definition at line 42 of file DevicesCommand.h.
Constructor & Destructor Documentation
DevicesCommand::DevicesCommand ()
Default constructor - zero's stuff.
Definition at line 26 of file DevicesCommand.cc.
DevicesCommand::~DevicesCommand ()
Default destructor - does nothing.
Definition at line 30 of file DevicesCommand.cc.
Member Function Documentation
void DevicesCommand::autocomplete (const HugeStaticString & input, HugeStaticString & output) virtual
Return an autocomplete string, given an input string.
Implements DebuggerCommand.
Definition at line 34 of file DevicesCommand.cc.
bool DevicesCommand::execute (const HugeStaticString & input, HugeStaticString & output, InterruptState & state, DebuggerIO * screen) virtual
Execute the command with the given screen.
Implements DebuggerCommand.
Definition at line 39 of file DevicesCommand.cc.
References DebuggerIO::drawHorizontalLine(), DebuggerIO::drawString(), Device::dump(), DebuggerIO::enableCli(), DebuggerIO::enableRefreshes(), Device::foreach(), DebuggerIO::getChar(), Device::getChild(), Device::getName(), Device::getNumChildren(), Device::getParent(), Device::getSpecificType(), DebuggerIO::getWidth(), Device::Address::m_Address, Device::Address::m_IsIoSpace, Device::Address::m_Name, and Device::Address::m_Size.
const NormalStaticString DevicesCommand::getString () inline virtual
Returns the string representation of this command.
Implements DebuggerCommand.
Definition at line 70 of file DevicesCommand.h.
The documentation for this class was generated from the following files:
DevicesCommand.h
DevicesCommand.cc