The Pedigree Project: PPCCommonProcessorInformation Class Reference
PPCCommonProcessorInformation Class Reference
Kernelprocessorppccommon
#include <ProcessorInformation.h>
Public Member Functions
VirtualAddressSpace & getVirtualAddressSpace () const
void setVirtualAddressSpace (VirtualAddressSpace &virtualAddressSpace)
uintptr_t getKernelStack () const
void setKernelStack (uintptr_t stack)
Thread * getCurrentThread () const
void setCurrentThread (Thread *pThread)
Protected Member Functions
PPCCommonProcessorInformation (ProcessorId processorId)
virtual ~PPCCommonProcessorInformation ()
Private Member Functions
PPCCommonProcessorInformation ()
PPCCommonProcessorInformation (const PPCCommonProcessorInformation &)
PPCCommonProcessorInformation & operator= (const PPCCommonProcessorInformation &)
Private Attributes
ProcessorId m_ProcessorId
VirtualAddressSpace * m_VirtualAddressSpace
Thread * m_pCurrentThread
Friends
class Processor
Detailed Description
Common mips processor information structure
Definition at line 31 of file ppc_common/ProcessorInformation.h.
Constructor & Destructor Documentation
PPCCommonProcessorInformation::PPCCommonProcessorInformation (ProcessorId processorId) inline protected
Construct a PPCCommonProcessorInformation object
Parameters
[in] processorId Identifier of the processor
Definition at line 63 of file ppc_common/ProcessorInformation.h.
virtual PPCCommonProcessorInformation::~PPCCommonProcessorInformation () inline protected virtual
The destructor does nothing
Definition at line 70 of file ppc_common/ProcessorInformation.h.
References operator=(), and PPCCommonProcessorInformation().
PPCCommonProcessorInformation::PPCCommonProcessorInformation () private
Default constructor
Note
NOT implemented
Referenced by ~PPCCommonProcessorInformation().
PPCCommonProcessorInformation::PPCCommonProcessorInformation (const PPCCommonProcessorInformation &) private
Copy-constructor
Note
NOT implemented
Member Function Documentation
VirtualAddressSpace& PPCCommonProcessorInformation::getVirtualAddressSpace () const inline
Get the current processor's VirtualAddressSpace
Returns
reference to the current processor's VirtualAddressSpace
Definition at line 38 of file ppc_common/ProcessorInformation.h.
References m_VirtualAddressSpace.
PPCCommonProcessorInformation& PPCCommonProcessorInformation::operator= (const PPCCommonProcessorInformation &) private
Assignment operator
Note
NOT implemented
Referenced by ~PPCCommonProcessorInformation().
void PPCCommonProcessorInformation::setVirtualAddressSpace (VirtualAddressSpace & virtualAddressSpace) inline
Set the current processor's VirtualAddressSpace
Parameters
[in] virtualAddressSpace reference to the new VirtualAddressSpace
Definition at line 44 of file ppc_common/ProcessorInformation.h.
References m_pCurrentThread, and m_VirtualAddressSpace.
Member Data Documentation
Thread* PPCCommonProcessorInformation::m_pCurrentThread private
The current thread
Definition at line 91 of file ppc_common/ProcessorInformation.h.
Referenced by setVirtualAddressSpace().
ProcessorId PPCCommonProcessorInformation::m_ProcessorId private
Identifier of that processor
Definition at line 87 of file ppc_common/ProcessorInformation.h.
VirtualAddressSpace* PPCCommonProcessorInformation::m_VirtualAddressSpace private
The current VirtualAddressSpace
Definition at line 89 of file ppc_common/ProcessorInformation.h.
Referenced by getVirtualAddressSpace(), and setVirtualAddressSpace().
The documentation for this class was generated from the following file:
ppc_common/ProcessorInformation.h