The Pedigree Project: Bios Class Reference
Bios Class Reference
#include <Bios.h>
Public Member Functions
void executeInterrupt (int interrupt)
uintptr_t malloc (int n)
void free (uintptr_t)
void setAx (int n)
void setBx (int n)
void setCx (int n)
void setDx (int n)
void setDi (int n)
void setEs (int n)
int getAx ()
int getBx ()
int getCx ()
int getDx ()
int getDi ()
int getEs ()
Static Public Member Functions
static Bios & instance ()
Private Member Functions
Bios ()
Private Attributes
uintptr_t mallocLoc
Static Private Attributes
static Bios m_Instance
Detailed Description
Provides an interface to BIOS functions. Currently, this is implemented as a wrapper around X86Emu, taken from the XFree86 source.
Definition at line 28 of file Bios.h.
Constructor & Destructor Documentation
Bios::Bios () private
Private constructor - Singleton class.
Definition at line 130 of file Bios.cc.
Member Function Documentation
void Bios::executeInterrupt (int interrupt)
Executes a BIOS interrupt.
Parameters
i The interrupt number to execute.
Definition at line 172 of file Bios.cc.
References ERROR, Processor::getInterrupts(), VirtualAddressSpace::getKernelAddressSpace(), Hex, Processor::information(), VirtualAddressSpace::isMapped(), VirtualAddressSpace::KernelMode, VirtualAddressSpace::map(), Processor::setInterrupts(), Processor::switchAddressSpace(), and VirtualAddressSpace::Write.
Referenced by X86Vga::rememberMode(), X86Vga::restoreMode(), and VbeDisplay::setScreenMode().
int Bios::getAx ()
Gets the AX register.
Definition at line 236 of file Bios.cc.
int Bios::getBx ()
Gets the BX register.
Definition at line 240 of file Bios.cc.
int Bios::getCx ()
Gets the CX register.
Definition at line 244 of file Bios.cc.
int Bios::getDi ()
Gets the DI register.
Definition at line 252 of file Bios.cc.
int Bios::getDx ()
Gets the DX register.
Definition at line 248 of file Bios.cc.
int Bios::getEs ()
Gets the ES register.
Definition at line 256 of file Bios.cc.
static Bios& Bios::instance () inline static
Returns the singleton BIOS instance.
Definition at line 32 of file Bios.h.
Referenced by X86Vga::rememberMode(), X86Vga::restoreMode(), and VbeDisplay::setScreenMode().
uintptr_t Bios::malloc (int n)
Returns n bytes of sub-64K space.
Definition at line 165 of file Bios.cc.
References mallocLoc.
void Bios::setAx (int n)
Sets the AX register.
Definition at line 211 of file Bios.cc.
Referenced by X86Vga::rememberMode(), X86Vga::restoreMode(), and VbeDisplay::setScreenMode().
void Bios::setBx (int n)
Sets the BX register.
Definition at line 215 of file Bios.cc.
Referenced by X86Vga::rememberMode(), X86Vga::restoreMode(), and VbeDisplay::setScreenMode().
void Bios::setCx (int n)
Sets the CX register.
Definition at line 219 of file Bios.cc.
void Bios::setDi (int n)
Sets the DI register.
Definition at line 227 of file Bios.cc.
Referenced by X86Vga::rememberMode(), X86Vga::restoreMode(), and VbeDisplay::setScreenMode().
void Bios::setDx (int n)
Sets the DX register.
Definition at line 223 of file Bios.cc.
void Bios::setEs (int n)
Sets the ES register.
Definition at line 231 of file Bios.cc.
Referenced by X86Vga::rememberMode(), X86Vga::restoreMode(), and VbeDisplay::setScreenMode().
Member Data Documentation
Bios Bios::m_Instance static private
Singleton instance.
Definition at line 83 of file Bios.h.
uintptr_t Bios::mallocLoc private
Malloc location.
Definition at line 80 of file Bios.h.
Referenced by malloc().
The documentation for this class was generated from the following files:
Bios.h
Bios.cc