The Pedigree Project: Config Class Reference
Config Class Reference
#include <Config.h>
Public Member Functions
Result * query (const char *sql)
Static Public Member Functions
static Config & instance ()
Static Private Attributes
static Config m_Instance
Detailed Description
The configuration system for Pedigree.
The system is database-based (currently using SQLite).
Definition at line 34 of file system/config/Config.h.
Member Function Documentation
Config::Result * Config::query (const char * sql)
Performs a select/update/insert/whatever query on the database.
Returns
A Result* object, which should be deleted after use, or 0.
Definition at line 150 of file subsys/native/user/config/Config.cc.
Referenced by StreamingScreenLogger::callback(), Config::Result::getStr(), and UserManager::UserManager().
The documentation for this class was generated from the following files:
system/config/Config.h
subsys/native/user/config/Config.cc