The Pedigree Project: StreamingScreenLogger Class Reference
StreamingScreenLogger Class Reference
Public Member Functions
void callback (const LogCord &cord)
Detailed Description
Definition at line 206 of file modules/system/splash/main.cc.
Member Function Documentation
void StreamingScreenLogger::callback (const LogCord & cord) inline virtual
printString is used directly as well as in this callback object, therefore we simply redirect to it.
Implements Log::LogCallback.
Definition at line 213 of file modules/system/splash/main.cc.
References Vector< T >::begin(), Framebuffer::createBuffer(), Framebuffer::destroyBuffer(), Framebuffer::draw(), Vector< T >::end(), ServiceManager::enumerateOperations(), ERROR, Config::Result::errorMessage(), Config::Result::getNum(), ServiceManager::getService(), InputManager::installCallback(), Log::installCallback(), InputManager::instance(), Log::instance(), InputManager::Key, NOTICE, ServiceFeatures::probe, ServiceFeatures::provides(), Config::query(), Framebuffer::rect(), Framebuffer::redraw(), InputManager::removeCallback(), Log::removeCallback(), Service::serve(), Display::setScreenMode(), Config::Result::succeeded(), and BootIO::write().
The documentation for this class was generated from the following file:
modules/system/splash/main.cc