The Pedigree Project: InterruptHandler Class Reference
InterruptHandler Class Reference abstract
kernel » processor-specifc kernel
Abstract base class for interrupt-handlers.
#include <InterruptHandler.h>
Public Member Functions
virtual void interrupt (size_t nInterruptNumber, InterruptState &state)=0
Protected Member Functions
virtual ~InterruptHandler ()
Detailed Description
Abstract base class for interrupt-handlers.
Abstract base class for all interrupt-handlers. All interrupt-handlers must be derived from this class
Definition at line 32 of file InterruptHandler.h.
Constructor & Destructor Documentation
InterruptHandler::~InterruptHandler () protected virtual default
Virtual destructor
Member Function Documentation
virtual void InterruptHandler::interrupt (size_t nInterruptNumber, InterruptState & state) pure virtual
Called when the handler is registered with the interrupt manager and the interrupt occurred
Parameters
[in] nInterruptNumber the interrupt number
[in] state reference to the state before the interrupt
Implemented in GPTimer, OpenPic, Pic, HostedIrqManager, Heathrow, MIPS32TlbManager, Pic, PageFaultHandler, CountCompareTimer, Debugger, Decrementer, NMFaultHandler, and ArmBeagleSerial.
Referenced by HostedInterruptManager::interrupt(), X64InterruptManager::interrupt(), and X86InterruptManager::interrupt().
The documentation for this class was generated from the following files:
InterruptHandler.h
InterruptHandler.cc