The Pedigree Project: ServiceManager Class Reference
ServiceManager Class Reference
#include <ServiceManager.h>
Classes
class InternalService
Public Member Functions
virtual ~ServiceManager ()
ServiceFeatures * enumerateOperations (const String &serviceName)
void addService (const String &serviceName, Service *s, ServiceFeatures *feats)
void removeService (const String &serviceName)
Service * getService (const String &serviceName)
Static Public Member Functions
static ServiceManager & instance ()
Private Attributes
RadixTree< InternalService * > m_Services
Static Private Attributes
static ServiceManager m_Instance
Detailed Description
Todo:
Integrate with the Event system somehow
Service Manager
The service manager controls Services in a central location, by allowing them to be referred to by name.
It also provides services such as enumeration of Service operations.
Definition at line 39 of file ServiceManager.h.
Constructor & Destructor Documentation
ServiceManager::~ServiceManager () virtual
Todo:
Delete all the pointers!
Definition at line 31 of file ServiceManager.cc.
Member Function Documentation
void ServiceManager::addService (const String & serviceName, Service * s, ServiceFeatures * feats)
Adds a service to the manager
Definition at line 46 of file ServiceManager.cc.
References ServiceManager::InternalService::pFeatures, and ServiceManager::InternalService::pService.
Referenced by PartitionService::serve().
ServiceFeatures * ServiceManager::enumerateOperations (const String & serviceName)
Enumerates all possible operations that can be performed for a given Service
Definition at line 36 of file ServiceManager.cc.
Referenced by StreamingScreenLogger::callback(), RtcFile::command(), CdiDisk::initialise(), ScsiDisk::initialise(), panic(), and Debugger::start().
Service * ServiceManager::getService (const String & serviceName)
Gets the Service object for a service
Definition at line 60 of file ServiceManager.cc.
Referenced by StreamingScreenLogger::callback(), RtcFile::command(), CdiDisk::initialise(), ScsiDisk::initialise(), panic(), and Debugger::start().
void ServiceManager::removeService (const String & serviceName)
Removes a service from the manager
Definition at line 55 of file ServiceManager.cc.
Referenced by PartitionService::serve().
Member Data Documentation
RadixTree<InternalService *> ServiceManager::m_Services private
Services we know about
Definition at line 81 of file ServiceManager.h.
The documentation for this class was generated from the following files:
ServiceManager.h
ServiceManager.cc