The Pedigree Project: DisassembleCommand Class Reference
DisassembleCommand Class Reference
kernel » debugger » commands
Public Member Functions
void autocomplete (const HugeStaticString &input, HugeStaticString &output)
bool execute (const HugeStaticString &input, HugeStaticString &output, InterruptState &state, DebuggerIO *screen)
const NormalStaticString getString ()
Detailed Description
Definition at line 32 of file DisassembleCommand.h.
Member Function Documentation
void DisassembleCommand::autocomplete (const HugeStaticString & input, HugeStaticString & output) virtual
Return an autocomplete string, given an input string.
Implements DebuggerCommand.
Definition at line 35 of file DisassembleCommand.cc.
bool DisassembleCommand::execute (const HugeStaticString & input, HugeStaticString & output, InterruptState & state, DebuggerIO * screen) virtual
Execute the command with the given screen.
Implements DebuggerCommand.
Definition at line 42 of file DisassembleCommand.cc.
References Arm926EDisassembler::disassemble(), Arm926EDisassembler::getLocation(), KernelElf::globalLookupSymbol(), KernelElf::instance(), Arm926EDisassembler::setLocation(), and Arm926EDisassembler::setMode().
const NormalStaticString DisassembleCommand::getString () virtual
Returns the string representation of this command.
Implements DebuggerCommand.
Definition at line 118 of file DisassembleCommand.cc.
The documentation for this class was generated from the following files:
DisassembleCommand.h
DisassembleCommand.cc