The Pedigree Project: BreakpointCommand Class Reference
BreakpointCommand Class Reference
kernel » debugger » commands
#include <BreakpointCommand.h>
Public Member Functions
BreakpointCommand ()
~BreakpointCommand ()
void autocomplete (const HugeStaticString &input, HugeStaticString &output)
bool execute (const HugeStaticString &input, HugeStaticString &output, InterruptState &state, DebuggerIO *screen)
const NormalStaticString getString ()
Detailed Description
Debugger command that allows viewing of the kernel log.
Definition at line 35 of file BreakpointCommand.h.
Constructor & Destructor Documentation
BreakpointCommand::BreakpointCommand ()
Default constructor - zero's stuff.
Definition at line 26 of file BreakpointCommand.cc.
BreakpointCommand::~BreakpointCommand ()
Default destructor - does nothing.
Definition at line 30 of file BreakpointCommand.cc.
Member Function Documentation
void BreakpointCommand::autocomplete (const HugeStaticString & input, HugeStaticString & output) virtual
Return an autocomplete string, given an input string.
Implements DebuggerCommand.
Definition at line 34 of file BreakpointCommand.cc.
bool BreakpointCommand::execute (const HugeStaticString & input, HugeStaticString & output, InterruptState & state, DebuggerIO * screen) virtual
Execute the command with the given screen.
Implements DebuggerCommand.
Definition at line 40 of file BreakpointCommand.cc.
References Processor::disableDebugBreakpoint(), Processor::enableDebugBreakpoint(), Processor::getDebugBreakpoint(), and Processor::getDebugBreakpointCount().
const NormalStaticString BreakpointCommand::getString () inline virtual
Returns the string representation of this command.
Implements DebuggerCommand.
Definition at line 63 of file BreakpointCommand.h.
The documentation for this class was generated from the following files:
BreakpointCommand.h
BreakpointCommand.cc