The Pedigree Project: HostedSyscallManager Class Reference
HostedSyscallManager Class Reference
Kernelprocessorhosted
#include <SyscallManager.h>
Public Member Functions
virtual bool registerSyscallHandler (Service_t Service, SyscallHandler *pHandler)
uintptr_t syscall (Service_t service, uintptr_t function, uintptr_t p1, uintptr_t p2, uintptr_t p3, uintptr_t p4, uintptr_t p5)
Static Public Member Functions
static HostedSyscallManager & instance ()
static void initialiseProcessor () INITIALISATION_ONLY
Static Public Member Functions inherited from SyscallManager
static EXPORTED_PUBLIC SyscallManager & instance ()
Private Member Functions
HostedSyscallManager () INITIALISATION_ONLY
HostedSyscallManager (const HostedSyscallManager &)
HostedSyscallManager & operator= (const HostedSyscallManager &)
virtual ~HostedSyscallManager ()
Static Private Member Functions
static void syscall (SyscallState &syscallState)
Private Attributes
Spinlock m_Lock
SyscallHandler * m_pHandler [serviceEnd]
Static Private Attributes
static HostedSyscallManager m_Instance
Additional Inherited Members
Protected Member Functions inherited from SyscallManager
SyscallManager ()
virtual ~SyscallManager ()
Detailed Description
The syscall manager on x64 processors
Definition at line 31 of file kernel/core/processor/hosted/SyscallManager.h.
Constructor & Destructor Documentation
HostedSyscallManager::HostedSyscallManager () private
The constructor
Definition at line 100 of file hosted/SyscallManager.cc.
References m_pHandler.
Referenced by instance().
HostedSyscallManager::HostedSyscallManager (const HostedSyscallManager &) private
Copy constructor
Note
NOT implemented
HostedSyscallManager::~HostedSyscallManager () private virtual
The destructor
Definition at line 107 of file hosted/SyscallManager.cc.
Referenced by instance().
Member Function Documentation
void HostedSyscallManager::initialiseProcessor () static
Initialises this processors syscall handling
Note
This should only be called from Processor::initialise1() and Multiprocessor::applicationProcessorStartup()
Definition at line 96 of file hosted/SyscallManager.cc.
Referenced by Processor::initialisationDone(), and instance().
static HostedSyscallManager& HostedSyscallManager::instance () inline static
Get the HostedSyscallManager class instance
Returns
instance of the HostedSyscallManager class
Definition at line 36 of file kernel/core/processor/hosted/SyscallManager.h.
References HostedSyscallManager(), INITIALISATION_ONLY, initialiseProcessor(), m_Instance, operator=(), registerSyscallHandler(), syscall(), and ~HostedSyscallManager().
HostedSyscallManager& HostedSyscallManager::operator= (const HostedSyscallManager &) private
Assignment operator
Note
NOT implemented
Referenced by instance().
bool HostedSyscallManager::registerSyscallHandler (Service_t Service, SyscallHandler * pHandler) virtual
Register a syscall handler
Parameters
[in] Service the service number you want to register
[in] pHandler the interrupt handler
Returns
true, if successfully registered, false otherwise
Implements SyscallManager.
Definition at line 32 of file hosted/SyscallManager.cc.
References UNLIKELY.
Referenced by instance().
uintptr_t HostedSyscallManager::syscall (Service_t service, uintptr_t function, uintptr_t p1, uintptr_t p2, uintptr_t p3, uintptr_t p4, uintptr_t p5) virtual
Called to execute a syscall.
Implements SyscallManager.
Definition at line 85 of file hosted/SyscallManager.cc.
Referenced by instance().
void HostedSyscallManager::syscall (SyscallState & syscallState) static private
Called when a syscall was called
Parameters
[in] syscallState reference to the usermode state before the syscall
Definition at line 49 of file hosted/SyscallManager.cc.
References Thread::Exit, Processor::information(), LIKELY, NOTICE, SyscallHandler::syscall(), and UNLIKELY.
Member Data Documentation
HostedSyscallManager HostedSyscallManager::m_Instance static private
The instance of the syscall manager
Definition at line 78 of file kernel/core/processor/hosted/SyscallManager.h.
Referenced by instance().
Spinlock HostedSyscallManager::m_Lock private
Spinlock protecting the member variables
Definition at line 72 of file kernel/core/processor/hosted/SyscallManager.h.
SyscallHandler* HostedSyscallManager::m_pHandler[serviceEnd] private
The syscall handlers
Definition at line 75 of file kernel/core/processor/hosted/SyscallManager.h.
Referenced by HostedSyscallManager().
The documentation for this class was generated from the following files:
kernel/core/processor/hosted/SyscallManager.h
hosted/SyscallManager.cc