The Pedigree Project: AllocationCommand Class Reference
AllocationCommand Class Reference
kernel » debugger » commands
#include <AllocationCommand.h>
Classes
struct Allocation
Public Member Functions
AllocationCommand ()
~AllocationCommand ()
void autocomplete (const HugeStaticString &input, HugeStaticString &output)
bool execute (const HugeStaticString &input, HugeStaticString &output, InterruptState &state, DebuggerIO *screen)
const NormalStaticString getString ()
void allocatePage (physical_uintptr_t page)
void freePage (physical_uintptr_t page)
void postProcess ()
bool isMallocing ()
void setMallocing (bool b)
void checkpoint ()
virtual const char * getLine1 (size_t index, DebuggerIO::Colour &colour, DebuggerIO::Colour &bgColour)
virtual const char * getLine2 (size_t index, size_t &colOffset, DebuggerIO::Colour &colour, DebuggerIO::Colour &bgColour)
virtual size_t getLineCount ()
Public Member Functions inherited from Scrollable
void move (size_t x, size_t y)
void resize (size_t width, size_t height)
void scroll (ssize_t lines)
void scrollTo (size_t absolute)
void refresh (DebuggerIO *pScreen)
void setScrollKeys (char up, char down)
ssize_t getLine ()
void centreOn (size_t line)
size_t height () const
size_t width () const
Private Attributes
Vector< Allocation * > m_Allocations
Vector< void * > m_Frees
size_t m_nLines
Tree< size_t, Allocation * > m_Tree
Tree< size_t, Allocation * >::Iterator m_It
size_t m_nIdx
bool m_bAllocating
Additional Inherited Members
Protected Attributes inherited from Scrollable
size_t m_x
size_t m_y
size_t m_width
size_t m_height
ssize_t m_line
char m_ScrollUp
char m_ScrollDown
Detailed Description
Traces page allocations.
Definition at line 40 of file AllocationCommand.h.
Constructor & Destructor Documentation
AllocationCommand::AllocationCommand ()
Default constructor - zeroes stuff.
Definition at line 35 of file AllocationCommand.cc.
AllocationCommand::~AllocationCommand ()
Default destructor - does nothing.
Definition at line 41 of file AllocationCommand.cc.
Member Function Documentation
void AllocationCommand::autocomplete (const HugeStaticString & input, HugeStaticString & output) virtual
Return an autocomplete string, given an input string.
Implements DebuggerCommand.
Definition at line 45 of file AllocationCommand.cc.
bool AllocationCommand::execute (const HugeStaticString & input, HugeStaticString & output, InterruptState & state, DebuggerIO * screen) virtual
Execute the command with the given screen.
Implements DebuggerCommand.
Definition at line 50 of file AllocationCommand.cc.
References Vector< T >::begin(), Vector< T >::clear(), DebuggerIO::drawHorizontalLine(), DebuggerIO::drawString(), DebuggerIO::enableCli(), Vector< T >::end(), Vector< T >::erase(), DebuggerIO::getChar(), Process::getId(), DebuggerIO::getWidth(), KernelElf::globalLookupSymbol(), Processor::information(), KernelElf::instance(), Backtrace::m_pReturnAddresses, NOTICE, Backtrace::performBpBacktrace(), and Vector< T >::pushBack().
const NormalStaticString AllocationCommand::getString () inline virtual
Returns the string representation of this command.
Implements DebuggerCommand.
Definition at line 68 of file AllocationCommand.h.
The documentation for this class was generated from the following files:
AllocationCommand.h
AllocationCommand.cc