The Pedigree Project: CountCompareTimer Class Reference
CountCompareTimer Class Reference
kernel » machine-specifc kernel » x86-common
#include <Timer.h>
Public Member Functions
virtual bool registerHandler (TimerHandler *handler)
bool initialise () INITIALISATION_ONLY
void uninitialise ()
Static Public Member Functions
static CountCompareTimer & instance ()
Protected Member Functions
CountCompareTimer () INITIALISATION_ONLY
virtual ~CountCompareTimer ()
Protected Member Functions inherited from SchedulerTimer
SchedulerTimer ()
virtual ~SchedulerTimer ()
Private Member Functions
CountCompareTimer (const CountCompareTimer &)
CountCompareTimer & operator= (const CountCompareTimer &)
virtual void interrupt (size_t interruptNumber, InterruptState &state)
virtual ~InterruptHandler ()
Private Attributes
TimerHandler * m_Handler
uint32_t m_Compare
Static Private Attributes
static CountCompareTimer m_Instance
Detailed Description
The programmable interval timer implements the SchedulerTimer interface
Definition at line 31 of file kernel/machine/mips_common/Timer.h.
Constructor & Destructor Documentation
CountCompareTimer::CountCompareTimer () protected
The default constructor
Definition at line 73 of file mips_common/Timer.cc.
Referenced by instance(), and ~CountCompareTimer().
virtual CountCompareTimer::~CountCompareTimer () inline protected virtual
The destructor
Definition at line 55 of file kernel/machine/mips_common/Timer.h.
References CountCompareTimer(), interrupt(), and operator=().
CountCompareTimer::CountCompareTimer (const CountCompareTimer &) private
The copy-constructor
Note
NOT implemented
Member Function Documentation
bool CountCompareTimer::initialise ()
Initialises the class
Returns
true, if successful, false otherwise
Definition at line 39 of file mips_common/Timer.cc.
References Hex, InterruptManager::instance(), NOTICE, and Processor::setInterrupts().
Referenced by Malta::initialise(), and instance().
static CountCompareTimer& CountCompareTimer::instance () inline static
Get the CountCompareTimer class instance
Definition at line 35 of file kernel/machine/mips_common/Timer.h.
References CountCompareTimer(), INITIALISATION_ONLY, initialise(), m_Instance, and uninitialise().
Referenced by Malta::initialise().
void CountCompareTimer::interrupt (size_t nInterruptNumber, InterruptState & state) private virtual
Called when the handler is registered with the interrupt manager and the interrupt occurred
Parameters
[in] nInterruptNumber the interrupt number
[in] state reference to the state before the interrupt
Implements InterruptHandler.
Definition at line 77 of file mips_common/Timer.cc.
References LIKELY, m_Handler, and TimerHandler::timer().
Referenced by ~CountCompareTimer().
CountCompareTimer& CountCompareTimer::operator= (const CountCompareTimer &) private
The assignment operator
Note
NOT implemented
Referenced by ~CountCompareTimer().
void CountCompareTimer::uninitialise ()
Uninitialises the class
Definition at line 69 of file mips_common/Timer.cc.
Referenced by instance().
Member Data Documentation
TimerHandler* CountCompareTimer::m_Handler private
The scheduler
Definition at line 73 of file kernel/machine/mips_common/Timer.h.
Referenced by interrupt().
CountCompareTimer CountCompareTimer::m_Instance static private
The CountCompareTimer class instance
Definition at line 76 of file kernel/machine/mips_common/Timer.h.
Referenced by instance().
The documentation for this class was generated from the following files:
kernel/machine/mips_common/Timer.h
mips_common/Timer.cc