The Pedigree Project: UnixFilesystem Class Reference
UnixFilesystem Class Reference
#include <UnixFilesystem.h>
Public Member Functions
virtual bool initialise (Disk *pDisk)
virtual File * getRoot () const
virtual String getVolumeLabel () const
virtual void truncate (File *pFile)
virtual void fileAttributeChanged (File *pFile)
virtual void cacheDirectoryContents (File *pFile)
virtual void extend (File *pFile, size_t size)
Public Member Functions inherited from Filesystem
Filesystem ()
virtual ~Filesystem ()
virtual File * find (const StringView &path)
virtual File * find (const String &path)
virtual File * find (const StringView &path, File *pStartNode)
virtual File * find (const String &path, File *pStartNode)
bool createFile (const StringView &path, uint32_t mask, File *pStartNode=0)
bool createDirectory (const StringView &path, uint32_t mask, File *pStartNode=0)
bool createSymlink (const StringView &path, const String &value, File *pStartNode=0)
bool createLink (const StringView &path, File *target, File *pStartNode=0)
bool remove (const StringView &path, File *pStartNode=0)
Disk * getDisk ()
bool isReadOnly ()
virtual bool isCaseSensitive ()
Protected Member Functions
virtual bool createFile (File *parent, const String &filename, uint32_t mask)
virtual bool createDirectory (File *parent, const String &filename, uint32_t mask)
virtual bool createSymlink (File *parent, const String &filename, const String &value)
virtual bool remove (File *parent, File *file)
Protected Member Functions inherited from Filesystem
virtual bool createLink (File *parent, const String &filename, File *target)
Private Member Functions
virtual bool isBytewise () const
Private Attributes
File * m_pRoot
Static Private Attributes
static String m_VolumeLabel
Additional Inherited Members
Public Types inherited from Filesystem
typedef Filesystem *(* ProbeCallback) (Disk *)
Protected Attributes inherited from Filesystem
bool m_bReadOnly
Disk * m_pDisk
Detailed Description
UnixFilesystem: UNIX sockets.
This filesystem is mounted with the "unix" 'volume' label, and provides the filesystem abstraction for UNIX sockets (at least, non-anonymous ones).
Definition at line 43 of file UnixFilesystem.h.
Member Function Documentation
bool UnixFilesystem::createDirectory (File * parent, const String & filename, uint32_t mask) protected virtual
createDirectory calls this after it has parsed the string path.
Implements Filesystem.
Definition at line 522 of file UnixFilesystem.cc.
References Directory::fromFile().
Referenced by getVolumeLabel().
bool UnixFilesystem::createFile (File * parent, const String & filename, uint32_t mask) protected virtual
createFile calls this after it has parsed the string path.
Implements Filesystem.
Definition at line 501 of file UnixFilesystem.cc.
References Directory::fromFile().
Referenced by getVolumeLabel().
virtual bool UnixFilesystem::createSymlink (File * parent, const String & filename, const String & value) inline protected virtual
createSymlink calls this after it has parsed the string path.
Implements Filesystem.
Definition at line 91 of file UnixFilesystem.h.
virtual File* UnixFilesystem::getRoot () const inline virtual
Returns the root filesystem node.
Implements Filesystem.
Definition at line 54 of file UnixFilesystem.h.
virtual String UnixFilesystem::getVolumeLabel () const inline virtual
Returns a string identifying the volume label.
Implements Filesystem.
Definition at line 59 of file UnixFilesystem.h.
References Directory::cacheDirectoryContents(), createDirectory(), createFile(), Directory::fromFile(), and File::isDirectory().
virtual bool UnixFilesystem::initialise (Disk * pDisk) inline virtual
Populates this filesystem with data from the given Disk device.
Returns
true on success, false on failure.
Implements Filesystem.
Definition at line 49 of file UnixFilesystem.h.
bool UnixFilesystem::remove (File * parent, File * file) protected virtual
Remove a file given a parent and file, assuming path parsing already completed.
Implements Filesystem.
Definition at line 546 of file UnixFilesystem.cc.
References Directory::fromFile().
The documentation for this class was generated from the following files:
UnixFilesystem.h
UnixFilesystem.cc