The Pedigree Project: MemoryPressureProcessKiller Class Reference
MemoryPressureProcessKiller Class Reference
#include <MemoryPressureKiller.h>
Public Member Functions
virtual const String getMemoryPressureDescription ()
virtual bool compact ()
Detailed Description
Handles killing processes if memory pressure is encountered.
Definition at line 24 of file MemoryPressureKiller.h.
Member Function Documentation
bool MemoryPressureProcessKiller::compact () virtual
Called by MemoryPressureManager to request this handler to take action to reduce memory pressure.
Returns
true if pages were released, false otherwise.
Implements MemoryPressureHandler.
Definition at line 32 of file MemoryPressureKiller.cc.
References Dec, Process::getId(), Scheduler::getNumProcesses(), Scheduler::getProcess(), Process::getThread(), Hex, Scheduler::instance(), Subsystem::kill(), and Scheduler::yield().
The documentation for this class was generated from the following files:
MemoryPressureKiller.h
MemoryPressureKiller.cc