The Pedigree Project: Decrementer Class Reference
Decrementer Class Reference
Kernelmachineppccommon
#include <Decrementer.h>
Public Member Functions
virtual bool registerHandler (TimerHandler *handler)
bool initialise () INITIALISATION_ONLY
void uninitialise ()
Decrementer () INITIALISATION_ONLY
virtual ~Decrementer ()
Private Member Functions
Decrementer (const Decrementer &)
Decrementer & operator= (const Decrementer &)
virtual void interrupt (size_t interruptNumber, InterruptState &state)
virtual ~InterruptHandler ()
Private Attributes
TimerHandler * m_Handler
uint32_t m_Frequency
Static Private Attributes
static Decrementer m_Instance
Additional Inherited Members
Protected Member Functions inherited from SchedulerTimer
SchedulerTimer ()
virtual ~SchedulerTimer ()
Detailed Description
The decrementer timer implements the SchedulerTimer interface
Definition at line 33 of file Decrementer.h.
Constructor & Destructor Documentation
Decrementer::Decrementer ()
The default constructor
Definition at line 68 of file Decrementer.cc.
Referenced by ~Decrementer().
virtual Decrementer::~Decrementer () inline virtual
The destructor
Definition at line 50 of file Decrementer.h.
References Decrementer(), interrupt(), and operator=().
Decrementer::Decrementer (const Decrementer &) private
The copy-constructor
Note
NOT implemented
Member Function Documentation
bool Decrementer::initialise ()
Initialises the class
Returns
true, if successful, false otherwise
Definition at line 41 of file Decrementer.cc.
References InterruptManager::instance(), OpenFirmware::instance(), m_Frequency, and WARNING.
void Decrementer::interrupt (size_t nInterruptNumber, InterruptState & state) private virtual
Called when the handler is registered with the interrupt manager and the interrupt occurred
Parameters
[in] nInterruptNumber the interrupt number
[in] state reference to the state before the interrupt
Implements InterruptHandler.
Definition at line 74 of file Decrementer.cc.
References LIKELY, m_Frequency, m_Handler, and TimerHandler::timer().
Referenced by ~Decrementer().
Decrementer& Decrementer::operator= (const Decrementer &) private
The assignment operator
Note
NOT implemented
Referenced by ~Decrementer().
void Decrementer::uninitialise ()
Uninitialises the class
Definition at line 64 of file Decrementer.cc.
Member Data Documentation
uint32_t Decrementer::m_Frequency private
The rate of the decrementer, in hertz
Definition at line 71 of file Decrementer.h.
Referenced by initialise(), and interrupt().
TimerHandler* Decrementer::m_Handler private
The scheduler
Definition at line 68 of file Decrementer.h.
Referenced by interrupt().
Decrementer Decrementer::m_Instance static private
The Decrementer class instance
Definition at line 74 of file Decrementer.h.
The documentation for this class was generated from the following files:
Decrementer.h
Decrementer.cc