The Pedigree Project: PedigreeCSyscallManager Class Reference
PedigreeCSyscallManager Class Reference
Public Member Functions
void initialise ()
uintptr_t call (uintptr_t function, uintptr_t p1=0, uintptr_t p2=0, uintptr_t p3=0, uintptr_t p4=0, uintptr_t p5=0)
virtual uintptr_t syscall (SyscallState &state)
PedigreeCSyscallManager ()
virtual ~PedigreeCSyscallManager ()
Private Member Functions
PedigreeCSyscallManager (const PedigreeCSyscallManager &)
PedigreeCSyscallManager & operator= (const PedigreeCSyscallManager &)
Additional Inherited Members
Protected Member Functions inherited from SyscallHandler
virtual ~SyscallHandler ()
Detailed Description
Definition at line 26 of file PedigreeCSyscallManager.h.
Constructor & Destructor Documentation
PedigreeCSyscallManager::PedigreeCSyscallManager ()
The constructor
Definition at line 32 of file PedigreeCSyscallManager.cc.
PedigreeCSyscallManager::~PedigreeCSyscallManager () virtual
The destructor
Definition at line 36 of file PedigreeCSyscallManager.cc.
References SyscallManager::instance(), and SyscallManager::registerSyscallHandler().
PedigreeCSyscallManager::PedigreeCSyscallManager (const PedigreeCSyscallManager &) private
The copy-constructor
Note
Not implemented (singleton)
Member Function Documentation
uintptr_t PedigreeCSyscallManager::call (uintptr_t function, uintptr_t p1 = 0, uintptr_t p2 = 0, uintptr_t p3 = 0, uintptr_t p4 = 0, uintptr_t p5 = 0)
Calls a syscall.
Definition at line 46 of file PedigreeCSyscallManager.cc.
References Dec, ERROR, SyscallManager::instance(), and SyscallManager::syscall().
PedigreeCSyscallManager& PedigreeCSyscallManager::operator= (const PedigreeCSyscallManager &) private
The copy-constructor
Note
Not implemented (singleton)
uintptr_t PedigreeCSyscallManager::syscall (SyscallState & state) virtual
Called when a syscall arrives.
Implements SyscallHandler.
Definition at line 61 of file PedigreeCSyscallManager.cc.
References Dec, ERROR, and Processor::setInterrupts().
The documentation for this class was generated from the following files:
PedigreeCSyscallManager.h
PedigreeCSyscallManager.cc