The Pedigree Project: MappingCommand Class Reference
MappingCommand Class Reference
kernel » debugger » commands
#include <MappingCommand.h>
Public Member Functions
MappingCommand ()
~MappingCommand ()
void autocomplete (const HugeStaticString &input, HugeStaticString &output)
bool execute (const HugeStaticString &input, HugeStaticString &output, InterruptState &state, DebuggerIO *screen)
const NormalStaticString getString ()
Detailed Description
Calculates effective addresses and physical addresses.
Definition at line 34 of file MappingCommand.h.
Constructor & Destructor Documentation
MappingCommand::MappingCommand ()
Default constructor - zeroes stuff.
Definition at line 29 of file MappingCommand.cc.
MappingCommand::~MappingCommand ()
Default destructor - does nothing.
Definition at line 33 of file MappingCommand.cc.
Member Function Documentation
void MappingCommand::autocomplete (const HugeStaticString & input, HugeStaticString & output) virtual
Return an autocomplete string, given an input string.
Implements DebuggerCommand.
Definition at line 37 of file MappingCommand.cc.
bool MappingCommand::execute (const HugeStaticString & input, HugeStaticString & output, InterruptState & state, DebuggerIO * screen) virtual
Execute the command with the given screen.
Todo:
define operator != on StaticString
Implements DebuggerCommand.
Definition at line 42 of file MappingCommand.cc.
References VirtualAddressSpace::getKernelAddressSpace(), VirtualAddressSpace::getMapping(), PhysicalMemoryManager::getPageSize(), Processor::information(), VirtualAddressSpace::isMapped(), and Processor::switchAddressSpace().
const NormalStaticString MappingCommand::getString () inline virtual
Returns the string representation of this command.
Implements DebuggerCommand.
Definition at line 62 of file MappingCommand.h.
The documentation for this class was generated from the following files:
MappingCommand.h
MappingCommand.cc