The Pedigree Project: Mac Class Reference
Mac Class Reference
#include <Mac.h>
Public Member Functions
virtual void initialise ()
virtual Serial * getSerial (size_t n)
virtual size_t getNumSerial ()
virtual Vga * getVga (size_t n)
virtual size_t getNumVga ()
virtual IrqManager * getIrqManager ()
virtual SchedulerTimer * getSchedulerTimer ()
virtual Timer * getTimer ()
virtual Keyboard * getKeyboard ()
virtual void initialiseDeviceTree ()
Public Member Functions inherited from Machine
virtual void initialise2 ()
Called after debugger startup.
virtual void initialise3 ()
Called after processor startup - for thread creation etc.
virtual void deinitialise ()
bool isInitialised ()
virtual void setKeyboard (Keyboard *kb)=0
Static Public Member Functions
static Machine & instance ()
Static Public Member Functions inherited from Machine
static Machine & instance ()
Private Member Functions
Mac ()
Mac (const Mac &)
Mac & operator= (const Mac &)
virtual ~Mac ()
Private Attributes
PPCSerial m_Serial [2]
Decrementer m_Decrementer
PPCVga m_Vga
PPCKeyboard m_Keyboard
IrqManager * m_pIrqManager
Static Private Attributes
static Mac m_Instance
Additional Inherited Members
Protected Attributes inherited from Machine
bool m_bInitialised
Detailed Description
Concretion of the abstract Machine class for a MIPS Malta board.
Definition at line 33 of file Mac.h.
Constructor & Destructor Documentation
Mac::Mac () private
Default constructor, does nothing.
Definition at line 80 of file Mac.cc.
Mac::~Mac () private virtual
Virtual destructor, does nothing.
Definition at line 83 of file Mac.cc.
References Device::addChild(), OpenFirmware::getFirstChild(), OpenFirmware::getSibling(), OpenFirmware::instance(), Device::setInterruptNumber(), Device::setParent(), and Device::setSpecificType().
Member Function Documentation
Keyboard * Mac::getKeyboard () virtual
Returns the keyboard device.
Implements Machine.
Definition at line 75 of file Mac.cc.
size_t Mac::getNumSerial () virtual
Returns the number of Serial device.
Implements Machine.
Definition at line 50 of file Mac.cc.
size_t Mac::getNumVga () virtual
Returns the number of VGA devices.
Implements Machine.
Definition at line 58 of file Mac.cc.
SchedulerTimer * Mac::getSchedulerTimer () virtual
Returns the SchedulerTimer device.
Implements Machine.
Definition at line 66 of file Mac.cc.
Serial * Mac::getSerial (size_t n) virtual
Returns the n'th Serial device.
Implements Machine.
Definition at line 46 of file Mac.cc.
Timer * Mac::getTimer () virtual
Returns the n'th Timer device.
Implements Machine.
Definition at line 70 of file Mac.cc.
Vga * Mac::getVga (size_t n) virtual
Returns the n'th VGA device.
Implements Machine.
Definition at line 54 of file Mac.cc.
void Mac::initialise () virtual
Initialises the machine.
Implements Machine.
Definition at line 39 of file Mac.cc.
Referenced by initialiseDeviceTree().
void Mac::initialiseDeviceTree () virtual
Initialises the machine's base device tree, if one exists, to prefill the tree with those devices that are not otherwise able to be detected via some sort of bus support.
Reimplemented from Machine.
Definition at line 121 of file Mac.cc.
References ERROR, initialise(), Heathrow::instance(), OpenFirmware::instance(), OpenPic::instance(), and Device::root().
The documentation for this class was generated from the following files:
Mac.h
Mac.cc