The Pedigree Project: Gears Class Reference
Gears Class Reference
Public Member Functions
bool initOpenGL ()
void deinitOpenGL ()
void reposition (PedigreeGraphics::Rect newrt)
virtual bool render (PedigreeGraphics::Rect &rt, PedigreeGraphics::Rect &dirty)
Public Member Functions inherited from Widget
uint64_t getHandle () const
bool construct (const char *endpoint, const char *title, widgetCallback_t cb, PedigreeGraphics::Rect &dimensions)
bool setTitle (const std::string &newTitle)
bool redraw (PedigreeGraphics::Rect &rt)
bool visibility (bool vis)
void destroy ()
void * getRawFramebuffer ()
int getSocket () const
Private Member Functions
bool glResize (size_t w, size_t h)
Private Attributes
uint8_t * fb
bool m_bGlInit
bool m_bContextValid
OSMesaContext gl_ctx
size_t m_nWidth
size_t m_nHeight
Additional Inherited Members
Static Public Member Functions inherited from Widget
static void checkForEvents (bool bAsync=false)
Detailed Description
Definition at line 316 of file gears.cc.
Member Function Documentation
virtual bool Gears::render (PedigreeGraphics::Rect & rt, PedigreeGraphics::Rect & dirty) inline virtual
Called to actually render the widget. Would normally be called by the RepaintNeeded handler by application code.
Parameters
rt Area that needs to be rendered.
dirty Object containing a dirty rectangle for redrawing.
Returns
True if the render succeeded, False otherwise.
Implements Widget.
Definition at line 350 of file gears.cc.
References Widget::checkForEvents(), Widget::construct(), Widget::destroy(), Widget::getRawFramebuffer(), Widget::redraw(), and render().
Referenced by render().
The documentation for this class was generated from the following file:
gears.cc