The Pedigree Project: DevFs Class Reference
DevFs Class Reference
#include <DevFs.h>
Public Member Functions
virtual bool initialise (Disk *pDisk)
virtual File * getRoot () const
virtual String getVolumeLabel () const
virtual size_t getNextInode ()
virtual void revertInode ()
void handleInput (InputManager::InputNotification &in)
VirtualTerminalManager & getTerminalManager ()
Public Member Functions inherited from Filesystem
Filesystem ()
virtual ~Filesystem ()
virtual File * find (const StringView &path)
virtual File * find (const String &path)
virtual File * find (const StringView &path, File *pStartNode)
virtual File * find (const String &path, File *pStartNode)
bool createFile (const StringView &path, uint32_t mask, File *pStartNode=0)
bool createDirectory (const StringView &path, uint32_t mask, File *pStartNode=0)
bool createSymlink (const StringView &path, const String &value, File *pStartNode=0)
bool createLink (const StringView &path, File *target, File *pStartNode=0)
bool remove (const StringView &path, File *pStartNode=0)
Disk * getDisk ()
bool isReadOnly ()
virtual bool isCaseSensitive ()
Protected Member Functions
virtual bool createFile (File *parent, const String &filename, uint32_t mask)
virtual bool createDirectory (File *parent, const String &filename, uint32_t mask)
virtual bool createSymlink (File *parent, const String &filename, const String &value)
virtual bool remove (File *parent, File *file)
Protected Member Functions inherited from Filesystem
virtual bool createLink (File *parent, const String &filename, File *target)
Private Member Functions
DevFs (const DevFs &)
DevFs & operator= (const DevFs &)
Private Attributes
DevFsDirectory * m_pRoot
TextIO * m_pTty
size_t m_NextInode
TextIO * m_pTtys [DEVFS_NUMTTYS]
File * m_pTtyFiles [DEVFS_NUMTTYS]
size_t m_CurrentTty
VirtualTerminalManager * m_VtManager
PsAuxFile * m_pPsAuxFile
Additional Inherited Members
Public Types inherited from Filesystem
typedef Filesystem *(* ProbeCallback) (Disk *)
Protected Attributes inherited from Filesystem
bool m_bReadOnly
Disk * m_pDisk
Detailed Description
This class provides /dev
Definition at line 287 of file DevFs.h.
Member Function Documentation
virtual bool DevFs::createDirectory (File * parent, const String & filename, uint32_t mask) inline protected virtual
createDirectory calls this after it has parsed the string path.
Implements Filesystem.
Definition at line 323 of file DevFs.h.
virtual bool DevFs::createFile (File * parent, const String & filename, uint32_t mask) inline protected virtual
createFile calls this after it has parsed the string path.
Implements Filesystem.
Definition at line 318 of file DevFs.h.
virtual bool DevFs::createSymlink (File * parent, const String & filename, const String & value) inline protected virtual
createSymlink calls this after it has parsed the string path.
Implements Filesystem.
Definition at line 328 of file DevFs.h.
virtual File* DevFs::getRoot () const inline virtual
Returns the root filesystem node.
Implements Filesystem.
Definition at line 298 of file DevFs.h.
virtual String DevFs::getVolumeLabel () const inline virtual
Returns a string identifying the volume label.
Implements Filesystem.
Definition at line 302 of file DevFs.h.
bool DevFs::initialise (Disk * pDisk) virtual
Populates this filesystem with data from the given Disk device.
Returns
true on success, false on failure.
Implements Filesystem.
Definition at line 491 of file DevFs.cc.
References File::getName(), TextIO::initialise(), InputManager::installCallback(), InputManager::instance(), InputManager::Key, WARNING, and File::write().
virtual bool DevFs::remove (File * parent, File * file) inline protected virtual
Remove a file given a parent and file, assuming path parsing already completed.
Implements Filesystem.
Definition at line 332 of file DevFs.h.
The documentation for this class was generated from the following files:
DevFs.h
DevFs.cc