The Pedigree Project: SlamCommand Class Reference
SlamCommand Class Reference
kernel » debugger » commands
#include <SlamCommand.h>
Classes
struct SlamAllocation
Public Member Functions
SlamCommand ()
~SlamCommand ()
void autocomplete (const HugeStaticString &input, HugeStaticString &output)
bool execute (const HugeStaticString &input, HugeStaticString &output, InterruptState &state, DebuggerIO *screen)
const NormalStaticString getString ()
void addAllocation (uintptr_t *backtrace, size_t requested)
void removeAllocation (uintptr_t *backtrace, size_t requested)
void clean ()
virtual const char * getLine1 (size_t index, DebuggerIO::Colour &colour, DebuggerIO::Colour &bgColour)
virtual const char * getLine2 (size_t index, size_t &colOffset, DebuggerIO::Colour &colour, DebuggerIO::Colour &bgColour)
virtual size_t getLineCount ()
Public Member Functions inherited from Scrollable
void move (size_t x, size_t y)
void resize (size_t width, size_t height)
void scroll (ssize_t lines)
void scrollTo (size_t absolute)
void refresh (DebuggerIO *pScreen)
void setScrollKeys (char up, char down)
ssize_t getLine ()
void centreOn (size_t line)
size_t height () const
size_t width () const
Private Attributes
Tree< size_t, SlamAllocation * > m_Tree
Tree< size_t, SlamAllocation * >::Iterator m_It
size_t m_nLines
size_t m_nIdx
bool m_Lock
Additional Inherited Members
Protected Attributes inherited from Scrollable
size_t m_x
size_t m_y
size_t m_width
size_t m_height
ssize_t m_line
char m_ScrollUp
char m_ScrollDown
Detailed Description
Traces page allocations.
Definition at line 40 of file SlamCommand.h.
Constructor & Destructor Documentation
SlamCommand::SlamCommand ()
Default constructor - zeroes stuff.
Definition at line 31 of file SlamCommand.cc.
SlamCommand::~SlamCommand ()
Default destructor - does nothing.
Definition at line 37 of file SlamCommand.cc.
Member Function Documentation
void SlamCommand::autocomplete (const HugeStaticString & input, HugeStaticString & output) virtual
Return an autocomplete string, given an input string.
Implements DebuggerCommand.
Definition at line 41 of file SlamCommand.cc.
bool SlamCommand::execute (const HugeStaticString & input, HugeStaticString & output, InterruptState & state, DebuggerIO * screen) virtual
Execute the command with the given screen.
Implements DebuggerCommand.
Definition at line 46 of file SlamCommand.cc.
References DebuggerIO::drawHorizontalLine(), DebuggerIO::drawString(), DebuggerIO::enableCli(), DebuggerIO::getChar(), Machine::getSerial(), DebuggerIO::getWidth(), KernelElf::globalLookupSymbol(), and KernelElf::instance().
const NormalStaticString SlamCommand::getString () inline virtual
Returns the string representation of this command.
Implements DebuggerCommand.
Definition at line 68 of file SlamCommand.h.
The documentation for this class was generated from the following files:
SlamCommand.h
SlamCommand.cc