The Pedigree Project: ARM926EInterruptManager Class Reference
ARM926EInterruptManager Class Reference
kernel » processor-specifc kernel » ARM926E
#include <InterruptManager.h>
Public Member Functions
virtual bool registerInterruptHandler (size_t interruptNumber, InterruptHandler *handler)
virtual bool registerInterruptHandlerDebugger (size_t interruptNumber, InterruptHandler *handler)
virtual size_t getBreakpointInterruptNumber () PURE
virtual size_t getDebugInterruptNumber () PURE
virtual bool registerSyscallHandler (Service_t Service, SyscallHandler *handler)
virtual uintptr_t syscall (Service_t service, uintptr_t function, uintptr_t p1=0, uintptr_t p2=0, uintptr_t p3=0, uintptr_t p4=0, uintptr_t p5=0)
Static Public Member Functions
static ARM926EInterruptManager & instance ()
static void initialiseProcessor ()
Static Public Member Functions inherited from InterruptManager
static InterruptManager & instance ()
Static Public Member Functions inherited from SyscallManager
static EXPORTED_PUBLIC SyscallManager & instance ()
Private Member Functions
ARM926EInterruptManager ()
ARM926EInterruptManager (const ARM926EInterruptManager &)
ARM926EInterruptManager & operator= (const ARM926EInterruptManager &)
virtual ~ARM926EInterruptManager ()
Static Private Member Functions
static void interrupt (InterruptState &interruptState)
Private Attributes
InterruptHandler * m_Handler [256]
InterruptHandler * m_DbgHandler [256]
SyscallHandler * m_SyscallHandler [serviceEnd]
Static Private Attributes
static ARM926EInterruptManager m_Instance
Additional Inherited Members
Protected Member Functions inherited from InterruptManager
InterruptManager ()
virtual ~InterruptManager ()
Protected Member Functions inherited from SyscallManager
SyscallManager ()
virtual ~SyscallManager ()
Detailed Description
The interrupt handler on mips32 processors
Definition at line 32 of file kernel/core/processor/arm_926e/InterruptManager.h.
Constructor & Destructor Documentation
ARM926EInterruptManager::ARM926EInterruptManager () private
The constructor
Definition at line 204 of file arm_926e/InterruptManager.cc.
Referenced by instance().
ARM926EInterruptManager::ARM926EInterruptManager (const ARM926EInterruptManager &) private
Copy constructor
Note
NOT implemented
ARM926EInterruptManager::~ARM926EInterruptManager () private virtual
The destructor
Definition at line 219 of file arm_926e/InterruptManager.cc.
Referenced by instance().
Member Function Documentation
size_t ARM926EInterruptManager::getBreakpointInterruptNumber () virtual
Get the interrupt number of the breakpoint exception
Returns
the interrupt number of the breakpoint exception
Implements InterruptManager.
Definition at line 110 of file arm_926e/InterruptManager.cc.
Referenced by instance().
size_t ARM926EInterruptManager::getDebugInterruptNumber () virtual
Get the interrupt number of the debug exception
Returns
the interrupt number of the debug exception
Implements InterruptManager.
Definition at line 114 of file arm_926e/InterruptManager.cc.
Referenced by instance().
void ARM926EInterruptManager::initialiseProcessor () static
Initialises this processors IDTR
Note
This should only be called from initialiseProcessor()
Todo:
and some smp/acpi function
Definition at line 146 of file arm_926e/InterruptManager.cc.
Referenced by instance().
static ARM926EInterruptManager& ARM926EInterruptManager::instance () inline static
Get the ARM926EInterruptManager class instance
Returns
instance of the ARM926EInterruptManager class
Definition at line 38 of file kernel/core/processor/arm_926e/InterruptManager.h.
References ARM926EInterruptManager(), getBreakpointInterruptNumber(), getDebugInterruptNumber(), initialiseProcessor(), interrupt(), m_Instance, operator=(), PURE, registerInterruptHandler(), registerInterruptHandlerDebugger(), registerSyscallHandler(), syscall(), and ~ARM926EInterruptManager().
Referenced by SyscallManager::instance(), and InterruptManager::instance().
void ARM926EInterruptManager::interrupt (InterruptState & interruptState) static private
Called when an interrupt was triggered
Parameters
[in] interruptState reference to the usermode/kernel state before the interrupt
Definition at line 151 of file arm_926e/InterruptManager.cc.
References Debugger::instance(), LIKELY, panic(), and Debugger::start().
Referenced by instance().
ARM926EInterruptManager& ARM926EInterruptManager::operator= (const ARM926EInterruptManager &) private
Assignment operator
Note
NOT implemented
Referenced by instance().
bool ARM926EInterruptManager::registerInterruptHandler (size_t nInterruptNumber, InterruptHandler * pHandler) virtual
Register an interrupt handler
Parameters
[in] nInterruptNumber the interrupt's number
[in] pHandler the interrupt handler
Returns
true, if successfully registered, false otherwise
Implements InterruptManager.
Definition at line 79 of file arm_926e/InterruptManager.cc.
References UNLIKELY.
Referenced by instance().
bool ARM926EInterruptManager::registerInterruptHandlerDebugger (size_t nInterruptNumber, InterruptHandler * pHandler) virtual
Register an interrupt handler (for the kernel debugger)
Parameters
[in] nInterruptNumber the interrupt's number
[in] pHandler the interrupt handler
Returns
true, if successfully registered, false otherwise
Implements InterruptManager.
Definition at line 96 of file arm_926e/InterruptManager.cc.
References UNLIKELY.
Referenced by instance().
bool ARM926EInterruptManager::registerSyscallHandler (Service_t Service, SyscallHandler * pHandler) virtual
Register a syscall handler
Parameters
[in] Service the service number you want to register
[in] pHandler the interrupt handler
Returns
true, if successfully registered, false otherwise
Implements SyscallManager.
Definition at line 121 of file arm_926e/InterruptManager.cc.
References UNLIKELY.
Referenced by instance().
uintptr_t ARM926EInterruptManager::syscall (Service_t service, uintptr_t function, uintptr_t p1 = 0, uintptr_t p2 = 0, uintptr_t p3 = 0, uintptr_t p4 = 0, uintptr_t p5 = 0) virtual
Calls a syscall.
Todo:
Software interrupt
Implements SyscallManager.
Definition at line 137 of file arm_926e/InterruptManager.cc.
Referenced by instance().
Member Data Documentation
InterruptHandler* ARM926EInterruptManager::m_DbgHandler[256] private
The debugger interrupt handlers
Definition at line 86 of file kernel/core/processor/arm_926e/InterruptManager.h.
ARM926EInterruptManager ARM926EInterruptManager::m_Instance static private
The instance of the interrupt manager
Definition at line 92 of file kernel/core/processor/arm_926e/InterruptManager.h.
Referenced by instance().
SyscallHandler* ARM926EInterruptManager::m_SyscallHandler[serviceEnd] private
The syscall handlers
Definition at line 89 of file kernel/core/processor/arm_926e/InterruptManager.h.
The documentation for this class was generated from the following files:
kernel/core/processor/arm_926e/InterruptManager.h
arm_926e/InterruptManager.cc