The Pedigree Project: BootIO Class Reference
BootIO Class Reference
#include <BootIO.h>
Public Types
enum Colour {
Black = 0, Blue = 1, Green = 2, Cyan = 3,
Red = 4, Magenta = 5, Orange = 6, LightGrey = 7,
DarkGrey = 8, LightBlue = 9, LightGreen = 10, LightCyan = 11,
LightRed = 12, LightMagenta = 13, Yellow = 14, White = 15
}
Public Member Functions
BootIO () NOTHROW
~BootIO ()
void initialise ()
template<class T >
EXPORTED_PUBLIC void write (T &str, Colour foreColour, Colour backColour)
template<class T >
void write (T &str, Colour foreColour, Colour backColour)
Private Member Functions
void putCharVga (const char c, Colour foreColour, Colour backColour)
void startColour (Serial *pSerial, Colour foreColour, Colour backColour)
void endColour (Serial *pSerial)
Private Attributes
size_t m_CursorX
size_t m_CursorY
Detailed Description
A class which provides extremely simple output to both the Vga class and Serial classes, intended to be used for displaying messages during bootup.
Definition at line 36 of file BootIO.h.
Member Enumeration Documentation
enum BootIO::Colour
Enumeration of all possible foreground and background colours.
Definition at line 42 of file BootIO.h.
Constructor & Destructor Documentation
BootIO::BootIO ()
Constructor. I hope you knew that already.
Definition at line 28 of file BootIO.cc.
BootIO::~BootIO ()
Destructor. Let's hope you knew that too.
Definition at line 32 of file BootIO.cc.
Member Function Documentation
void BootIO::initialise ()
Initialise the BootIO - If we have a VGA device this clears the screen.
Definition at line 36 of file BootIO.cc.
References EXPORTED_PUBLIC, Vga::getNumCols(), Vga::getNumRows(), Machine::getSerial(), Machine::getVga(), Log::instance(), m_CursorX, Vga::pokeBuffer(), Vga::setLargestTextMode(), and write().
template<class T > template EXPORTED_PUBLIC void BootIO::write< HugeStaticString > (T & str, Colour foreColour, Colour backColour)
Write a string out to each output device.
Parameters
str The string to write
foreColour The foreground colour
backColour The background colour
Referenced by StreamingScreenLogger::callback(), and initialise().
Member Data Documentation
size_t BootIO::m_CursorX private
Current cursor position for VGA.
Definition at line 86 of file BootIO.h.
Referenced by initialise().
The documentation for this class was generated from the following files:
BootIO.h
BootIO.cc