The Pedigree Project: MD5 Class Reference
MD5 Class Reference
This class represents the implementation of the md5 message digest algorithm.
#include <md5.h>
Public Member Functions
void Reset ()
Initialization begins an operation, writing a new context.
void Input (unsigned char *input, unsigned int inputLen)
Block update operation. Continues an md5 message-digest operation, processing another message block, and updating the context.
void Result (unsigned char digest[16])
Finalization ends the md5 message-digest operation, writing the the message digest and zeroizing the context.
MD5 ()
default constructor
Private Member Functions
void MD5Transform (unsigned long int state[4], unsigned char block[64])
Basic transformation. Transforms state based on block.
void Encode (unsigned char *output, unsigned long int *input, unsigned int len)
Encodes input data.
void Decode (unsigned long int *output, unsigned char *input, unsigned int len)
Decodes input data into output.
void MD5_memcpy (POINTER output, POINTER input, unsigned int len)
internal memory management
void MD5_memset (POINTER output, int value, unsigned int len)
internal memory management
Private Attributes
unsigned long int state [4]
unsigned long int count [2]
unsigned char buffer [64]
Detailed Description
This class represents the implementation of the md5 message digest algorithm.
Basically the class provides three public member-functions to create a hash: Reset(), Input() and Result().
Definition at line 84 of file system/include/pedigree/kernel/utilities/md5/md5.h.
Member Function Documentation
void MD5::Decode (unsigned long int * output, unsigned char * input, unsigned int len) private
Decodes input data into output.
Parameters
output Decoded data as OUT parameter
input Input data
len The length of the input assuming it is a multiple of 4
Definition at line 266 of file md5.cc.
Referenced by MD5Transform().
void MD5::Encode (unsigned char * output, unsigned long int * input, unsigned int len) private
Encodes input data.
Parameters
output Encoded data as OUT parameter
input Input data
len The length of the input assuming it is a multiple of 4
Definition at line 245 of file md5.cc.
Referenced by Result().
void MD5::Input (unsigned char * input, unsigned int inputLen)
Block update operation. Continues an md5 message-digest operation, processing another message block, and updating the context.
Parameters
input The data to write into the context
inputLen The length of the input data
Definition at line 326 of file md5.cc.
References buffer, count, MD5_memcpy(), MD5Transform(), and state.
Referenced by Result().
void MD5::MD5_memcpy (POINTER output, POINTER input, unsigned int len) private
internal memory management
Parameters
output OUT parameter where POINTER is an unsigned char*
input Data to copy where POINTER is a unsigned char*
len The length of the data
output OUT parameter where POINTER is a unsigned char*
input Data to copy where POINTER is a unsigned char*
len The length of the data
Definition at line 285 of file md5.cc.
Referenced by Input().
void MD5::MD5_memset (POINTER output, int value, unsigned int len) private
internal memory management
Parameters
output OUT parameter where POINTER is an unsigned char*
value Value to fill the memory with
len The length of the data
Definition at line 298 of file md5.cc.
Referenced by MD5Transform().
void MD5::MD5Transform (unsigned long int state[4], unsigned char block[64]) private
Basic transformation. Transforms state based on block.
Parameters
state state to transform
block block to transform
Definition at line 147 of file md5.cc.
References Decode(), and MD5_memset().
Referenced by Input().
void MD5::Result (unsigned char digest[16])
Finalization ends the md5 message-digest operation, writing the the message digest and zeroizing the context.
Parameters
digest This is an OUT parameter which contains the created hash after the method returns
Definition at line 368 of file md5.cc.
References count, Encode(), Input(), and state.
Member Data Documentation
unsigned char MD5::buffer[64] private
input buffer
Definition at line 140 of file system/include/pedigree/kernel/utilities/md5/md5.h.
Referenced by Input().
unsigned long int MD5::count[2] private
number of bits, modulo 2^64 (lsb first)
Definition at line 137 of file system/include/pedigree/kernel/utilities/md5/md5.h.
Referenced by Input(), Reset(), and Result().
unsigned long int MD5::state[4] private
state (ABCD)
Definition at line 134 of file system/include/pedigree/kernel/utilities/md5/md5.h.
Referenced by Input(), Reset(), and Result().
The documentation for this class was generated from the following files:
system/include/pedigree/kernel/utilities/md5/md5.h
md5.cc