The Pedigree Project: Misc
Misc
Porting (system abstraction layer) » OS abstraction layer
Functions
void sys_msleep (u32_t ms)
sys_thread_t sys_thread_new (const char *name, lwip_thread_fn thread, void *arg, int stacksize, int prio)
Detailed Description
Function Documentation
void sys_msleep (u32_t ms)
Sleep for specified number of ms
Sleep for some ms. Timeouts are NOT processed while sleeping.
Parameters
ms number of milliseconds to sleep
Definition at line 112 of file modules/system/lwip/core/sys.c.
References ERR_OK, sys_arch_sem_wait(), sys_sem_free(), and sys_sem_new().
sys_thread_t sys_thread_new (const char * name, lwip_thread_fn thread, void * arg, int stacksize, int prio)
The only thread function: Creates a new thread ATTENTION: although this function returns a value, it MUST NOT FAIL (ports have to assert this!)
Parameters
name human-readable name for the thread (used for debugging purposes)
thread thread-function
arg parameter passed to 'thread'
stacksize stack size in bytes for the new thread (may be ignored by ports)
prio priority of the new thread (may be ignored by ports)
Todo:
stacksize might be important
Definition at line 83 of file sys_arch.cc.
References pocketknife::runConcurrently().
Referenced by slipif_init(), and tcpip_init().