The Pedigree Project: msdos.h File Reference
msdos.h File Reference
#include "pedigree/kernel/processor/types.h"
Classes
struct __attribute__
Macros
#define MSDOS_IDENT_1 0x55
#define MSDOS_IDENT_2 0xAA
#define MSDOS_PARTTAB_START 0x1BE
#define MSDOS_PARTTAB_NUM 0x4
#define MSDOS_EXT_PARTTAB_NUM 0x2
Functions
bool msdosProbeDisk (Disk *pDisk)
bool msdosReadTable (MsdosPartitionInfo *pPartitions, Disk *pDisk)
Detailed Description
Declares functions for probing Disk devices for MS-DOS partition tables.
Definition in file msdos.h.
Function Documentation
bool msdosProbeDisk (Disk * pDisk)
Attempts to find a MS-DOS partition table on pDisk. If found, new Partition objects are created and added as children of pDisk.
Returns
true if a ms-dos partition table was found.
Definition at line 457 of file msdos.cc.
References Disk::getName(), msdosReadTable(), NOTICE, Disk::read(), and WARNING.
bool msdosReadTable (MsdosPartitionInfo * pPartitions, Disk * pDisk)
Given a partition table, read and parse the contents.
Definition at line 400 of file msdos.cc.
References Disk::read(), and WARNING.
Referenced by msdosProbeDisk().