The Pedigree Project: HidUtils Namespace Reference
HidUtils Namespace Reference
Various utility functions used in HID.
Functions
uint64_t getBufferField (uint8_t *pBuffer, size_t nStart, size_t nLength)
Retrieves a field in a buffer.
void fixNegativeMinimum (int64_t &nMin, int64_t nMax)
Converts.
void fixNegativeValue (int64_t nMin, int64_t nMax, int64_t &nValue)
Converts.
void sendInputToManager (HidDeviceType deviceType, uint16_t nUsagePage, uint16_t nUsage, int64_t nRelativeValue)
Sends the input to the right handler in HidInputManager or InputManager.
Detailed Description
Various utility functions used in HID.
Function Documentation
void HidUtils::fixNegativeMinimum (int64_t & nMin, int64_t nMax)
Converts.
Parameters
nMin to a negative value, if it has the signed bit set
Definition at line 42 of file HidUtils.cc.
Referenced by HidReport::parseDescriptor().
void HidUtils::fixNegativeValue (int64_t nMin, int64_t nMax, int64_t & nValue)
Converts.
Parameters
nValue to a negative value, if it has the signed bit set
Definition at line 59 of file HidUtils.cc.
Referenced by HidReport::InputBlock::feedInput().
void HidUtils::sendInputToManager (HidDeviceType deviceType, uint16_t nUsagePage, uint16_t nUsage, int64_t nRelativeValue)
Sends the input to the right handler in HidInputManager or InputManager.
Todo:
Matt, fix the damn input manager!!!
Definition at line 83 of file HidUtils.cc.
References HidInputManager::instance(), InputManager::instance(), InputManager::joystickUpdate(), HidInputManager::keyDown(), HidInputManager::keyUp(), and InputManager::mouseUpdate().
Referenced by HidReport::InputBlock::feedInput().