The Pedigree Project: pbuf.c File Reference
pbuf.c File Reference
#include "lwip/opt.h"
#include "lwip/stats.h"
#include "lwip/def.h"
#include "lwip/mem.h"
#include "lwip/memp.h"
#include "lwip/pbuf.h"
#include "lwip/sys.h"
#include <string.h>
Macros
#define SIZEOF_STRUCT_PBUF LWIP_MEM_ALIGN_SIZE(sizeof(struct pbuf))
#define PBUF_POOL_BUFSIZE_ALIGNED LWIP_MEM_ALIGN_SIZE(PBUF_POOL_BUFSIZE)
#define PBUF_POOL_IS_EMPTY()
Functions
struct pbuf * pbuf_alloc (pbuf_layer layer, u16_t length, pbuf_type type)
void pbuf_realloc (struct pbuf *p, u16_t new_len)
u8_t pbuf_header (struct pbuf *p, s16_t header_size_increment)
u8_t pbuf_header_force (struct pbuf *p, s16_t header_size_increment)
u8_t pbuf_free (struct pbuf *p)
u16_t pbuf_clen (const struct pbuf *p)
void pbuf_ref (struct pbuf *p)
void pbuf_cat (struct pbuf *h, struct pbuf *t)
void pbuf_chain (struct pbuf *h, struct pbuf *t)
struct pbuf * pbuf_dechain (struct pbuf *p)
err_t pbuf_copy (struct pbuf *p_to, const struct pbuf *p_from)
u16_t pbuf_copy_partial (const struct pbuf *buf, void *dataptr, u16_t len, u16_t offset)
struct pbuf * pbuf_skip (struct pbuf *in, u16_t in_offset, u16_t *out_offset)
err_t pbuf_take (struct pbuf *buf, const void *dataptr, u16_t len)
err_t pbuf_take_at (struct pbuf *buf, const void *dataptr, u16_t len, u16_t offset)
struct pbuf * pbuf_coalesce (struct pbuf *p, pbuf_layer layer)
u8_t pbuf_get_at (const struct pbuf *p, u16_t offset)
int pbuf_try_get_at (const struct pbuf *p, u16_t offset)
void pbuf_put_at (struct pbuf *p, u16_t offset, u8_t data)
u16_t pbuf_memcmp (const struct pbuf *p, u16_t offset, const void *s2, u16_t n)
u16_t pbuf_memfind (const struct pbuf *p, const void *mem, u16_t mem_len, u16_t start_offset)
u16_t pbuf_strstr (const struct pbuf *p, const char *substr)
Detailed Description
Packet buffer management
Definition in file pbuf.c.
Function Documentation
u16_t pbuf_clen (const struct pbuf * p)
Count number of pbufs in a chain
Parameters
p first pbuf of chain
Returns
the number of pbufs in a chain
Definition at line 819 of file pbuf.c.
References pbuf::next.
Referenced by netif_set_link_down().
struct pbuf* pbuf_dechain (struct pbuf * p)
Dechains the first pbuf from its succeeding pbufs in the chain.
Makes p->tot_len field equal to p->len.
Parameters
p pbuf to dechain
Returns
remainder of the pbuf chain, or NULL if it was de-allocated.
Note
May not be called on a packet queue.
Definition at line 918 of file pbuf.c.
References pbuf::len, LWIP_DBG_TRACE, LWIP_DEBUGF, pbuf::next, PBUF_DEBUG, pbuf_free(), and pbuf::tot_len.
u8_t pbuf_header (struct pbuf * p, s16_t header_size_increment)
Adjusts the payload pointer to hide or reveal headers in the payload.
Adjusts the ->payload pointer so that space for a header (dis)appears in the pbuf payload.
The ->payload, ->tot_len and ->len fields are adjusted.
Parameters
p pbuf to change the header size.
header_size_increment Number of bytes to increment header size which increases the size of the pbuf. New space is on the front. (Using a negative value decreases the header size.) If hdr_size_inc is 0, this function does nothing and returns successful.
PBUF_ROM and PBUF_REF type buffers cannot have their sizes increased, so the call will fail. A check is made that the increase in header size does not move the payload pointer in front of the start of the buffer.
Returns
non-zero on failure, zero on success.
Definition at line 684 of file pbuf.c.
u8_t pbuf_header_force (struct pbuf * p, s16_t header_size_increment)
Same as pbuf_header but does not check if 'header_size > 0' is allowed. This is used internally only, to allow PBUF_REF for RX.
Definition at line 694 of file pbuf.c.
u16_t pbuf_strstr (const struct pbuf * p, const char * substr)
Find occurrence of substr with length substr_len in pbuf p, start at offset start_offset WARNING: in contrast to strstr(), this one does not stop at the first \0 in the pbuf/source string!
Parameters
p pbuf to search, maximum length is 0xFFFE since 0xFFFF is used as return value 'not found'
substr string to search for in p, maximum length is 0xFFFE
Returns
0xFFFF if substr was not found in p or the index where it was found
Definition at line 1450 of file pbuf.c.
References pbuf_memfind(), and pbuf::tot_len.