The Pedigree Project: HidReport::InputBlock Struct Reference
HidReport::InputBlock Struct Reference
Structure representing an Input block whitin a Collection.
Public Types
enum { Constant, Absolute, Relative, Array }
The type of the input block.
Public Member Functions
void feedInput (uint8_t *pBuffer, uint8_t *pOldBuffer, size_t nBufferSize, size_t &nBitOffset, HidDeviceType deviceType)
Feeds input to this block.
Public Attributes
enum HidReport::InputBlock:: { ... } type
The type of the input block.
LocalState state
The local state of the input block.
Detailed Description
Structure representing an Input block whitin a Collection.
Definition at line 121 of file HidReport.h.
Member Function Documentation
void HidReport::InputBlock::feedInput (uint8_t * pBuffer, uint8_t * pOldBuffer, size_t nBufferSize, size_t & nBitOffset, HidDeviceType deviceType)
Feeds input to this block.
Todo:
Do implement support
Note
This is harder that just checking the first byte
Proper support for old buffer data is needed, too
Definition at line 351 of file HidReport.cc.
References HidUtils::fixNegativeValue(), HidUtils::getBufferField(), HidUtils::sendInputToManager(), and WARNING.
Referenced by HidReport::Collection::feedInput().
The documentation for this struct was generated from the following files:
HidReport.h
HidReport.cc