The Pedigree Project: Log::LogEntry Struct Reference
Log::LogEntry Struct Reference
#include <Log.h>
Public Member Functions
LogEntry ()
LogEntry & operator<< (const char *)
LogEntry & operator<< (const String &)
LogEntry & operator<< (const StringView &)
LogEntry & operator<< (char *append_str)
LogEntry & operator<< (bool b)
template<class T >
LogEntry & operator<< (T *p)
template<class T >
LogEntry & operator<< (T n)
LogEntry & operator<< (SeverityLevel level)
LogEntry & operator<< (NumberType type)
template<class T >
Log::LogEntry & operator<< (T n)
Public Attributes
unsigned int timestamp
SeverityLevel severity
StaticString< LOG_LENGTH > str
NumberType numberType
Detailed Description
Stores an entry in the log.
Parameters
[in] T type of the log's text
Definition at line 235 of file Log.h.
Constructor & Destructor Documentation
Log::LogEntry::LogEntry ()
Constructor does nothing
Definition at line 255 of file Log.cc.
References StaticString< N >::disableHashing(), and str.
Member Function Documentation
Log::LogEntry & Log::LogEntry::operator<< (const char * s)
Adds an entry to the log.
Parameters
[in] str the null-terminated ASCII string that should be added
Definition at line 260 of file Log.cc.
References str.
Referenced by operator<<().
Log::LogEntry & Log::LogEntry::operator<< (char * append_str)
Adds an entry to the log
Parameters
[in] str the null-terminated ASCII string that should be added
Definition at line 278 of file Log.cc.
Log::LogEntry & Log::LogEntry::operator<< (bool b)
Adds an entry to the log
Parameters
[in] b boolean value
Definition at line 283 of file Log.cc.
References Hex, numberType, Oct, operator<<(), and str.
template<class T > LogEntry& Log::LogEntry::operator<< (T * p) inline
Adds an entry to the log
Parameters
[in] p pointer value
Definition at line 265 of file Log.h.
References Log::operator<<().
template<class T > LogEntry& Log::LogEntry::operator<< (T n)
Adds an entry to the log (integer type)
Parameters
[in] n the number
Log::LogEntry & Log::LogEntry::operator<< (SeverityLevel level)
Starts an entry in the log.
Definition at line 315 of file Log.cc.
References Timer::getTickCount(), Machine::getTimer(), operator<<(), severity, str, and timestamp.
Log::LogEntry & Log::LogEntry::operator<< (NumberType type)
Changes the number type between hex and decimal.
Definition at line 309 of file Log.cc.
References numberType.
Member Data Documentation
NumberType Log::LogEntry::numberType
The number type mode that we are in.
Definition at line 247 of file Log.h.
Referenced by operator<<().
SeverityLevel Log::LogEntry::severity
The severity level of this entry.
Definition at line 243 of file Log.h.
Referenced by LogViewer::execute(), Log::flushEntry(), and operator<<().
StaticString<LOG_LENGTH> Log::LogEntry::str
The actual entry text.
Definition at line 245 of file Log.h.
Referenced by LogViewer::execute(), Log::flushEntry(), LogEntry(), and operator<<().
unsigned int Log::LogEntry::timestamp
The time (since boot) that this log entry was added, in ticks.
Definition at line 241 of file Log.h.
Referenced by LogViewer::execute(), and operator<<().
The documentation for this struct was generated from the following files:
Log.h
Log.cc