The Pedigree Project: HidReport::Collection Struct Reference
HidReport::Collection Struct Reference
Structure representing a Collection whitin a report.
Classes
struct Child
Public Types
enum ChildType { CollectionChild, InputBlockChild }
Public Member Functions
void feedInput (uint8_t *pBuffer, uint8_t *pOldBuffer, size_t nBufferSize, size_t &nBitOffset)
HidDeviceType guessInputDevice ()
Public Attributes
Vector< Child * > childs
All the childs in this collection.
Collection * pParent
Our parent.
LocalState state
The local state of the collection.
Detailed Description
Structure representing a Collection whitin a report.
Definition at line 142 of file HidReport.h.
Member Function Documentation
void HidReport::Collection::feedInput (uint8_t * pBuffer, uint8_t * pOldBuffer, size_t nBufferSize, size_t & nBitOffset)
Feeds input to this collection (will get forwarded to the lowest collection)
Definition at line 302 of file HidReport.cc.
References HidReport::InputBlock::feedInput(), and feedInput().
Referenced by HidReport::feedInput(), and feedInput().
HidDeviceType HidReport::Collection::guessInputDevice ()
Guesses from which type of device the input associated with this collection comes from
Definition at line 324 of file HidReport.cc.
References HidReport::LocalState::getUsageByIndex(), pParent, and state.
The documentation for this struct was generated from the following files:
HidReport.h
HidReport.cc