# x86-64 Mach-O hosted kernel for Apple silicon development hosts. The kernel
# runs through Rosetta while its Pedigree modules remain x86-64 ELF objects.
set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_OSX_ARCHITECTURES x86_64 CACHE STRING "" FORCE)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
get_filename_component(
    PEDIGREE_SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)

find_program(PEDIGREE_HOST_C_COMPILER clang REQUIRED)
find_program(PEDIGREE_HOST_CXX_COMPILER clang++ REQUIRED)
find_program(PEDIGREE_HOST_STRIP strip REQUIRED)

set(CMAKE_C_COMPILER ${PEDIGREE_HOST_C_COMPILER})
set(CMAKE_CXX_COMPILER ${PEDIGREE_HOST_CXX_COMPILER})
set(CMAKE_ASM_COMPILER ${PEDIGREE_HOST_C_COMPILER})
set(CMAKE_STRIP ${PEDIGREE_HOST_STRIP})

set(PEDIGREE_C_COMPILER
    ${PEDIGREE_SOURCE_ROOT}/compilers/dir/bin/x86_64-pedigree-gcc)
set(PEDIGREE_CXX_COMPILER
    ${PEDIGREE_SOURCE_ROOT}/compilers/dir/bin/x86_64-pedigree-g++)
set(PEDIGREE_MODULE_OBJCOPY
    ${PEDIGREE_SOURCE_ROOT}/compilers/dir/bin/x86_64-pedigree-objcopy)
set(PEDIGREE_MODULE_STRIP
    ${PEDIGREE_SOURCE_ROOT}/compilers/dir/bin/x86_64-pedigree-strip)

set(TARGET_SUPPORTS_SHARED_LIBS TRUE)

set(PEDIGREE_COMPILER_TARGET x86_64-pedigree)
set(PEDIGREE_ARCH_TARGET HOSTED)
set(PEDIGREE_LINKERSCRIPT "")
set(PEDIGREE_ARCHDIR hosted)
set(PEDIGREE_MACHDIR hosted)
set(PEDIGREE_LINKERDIR hosted)
set(PEDIGREE_DRIVERDIR hosted)
set(PEDIGREE_ASMDIR amd64)
set(PEDIGREE_MUSLARCH amd64)
set(PEDIGREE_MUSL_ARCH_TARGET HOSTED)
set(PEDIGREE_HOSTED TRUE)
set(PEDIGREE_HOSTED_DARWIN TRUE)
set(PEDIGREE_NASM_FORMAT macho64)
set(PEDIGREE_NASM_GLOBAL_PREFIX "_")

set(PEDIGREE_TARGET_LIVECD FALSE)
set(GRUB FALSE)
set(PEDIGREE_BUILD_USER_DIR FALSE)
set(PEDIGREE_MACHINE_HASPS2 FALSE)
set(PEDIGREE_MACHINE_HASPCI FALSE)

add_definitions(
    -DMACH_HOSTED=1 -DBITS_64=1 -DBITS_32=0 -DTHREADS=1
    -DKERNEL_STANDALONE=1 -DMULTIBOOT=1 -DTARGET_IS_LITTLE_ENDIAN=1
    -DKERNEL_NEEDS_ADDRESS_SPACE_SWITCH=0 -DKERNEL_PROCESSOR_NO_PORT_IO=1
    -DTARGET_HAS_NO_ATOMICS=0 -DSYSTEM_REQUIRES_ATOMIC_CONTEXT_SWITCH=1
    -DPEDIGREE_HOSTED_DARWIN=1 -D_XOPEN_SOURCE=700 -D_DARWIN_C_SOURCE=1)

add_compile_options(
    -include
    ${PEDIGREE_SOURCE_ROOT}/src/system/include/pedigree/kernel/processor/hosted/DarwinAbi.h)

set(LIBRT "")
