set(CMAKE_SYSTEM_NAME Pedigree)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR armv7)

get_filename_component(
    PEDIGREE_SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
list(PREPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}")
set(PEDIGREE_TOOLCHAIN_ROOT
    "${PEDIGREE_SOURCE_ROOT}/pedigree-compiler-15.3.0-r2" CACHE PATH
    "Pedigree cross-toolchain installation root")
if (NOT DEFINED PEDIGREE_TARGET_SYSROOT)
    set(PEDIGREE_TARGET_SYSROOT
        "${PEDIGREE_SOURCE_ROOT}/scripts/alpine/build/armv7/sysroot")
endif ()
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    PEDIGREE_TOOLCHAIN_ROOT PEDIGREE_TARGET_SYSROOT)

set(PEDIGREE_TOOLCHAIN_TRIPLE armv7-alpine-linux-musleabihf)
set(PEDIGREE_TOOLCHAIN_BIN "${PEDIGREE_TOOLCHAIN_ROOT}/bin")
set(PEDIGREE_C_COMPILER "${PEDIGREE_TOOLCHAIN_BIN}/${PEDIGREE_TOOLCHAIN_TRIPLE}-gcc")
set(PEDIGREE_CXX_COMPILER "${PEDIGREE_TOOLCHAIN_BIN}/${PEDIGREE_TOOLCHAIN_TRIPLE}-g++")
set(CMAKE_ADDR2LINE "${PEDIGREE_TOOLCHAIN_BIN}/${PEDIGREE_TOOLCHAIN_TRIPLE}-addr2line" CACHE FILEPATH "" FORCE)
set(CMAKE_AR "${PEDIGREE_TOOLCHAIN_BIN}/${PEDIGREE_TOOLCHAIN_TRIPLE}-ar" CACHE FILEPATH "" FORCE)
set(CMAKE_ASM_COMPILER "${PEDIGREE_C_COMPILER}" CACHE FILEPATH "" FORCE)
set(CMAKE_C_COMPILER_AR "${PEDIGREE_TOOLCHAIN_BIN}/${PEDIGREE_TOOLCHAIN_TRIPLE}-gcc-ar" CACHE FILEPATH "" FORCE)
set(CMAKE_C_COMPILER_RANLIB "${PEDIGREE_TOOLCHAIN_BIN}/${PEDIGREE_TOOLCHAIN_TRIPLE}-gcc-ranlib" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER_AR "${PEDIGREE_TOOLCHAIN_BIN}/${PEDIGREE_TOOLCHAIN_TRIPLE}-gcc-ar" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER_RANLIB "${PEDIGREE_TOOLCHAIN_BIN}/${PEDIGREE_TOOLCHAIN_TRIPLE}-gcc-ranlib" CACHE FILEPATH "" FORCE)
set(CMAKE_LINKER "${PEDIGREE_TOOLCHAIN_BIN}/${PEDIGREE_TOOLCHAIN_TRIPLE}-ld" CACHE FILEPATH "" FORCE)
set(CMAKE_NM "${PEDIGREE_TOOLCHAIN_BIN}/${PEDIGREE_TOOLCHAIN_TRIPLE}-nm" CACHE FILEPATH "" FORCE)
set(CMAKE_OBJCOPY "${PEDIGREE_TOOLCHAIN_BIN}/${PEDIGREE_TOOLCHAIN_TRIPLE}-objcopy" CACHE FILEPATH "" FORCE)
set(CMAKE_OBJDUMP "${PEDIGREE_TOOLCHAIN_BIN}/${PEDIGREE_TOOLCHAIN_TRIPLE}-objdump" CACHE FILEPATH "" FORCE)
set(CMAKE_RANLIB "${PEDIGREE_TOOLCHAIN_BIN}/${PEDIGREE_TOOLCHAIN_TRIPLE}-ranlib" CACHE FILEPATH "" FORCE)
set(CMAKE_READELF "${PEDIGREE_TOOLCHAIN_BIN}/${PEDIGREE_TOOLCHAIN_TRIPLE}-readelf" CACHE FILEPATH "" FORCE)
set(CMAKE_STRIP "${PEDIGREE_TOOLCHAIN_BIN}/${PEDIGREE_TOOLCHAIN_TRIPLE}-strip" CACHE FILEPATH "" FORCE)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_C_COMPILER "${PEDIGREE_C_COMPILER}")
set(CMAKE_CXX_COMPILER "${PEDIGREE_CXX_COMPILER}")
set(CMAKE_SYSROOT "${PEDIGREE_TARGET_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH
    "${PEDIGREE_TOOLCHAIN_ROOT}"
    "${PEDIGREE_TOOLCHAIN_BIN}"
    "${PEDIGREE_TARGET_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

include("${CMAKE_CURRENT_LIST_DIR}/pedigree_armv7_target.cmake")
set(PEDIGREE_TARGET_LIVECD FALSE)
set(GRUB FALSE)
