list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    PEDIGREE_TOOLCHAIN_ROOT PEDIGREE_TARGET_SYSROOT)

set(PEDIGREE_TOOLCHAIN_BIN "${PEDIGREE_TOOLCHAIN_ROOT}/bin")
set(PEDIGREE_C_COMPILER "${PEDIGREE_TOOLCHAIN_BIN}/${PEDIGREE_TOOLCHAIN_TRIPLE}-gcc")
set(PEDIGREE_CXX_COMPILER "${PEDIGREE_TOOLCHAIN_BIN}/${PEDIGREE_TOOLCHAIN_TRIPLE}-g++")

# Reused build directories must not retain binutils from an old prefix.
foreach (tool ADDR2LINE AR NM OBJCOPY OBJDUMP RANLIB READELF STRIP)
    string(TOLOWER "${tool}" executable)
    set(CMAKE_${tool} "${PEDIGREE_TOOLCHAIN_BIN}/${PEDIGREE_TOOLCHAIN_TRIPLE}-${executable}"
        CACHE FILEPATH "" FORCE)
endforeach ()
set(CMAKE_LINKER "${PEDIGREE_TOOLCHAIN_BIN}/${PEDIGREE_TOOLCHAIN_TRIPLE}-ld"
    CACHE FILEPATH "" FORCE)
foreach (language ASM C CXX)
    set(CMAKE_${language}_COMPILER_AR "${PEDIGREE_TOOLCHAIN_BIN}/${PEDIGREE_TOOLCHAIN_TRIPLE}-gcc-ar"
        CACHE FILEPATH "" FORCE)
    set(CMAKE_${language}_COMPILER_RANLIB "${PEDIGREE_TOOLCHAIN_BIN}/${PEDIGREE_TOOLCHAIN_TRIPLE}-gcc-ranlib"
        CACHE FILEPATH "" FORCE)
endforeach ()
if (NOT DEFINED CMAKE_ASM_COMPILER)
    set(CMAKE_ASM_COMPILER "${PEDIGREE_C_COMPILER}" CACHE FILEPATH "" FORCE)
endif ()
if (NOT DEFINED CMAKE_ASM_NASM_COMPILER)
    set(CMAKE_ASM_NASM_COMPILER "${PEDIGREE_TOOLCHAIN_BIN}/nasm" CACHE FILEPATH "" FORCE)
endif ()

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_C_COMPILER "${PEDIGREE_C_COMPILER}")
set(CMAKE_CXX_COMPILER "${PEDIGREE_CXX_COMPILER}")
set(CMAKE_SYSROOT "${PEDIGREE_TARGET_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH
    "${PEDIGREE_TOOLCHAIN_ROOT}"
    "${PEDIGREE_TOOLCHAIN_BIN}"
    "${PEDIGREE_TARGET_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
