set(CMAKE_SYSTEM_NAME Pedigree)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR arm64)

get_filename_component(
    PEDIGREE_SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
list(PREPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}")
set(PEDIGREE_TOOLCHAIN_ROOT
    "${PEDIGREE_SOURCE_ROOT}/compilers/dir" CACHE PATH
    "Pedigree cross-toolchain installation root")
if (NOT DEFINED PEDIGREE_TARGET_SYSROOT)
    set(PEDIGREE_TARGET_SYSROOT
        "${PEDIGREE_TOOLCHAIN_ROOT}/arm64-elf")
endif ()
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    PEDIGREE_TOOLCHAIN_ROOT PEDIGREE_TARGET_SYSROOT)

set(PEDIGREE_C_COMPILER ${PEDIGREE_TOOLCHAIN_ROOT}/bin/arm64-elf-gcc)
set(PEDIGREE_CXX_COMPILER ${PEDIGREE_TOOLCHAIN_ROOT}/bin/arm64-elf-g++)

# Reused build directories can otherwise retain binutils paths from the
# previously selected compiler prefix.
set(PEDIGREE_TOOLCHAIN_BIN "${PEDIGREE_TOOLCHAIN_ROOT}/bin")
set(CMAKE_ADDR2LINE "${PEDIGREE_TOOLCHAIN_BIN}/arm64-elf-addr2line" CACHE FILEPATH "" FORCE)
set(CMAKE_AR "${PEDIGREE_TOOLCHAIN_BIN}/arm64-elf-ar" CACHE FILEPATH "" FORCE)
if (NOT DEFINED CMAKE_ASM_COMPILER)
    set(CMAKE_ASM_COMPILER "${PEDIGREE_TOOLCHAIN_BIN}/arm64-elf-gcc" CACHE FILEPATH "" FORCE)
endif ()
set(CMAKE_ASM_COMPILER_AR "${PEDIGREE_TOOLCHAIN_BIN}/arm64-elf-gcc-ar" CACHE FILEPATH "" FORCE)
set(CMAKE_ASM_COMPILER_RANLIB "${PEDIGREE_TOOLCHAIN_BIN}/arm64-elf-gcc-ranlib" CACHE FILEPATH "" FORCE)
if (NOT DEFINED CMAKE_ASM_NASM_COMPILER)
    set(CMAKE_ASM_NASM_COMPILER "${PEDIGREE_TOOLCHAIN_BIN}/nasm" CACHE FILEPATH "" FORCE)
endif ()
set(CMAKE_C_COMPILER_AR "${PEDIGREE_TOOLCHAIN_BIN}/arm64-elf-gcc-ar" CACHE FILEPATH "" FORCE)
set(CMAKE_C_COMPILER_RANLIB "${PEDIGREE_TOOLCHAIN_BIN}/arm64-elf-gcc-ranlib" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER_AR "${PEDIGREE_TOOLCHAIN_BIN}/arm64-elf-gcc-ar" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER_RANLIB "${PEDIGREE_TOOLCHAIN_BIN}/arm64-elf-gcc-ranlib" CACHE FILEPATH "" FORCE)
set(CMAKE_LINKER "${PEDIGREE_TOOLCHAIN_BIN}/arm64-elf-ld" CACHE FILEPATH "" FORCE)
set(CMAKE_NM "${PEDIGREE_TOOLCHAIN_BIN}/arm64-elf-nm" CACHE FILEPATH "" FORCE)
set(CMAKE_OBJCOPY "${PEDIGREE_TOOLCHAIN_BIN}/arm64-elf-objcopy" CACHE FILEPATH "" FORCE)
set(CMAKE_OBJDUMP "${PEDIGREE_TOOLCHAIN_BIN}/arm64-elf-objdump" CACHE FILEPATH "" FORCE)
set(CMAKE_RANLIB "${PEDIGREE_TOOLCHAIN_BIN}/arm64-elf-ranlib" CACHE FILEPATH "" FORCE)
set(CMAKE_READELF "${PEDIGREE_TOOLCHAIN_BIN}/arm64-elf-readelf" CACHE FILEPATH "" FORCE)
set(CMAKE_STRIP "${PEDIGREE_TOOLCHAIN_BIN}/arm64-elf-strip" CACHE FILEPATH "" FORCE)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_C_COMPILER ${PEDIGREE_C_COMPILER})
set(CMAKE_CXX_COMPILER ${PEDIGREE_CXX_COMPILER})

set(CMAKE_SYSROOT "${PEDIGREE_TARGET_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH
    ${PEDIGREE_TOOLCHAIN_ROOT}
    ${PEDIGREE_TOOLCHAIN_ROOT}/bin
    ${PEDIGREE_TARGET_SYSROOT})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

include("${CMAKE_CURRENT_LIST_DIR}/pedigree_arm64_target.cmake")

set(PEDIGREE_TARGET_LIVECD FALSE)
set(GRUB FALSE)
