include_guard(GLOBAL)

set(PEDIGREE_COMPILER_TARGET armv7-alpine-linux-musleabihf)
set(PEDIGREE_ARCH_TARGET ARMV7)
set(PEDIGREE_TARGET_PAGE_SIZE 4096 CACHE STRING
    "Pedigree base virtual-memory page size in bytes.")
set(PEDIGREE_LINKERSCRIPT
    "${CMAKE_SOURCE_DIR}/src/system/kernel/core/processor/armv7/kernel.ld")
set(PEDIGREE_ARCHDIR "armv7")
set(PEDIGREE_MACHDIR "mach_virt")
set(PEDIGREE_LINKERDIR "armv7")
set(PEDIGREE_DRIVERDIR "armv7")
set(PEDIGREE_ASMDIR "armv7")
set(PEDIGREE_MUSLARCH "armv7")
set(PEDIGREE_MUSL_ARCH_TARGET ${PEDIGREE_ARCH_TARGET})

if (NOT DEFINED PEDIGREE_BUILD_USER_DIR)
    set(PEDIGREE_BUILD_USER_DIR FALSE)
endif ()

set(PEDIGREE_MACHINE_HASPS2 FALSE)
set(PEDIGREE_MACHINE_HASPCI TRUE)

if (NOT CMAKE_SCRIPT_MODE_FILE)
    add_definitions(
        -DARMV7=1 -DMACH_VIRT=1 -DBITS_64=0 -DBITS_32=1
        -DTHREADS=1 -DKERNEL_STANDALONE=1
        -DTARGET_IS_LITTLE_ENDIAN=1
        -DKERNEL_PROCESSOR_NO_PORT_IO=1)
endif ()
