'''
Copyright (c) 2008-2014, Pedigree Developers

Please see the CONTRIB file in the root of the source tree for a full
list of contributors.

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
'''

import os

import buildutils.fs
import buildutils.modules

Import(['env'])

env_clone = env.Clone()

builddir = env["PEDIGREE_BUILD_BASE"]
kerneldir = env["PEDIGREE_BUILD_KERNEL"]
moduledir = env["PEDIGREE_BUILD_MODULES"]
subsysdir = env["PEDIGREE_BUILD_SUBSYS"]

native_userlib_objname = subsysdir.File('native.o')

env.Alias("subsys", native_userlib_objname)

files = [
    Glob("*.cc")
]

# To include a new directory for includes, just add it to the list
include_dirs = [
    './include',
    '#src',
    '#src/modules',
    '#src/system/include',
    '#src/modules/system',
    builddir.Dir('musl').Dir('include'),
    '#images/local/include',
    '#images/local/include/native',
    '.'
]

env_clone['CPPPATH'] = include_dirs
env_clone['LIBS'] = ['gcc']

env_clone.MergeFlags({
    'TARGET_CPPDEFINES': ['_POSIX_SOURCE', '_POSIX_C_SOURCE=200112L', '_XOPEN_SOURCE=600'],
    'TARGET_CCFLAGS': ['-Wno-undef', '-Wno-parentheses'],
})

final_output = native_userlib_objname
native_userlib_objname = '%s.debug' % native_userlib_objname

buildutils.modules.buildModule(env_clone, final_output, native_userlib_objname,
                               files)
