/*
 * Copyright (c) 2008-2014, Pedigree Developers
 *
 * Please see the CONTRIB file in the root of the source tree for a full
 * list of contributors.
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef SYSCALL_NUMBERS_H
#define SYSCALL_NUMBERS_H

#define POSIX_OPEN 1
#define POSIX_WRITE 2
#define POSIX_READ 3
#define POSIX_CLOSE 4
#define POSIX_SBRK 5
#define POSIX_FORK 6
#define POSIX_EXECVE 7
#define POSIX_WAITPID 8
#define POSIX_EXIT 9
#define POSIX_OPENDIR 10
#define POSIX_READDIR 11
#define POSIX_REWINDDIR 12
#define POSIX_CLOSEDIR 13
#define POSIX_TCGETATTR 14
#define POSIX_TCSETATTR 15
#define POSIX_IOCTL 16
#define POSIX_STAT 17
#define POSIX_FSTAT 18
#define POSIX_GETPID 19
#define POSIX_CHDIR 20
#define POSIX_SELECT 21
#define POSIX_LSEEK 22

#define POSIX_SOCKET 23
#define POSIX_CONNECT 24
#define POSIX_SEND 25
#define POSIX_RECV 26
#define POSIX_BIND 27
#define POSIX_LISTEN 28
#define POSIX_ACCEPT 29
#define POSIX_RECVFROM 30
#define POSIX_SENDTO 31

#define POSIX_GETTIMEOFDAY 32
#define POSIX_DUP 33
#define POSIX_DUP2 34
#define POSIX_LSTAT 35
#define POSIX_UNLINK 36
#define POSIX_SYMLINK 1000

#define POSIX_FCNTL 39
#define POSIX_PIPE 40

#define POSIX_MKDIR 41
#define POSIX_GETPWENT 42
#define POSIX_GETPWNAM 43
#define POSIX_GETUID 44
#define POSIX_GETGID 45

#define POSIX_SIGACTION 46
#define POSIX_SIGNAL 47
#define POSIX_RAISE 48
#define POSIX_KILL 49
#define POSIX_SIGPROCMASK 50

#define POSIX_ALARM 51
#define POSIX_SLEEP 52

#define POSIX_POLL 56

#define POSIX_RENAME 57

#define POSIX_GETCWD 58

#define POSIX_READLINK 59
#define POSIX_LINK 60

#define POSIX_ISATTY 61

#define POSIX_MMAP 62
#define POSIX_MUNMAP 63

#define POSIX_SHUTDOWN 64

#define POSIX_ACCESS 65

#define POSIX_SETSID 66
#define POSIX_SETPGID 67
#define POSIX_GETPGRP 68

#define POSIX_SIGALTSTACK 69

#define POSIX_SEM_CLOSE 70
#define POSIX_SEM_DESTROY 71
#define POSIX_SEM_GETVALUE 72
#define POSIX_SEM_INIT 73
#define POSIX_SEM_OPEN 74
#define POSIX_SEM_POST 75
#define POSIX_SEM_TIMEWAIT 76
#define POSIX_SEM_TRYWAIT 77
#define POSIX_SEM_UNLINK 78
#define POSIX_SEM_WAIT 79

#define POSIX_PTHREAD_RETURN 80
#define POSIX_PTHREAD_ENTER 81
#define POSIX_PTHREAD_CREATE 82
#define POSIX_PTHREAD_JOIN 83
#define POSIX_PTHREAD_DETACH 84
#define POSIX_PTHREAD_SELF 85
#define POSIX_PTHREAD_KILL 86
#define POSIX_PTHREAD_SIGMASK 87

#define POSIX_PTHREAD_MUTEX_INIT 88
#define POSIX_PTHREAD_MUTEX_DESTROY 89
#define POSIX_PTHREAD_MUTEX_LOCK 90
#define POSIX_PTHREAD_MUTEX_TRYLOCK 91
#define POSIX_PTHREAD_MUTEX_UNLOCK 92

#define POSIX_PTHREAD_KEY_CREATE 93
#define POSIX_PTHREAD_KEY_DELETE 94
#define POSIX_PTHREAD_SETSPECIFIC 95
#define POSIX_PTHREAD_GETSPECIFIC 96
#define POSIX_PTHREAD_KEY_DESTRUCTOR 97

#define POSIX_SYSLOG 98

#define POSIX_FTRUNCATE 99

#define POSIX_STUBBED 100

#define PEDIGREE_SIGRET 101
#define PEDIGREE_INIT_SIGRET 102

#define POSIX_SCHED_YIELD 103

#define POSIX_PEDIGREE_THRWAKEUP 104
#define POSIX_PEDIGREE_THRSLEEP 105

#define POSIX_NANOSLEEP 106
#define POSIX_CLOCK_GETTIME 107

#define POSIX_GETEUID 108
#define POSIX_GETEGID 109
#define POSIX_SETEUID 110
#define POSIX_SETEGID 111

#define POSIX_SETUID 112
#define POSIX_SETGID 113

#define POSIX_CHOWN 114
#define POSIX_CHMOD 115
#define POSIX_FCHOWN 116
#define POSIX_FCHMOD 117
#define POSIX_FCHDIR 118

#define POSIX_STATVFS 119
#define POSIX_FSTATVFS 120

#define PEDIGREE_UNWIND_SIGNAL 121

#define POSIX_MSYNC 122

#define POSIX_GETPEERNAME 123

#define POSIX_FSYNC 124

#define POSIX_MPROTECT 125

#define POSIX_REALPATH 126

#define POSIX_TIMES 127
#define POSIX_GETRUSAGE 128

#define POSIX_GETSOCKOPT 129
#define POSIX_GETPPID 130
#define POSIX_UTIME 131
#define POSIX_UTIMES 132
#define POSIX_CHROOT 133

#define POSIX_RMDIR 134
#define POSIX_GETGRNAM 135
#define POSIX_GETGRGID 136
#define POSIX_UMASK 137
#define POSIX_GETSOCKNAME 138
#define POSIX_WRITEV 139
#define POSIX_READV 140
#define POSIX_GETDENTS 141
#define POSIX_GETTID 142
#define POSIX_BRK 143

#define POSIX_PTSNAME 200
#define POSIX_TTYNAME 201
#define POSIX_TCSETPGRP 202
#define POSIX_TCGETPGRP 203

#define POSIX_USLEEP 204

#define POSIX_PEDIGREE_CREATE_WAITER 205
#define POSIX_PEDIGREE_DESTROY_WAITER 206
#define POSIX_PEDIGREE_THREAD_WAIT_FOR 207
#define POSIX_PEDIGREE_THREAD_TRIGGER 209

#define POSIX_PEDIGREE_GET_INFO_BLOCK 210

// For pthreads
#define POSIX_SET_TLS_AREA 211

#define POSIX_FUTEX 212
#define POSIX_UNAME 213
#define POSIX_ARCH_PRCTL 214
#define POSIX_CLONE 215
#define POSIX_PAUSE 216
#define POSIX_GETDENTS64 217
#define POSIX_L_SYSLOG 218
#define POSIX_FLOCK 219

#define POSIX_OPENAT 220
#define POSIX_MKDIRAT 221
#define POSIX_FCHOWNAT 222
#define POSIX_FUTIMESAT 223
#define POSIX_UNLINKAT 224
#define POSIX_RENAMEAT 225
#define POSIX_LINKAT 226
#define POSIX_SYMLINKAT 227
#define POSIX_READLINKAT 228
#define POSIX_FCHMODAT 229
#define POSIX_FACCESSAT 230
#define POSIX_FSTATAT 231
#define POSIX_SETGROUPS 232
#define POSIX_EXIT_GROUP 233
#define POSIX_GETRLIMIT 234
#define POSIX_GETPRIORITY 235
#define POSIX_SETPRIORITY 236
#define POSIX_GETXATTR 237
#define POSIX_LGETXATTR 238
#define POSIX_FGETXATTR 239
#define POSIX_MKNOD 240
#define POSIX_SETREUID 241
#define POSIX_SETREGID 242
#define POSIX_STATFS 243
#define POSIX_FSTATFS 244
#define POSIX_SETHOSTNAME 245
#define POSIX_CREAT 246
#define POSIX_SET_ROBUST_LIST 247
#define POSIX_GET_ROBUST_LIST 248
#define POSIX_GETGROUPS 249
#define POSIX_MOUNT 250
#define POSIX_SETTIMEOFDAY 251
#define POSIX_SETRLIMIT 252
#define POSIX_SETSOCKOPT 253
#define POSIX_GETPGID 254

#define POSIX_SETRESUID 255
#define POSIX_SETRESGID 256
#define POSIX_GETRESUID 257
#define POSIX_GETRESGID 258

#define POSIX_IOPERM 259
#define POSIX_IOPL 260

#define POSIX_TIME 261
#define POSIX_GETITIMER 262
#define POSIX_SETITIMER 263
#define POSIX_SOCKETPAIR 264
#define POSIX_SENDMSG 265
#define POSIX_RECVMSG 266
#define POSIX_CAPGET 267
#define POSIX_CAPSET 268
#define POSIX_PRCTL 269
#define POSIX_REBOOT 270
#define POSIX_ACCEPT4 271
#define POSIX_PIPE2 272
#define POSIX_GETRANDOM 273
#define POSIX_SET_TID_ADDRESS 274
#define POSIX_UMOUNT2 275
#define POSIX_EPOLL_CREATE 276
#define POSIX_EPOLL_CREATE1 277
#define POSIX_EPOLL_CTL 278
#define POSIX_EPOLL_WAIT 279
#define POSIX_EPOLL_PWAIT 280
#define POSIX_EVENTFD 281
#define POSIX_EVENTFD2 282
#define POSIX_PPOLL 283
#define POSIX_PSELECT6 284
#define POSIX_CLOCK_GETRES 285
#define POSIX_CLOCK_NANOSLEEP 286
#define POSIX_TKILL 287
#define POSIX_TGKILL 288
#define POSIX_RT_SIGSUSPEND 289
#define POSIX_PREAD64 290
#define POSIX_PWRITE64 291
#define POSIX_PRLIMIT64 292
#define POSIX_MEMBARRIER 293
#define POSIX_FACCESSAT2 294
#define POSIX_DUP3 295
#define POSIX_PREADV 296
#define POSIX_PWRITEV 297
#define POSIX_PREADV2 298
#define POSIX_PWRITEV2 299
#define POSIX_INOTIFY_INIT 300
#define POSIX_INOTIFY_INIT1 301
#define POSIX_INOTIFY_ADD_WATCH 302
#define POSIX_INOTIFY_RM_WATCH 303

#define POSIX_SEMGET 304
#define POSIX_SEMOP 305
#define POSIX_SEMCTL 306
#define POSIX_SEMTIMEDOP 307
#define POSIX_MSGGET 308
#define POSIX_MSGSND 309
#define POSIX_MSGRCV 310
#define POSIX_MSGCTL 311
#define POSIX_MQ_OPEN 312
#define POSIX_MQ_UNLINK 313
#define POSIX_MQ_TIMEDSEND 314
#define POSIX_MQ_TIMEDRECEIVE 315
#define POSIX_MQ_NOTIFY 316
#define POSIX_MQ_GETSETATTR 317

#define POSIX_SHMGET 318
#define POSIX_SHMAT 319
#define POSIX_SHMDT 320
#define POSIX_SHMCTL 321

#define POSIX_RT_SIGPENDING 322
#define POSIX_RT_SIGTIMEDWAIT 323
#define POSIX_RT_SIGQUEUEINFO 324
#define POSIX_TIMER_CREATE 325
#define POSIX_TIMER_SETTIME 326
#define POSIX_TIMER_GETTIME 327
#define POSIX_TIMER_GETOVERRUN 328
#define POSIX_TIMER_DELETE 329
#define POSIX_CLOCK_SETTIME 330
#define POSIX_SIGNALFD 331
#define POSIX_SIGNALFD4 332
#define POSIX_TIMERFD_CREATE 333
#define POSIX_TIMERFD_SETTIME 334
#define POSIX_TIMERFD_GETTIME 335
#define POSIX_MREMAP 336
#define POSIX_MINCORE 337
#define POSIX_MADVISE 338
#define POSIX_MEMFD_CREATE 339
#define POSIX_SENDFILE 340
#define POSIX_COPY_FILE_RANGE 341
#define POSIX_SPLICE 342
#define POSIX_TEE 343
#define POSIX_VMSPLICE 344
#define POSIX_MLOCK 345
#define POSIX_MUNLOCK 346
#define POSIX_MLOCKALL 347
#define POSIX_MUNLOCKALL 348
#define POSIX_MLOCK2 349
#define POSIX_REMAP_FILE_PAGES 350
#define POSIX_SETXATTR 351
#define POSIX_LSETXATTR 352
#define POSIX_FSETXATTR 353
#define POSIX_LISTXATTR 354
#define POSIX_LLISTXATTR 355
#define POSIX_FLISTXATTR 356
#define POSIX_REMOVEXATTR 357
#define POSIX_LREMOVEXATTR 358
#define POSIX_FREMOVEXATTR 359
#define POSIX_FANOTIFY_INIT 360
#define POSIX_FANOTIFY_MARK 361
#define POSIX_NAME_TO_HANDLE_AT 362
#define POSIX_OPEN_BY_HANDLE_AT 363
#define POSIX_SETFSUID 364
#define POSIX_SETFSGID 365
#define POSIX_PROCESS_VM_READV 366
#define POSIX_PROCESS_VM_WRITEV 367
#define POSIX_UNSHARE 368
#define POSIX_SETNS 369
#define POSIX_SETDOMAINNAME 370
#define POSIX_SCHED_SETPARAM 371
#define POSIX_SCHED_GETPARAM 372
#define POSIX_SCHED_SETSCHEDULER 373
#define POSIX_SCHED_GETSCHEDULER 374
#define POSIX_SCHED_GET_PRIORITY_MAX 375
#define POSIX_SCHED_GET_PRIORITY_MIN 376
#define POSIX_SCHED_SETAFFINITY 377
#define POSIX_SCHED_GETAFFINITY 378
#define POSIX_GETCPU 379
#define POSIX_SCHED_RR_GET_INTERVAL 380
#define POSIX_WAITID 381
#define POSIX_PTRACE 382
#define POSIX_FDATASYNC 383
#define POSIX_READAHEAD 384
#define POSIX_FADVISE64 385
#define POSIX_SYNC_FILE_RANGE 386
#define POSIX_ADJTIMEX 387
#define POSIX_CLOCK_ADJTIME 388
#define POSIX_DELETE_MODULE 389
#define POSIX_SYNC 390
#define POSIX_SYNCFS 391
#define POSIX_GETSID 392
#define POSIX_FALLOCATE 393
#define POSIX_RENAMEAT2 394
#define POSIX_RECVMMSG 395
#define POSIX_INIT_MODULE 396
#define POSIX_EXECVEAT 397
#define POSIX_ACCT 398
#define POSIX_VHANGUP 399
#define POSIX_QUOTACTL 400
#define POSIX_SWAPON 401
#define POSIX_SWAPOFF 402
#define POSIX_SYSINFO 403
#define POSIX_PERSONALITY 404
#define POSIX_PIVOT_ROOT 405
#define POSIX_TRUNCATE 406
#define POSIX_LCHOWN 407
#define POSIX_UTIMENSAT 408
#define POSIX_STATX 409
#define POSIX_FCHMODAT2 410
#define POSIX_MKNODAT 411
#define POSIX_VFORK 412

#endif
